(function(g){var window=this;'use strict';var Lv=function(q){q.publish("cardstatechange",q.aO()&&q.Ew()?1:0)},Bx=function(q,a){var w=g.kc(a),G=w?a:arguments;
for(w=w?0:1;w<G.length;w++){if(q==null)return;q=q[G[w]]}return q},Bae=function(q){var a=g.RR(q);
q=g.gh(q);return new g.Xr(a.x,a.y,q.width,q.height)},rn6=function(q,a,w){var G=G===void 0?{}:G;
var k;return k=g.$t(q,a,function(){g.sH(k);w.apply(q,arguments)},G)},My=function(q){q=g.lV(q);
delete rG[q];g.KH(rG)&&nv&&nv.stop()},Mn8=function(){nv||(nv=new g.o1(function(){n0V()},20));
var q=nv;q.isActive()||q.start()},n0V=function(){var q=g.Kw();
g.yx(rG,function(a){hiy(a,q)});
g.KH(rG)||Mn8()},hi=function(q,a,w,G){g.b9.call(this);
if(!Array.isArray(q)||!Array.isArray(a))throw Error("Start and end parameters must be arrays");if(q.length!=a.length)throw Error("Start and end points must be the same length");this.U=q;this.X=a;this.duration=w;this.D=G;this.coords=[];this.progress=this.L=0;this.Y=null},hiy=function(q,a){a<q.startTime&&(q.endTime=a+q.endTime-q.startTime,q.startTime=a);
q.progress=(a-q.startTime)/(q.endTime-q.startTime);q.progress>1&&(q.progress=1);q.L=1E3/(a-q.Y);q.Y=a;SzI(q,q.progress);q.progress==1?(q.V=0,My(q),q.onFinish(),q.Km()):q.isPlaying()&&q.JN()},SzI=function(q,a){typeof q.D==="function"&&(a=q.D(a));
q.coords=Array(q.U.length);for(var w=0;w<q.U.length;w++)q.coords[w]=(q.X[w]-q.U[w])*a+q.U[w]},fLI=function(q,a){g.t1.call(this,q);
this.coords=a.coords;this.x=a.coords[0];this.y=a.coords[1];this.z=a.coords[2];this.duration=a.duration;this.progress=a.progress;this.fps=a.L;this.state=a.V},Sh=function(q,a,w,G,k){hi.call(this,a,w,G,k);
this.element=q},Hi6=function(q,a,w,G,k){if(a.length!=2||w.length!=2)throw Error("Start and end points must be 2D");
Sh.call(this,q,a,w,G,k)},cnc=function(q){return Math.pow(q,3)},p3I=function(q){return 3*q*q-2*q*q*q},U0R=function(q){g.c.call(this);
this.U=q||window;this.V=[]},fv=function(q){return q.baseUrl||null},Hx=function(q,a){return g.L$(g.sd(q,a),function(w){return!!w})},X3U=function(q,a,w){function G($l){var ey=$l.hovercardButton;
if(!ey)return null;ey=ey.subscribeButtonRenderer;if(!ey)return null;var Nm=b(ey.unsubscribedButtonText),a_=b(ey.subscribedButtonText);if(ey.subscribed){var BJ=b(ey.subscriberCountWithUnsubscribeText);var WJ=b(ey.subscriberCountText)}else BJ=b(ey.subscriberCountText),WJ=b(ey.subscriberCountWithSubscribeText);var gy=null;if($l.signinEndpoint){gy=Bx($l,"signinEndpoint","webNavigationEndpointData","url");if(!gy){var F8,eK;gy=(eK=g.I((F8=ey.signInEndpoint)==null?void 0:F8.commandMetadata,g.Zk))==null?
void 0:eK.url}if(!gy)return null}return Nm&&(a_||gy)?{subscribed:ey.subscribed,subscribeText:Nm,subscribeCount:BJ,unsubscribeText:a_,unsubscribeCount:WJ,enabled:ey.enabled,signinUrl:gy,classic:$l.useClassicSubscribeButton}:null}
function k($l){if($l){var ey=[],Nm=$l.videoId;Nm&&ey.push("v="+Nm);(Nm=$l.playlistId)&&ey.push("list="+Nm);($l=$l.startTimeSeconds)&&ey.push("t="+$l);return"/watch?"+ey.join("&")}}
function b($l){if(!$l)return null;var ey=$l.simpleText;return ey?ey:$l.runs?g.sd($l.runs,function(Nm){return Nm.text}).join(""):null}
a=a.endscreenElementRenderer;if(!a)return null;var O=a.style,e=a.endpoint||{},N=null,Y=null,P=!1,K=null,d=null,T=null,F=null,J=!1,Q=null,B=null,L=null,M=null,H=null,X=null;if(O==="VIDEO")g.I(e,g.Be)?N=g.I(e,g.Be).url:(X=g.I(e,g.Er),N=k(X)),Y=!1,K=q,a.thumbnailOverlays?(P=a.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,d=b(P.text),P=P.style==="LIVE"):d=b(a.videoDuration);else if(O==="PLAYLIST")g.I(e,g.Be)?N=g.I(e,g.Be).url:(X=g.I(e,g.Er),N=k(X)),Y=!1,K=q,T=b(a.playlistLength);else if(O===
"CHANNEL"){if(J=Bx(e,"browseEndpoint","browseId"))F=J,N="/channel/"+F;Y=!1;K="new";(J=!!a.isSubscribe)?Q=G(a):B=b(a.subscribersText)}else O==="WEBSITE"?((L=Bx(e,"urlEndpoint","url"))&&(N=L),Y=!0,K="new",L=a.icon.thumbnails[0].url):O==="CREATOR_MERCHANDISE"&&(a.productPrice&&(M=b(a.productPrice)),a.additionalFeesText&&(H=b(a.additionalFeesText)),(Y=Bx(e,"urlEndpoint","url"))&&(N=Y),Y=!0,K="new");q=Bx(a,"title","accessibility","accessibilityData","label");var D=a.endpoint?a.endpoint.clickTrackingParams:
null,z="";if(a.metadata){var Oj=b(a.metadata);Oj&&(z=Oj)}return{id:"element-"+w,type:O,title:b(a.title),metadata:z,callToAction:b(a.callToAction),mw:a.image,iconUrl:L,left:Number(a.left),width:Number(a.width),top:Number(a.top),aspectRatio:Number(a.aspectRatio),startMs:Math.floor(Number(a.startMs)),endMs:Math.floor(Number(a.endMs)),videoDuration:d,Jy:P,playlistLength:T,channelId:F,subscribeButton:Q,subscribersText:B,isSubscribe:J,targetUrl:N||null,wD:Y,sessionData:D?{itct:D}:null,MZh:K,cA:q?q:null,
isPlaceholder:a.isPlaceholder,impressionUrls:Hx(a.impressionUrls||[],fv),Hy:Hx(a.hovercardShowUrls||[],fv),clickUrls:Hx(e.loggingUrls||[],fv),visualElement:g.KF(a.trackingParams),productPrice:M,additionalFeesText:H,watchEndpoint:X||null}},jLx=function(q,a){var w={startMs:Math.floor(Number(q.startMs)),
impressionUrls:Hx(q.impressionUrls||[],fv),elements:Hx(q.elements||[],function(G,k){return X3U(a,G,k)})};
q.trackingParams&&(w.visualElement=g.KF(q.trackingParams));return w},o0l=function(q){g.md.call(this,q);
this.Y=this.endscreen=null;this.U={};this.L={};this.D=this.W=null;this.S=[];this.V=null;this.F9=!0;this.X=0;q=q.B();this.J=g.kM(q)||g.OV(q);this.events=new g.Ee(this);g.p(this,this.events);this.events.C(this.player,g.oM("creatorendscreen"),this.onCueRangeEnter);this.events.C(this.player,g.IM("creatorendscreen"),this.onCueRangeExit);this.events.C(this.player,"resize",this.sA);this.events.C(window,"focus",this.M4Q);this.load();var a=g.dp("STYLE");(g.kA("HEAD")[0]||document.body).appendChild(a);this.addOnDisposeCallback(function(){g.Cn(a)});
a.sheet&&(a.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),a.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},ILe=function(q){return q.player.getVideoData().J8?"current":q.J?"new":"current"},cx=function(q){return q.player.B().playerStyle==="creator-endscreen-editor"},uix=function(q){var a=q.player.getVideoData(),w=a.videoId;
q.Y&&q.Y.abort();w={method:"POST",onFinish:function(k){var b=q.Y=null;k.status===200&&(k=k.responseText,k.substring(0,3)===")]}"&&(k=k.substring(3),b=JSON.parse(k),b=jLx(b,ILe(q))));pv(q,b)},
urlParams:{v:w},withCredentials:!0};q.J&&(w.urlParams.ptype="embedded");var G=a.pL;G&&(w.postParams={ad_tracking:G});if(a=g.uAK(a))if(a=g.OX(a),a=g.GR(a))q.Y=g.Cy(a,w)},pv=function(q,a,w){w=w===void 0?!0:w;
q.player.XC("creatorendscreen");q.W&&(q.W.dispose(),q.W=null,q.D.dispose(),q.D=null);for(var G=g.V(Object.values(q.U)),k=G.next();!k.done;k=G.next())k.value.dispose();q.U={};q.L={};q.S.length>0&&(q.S.forEach(function(e){e.dispose()}),q.S.length=0);
q.V&&(g.wU(q.V,"ytp-ce-element-show"),q.V.setAttribute("aria-hidden","true"));q.X=0;if((q.endscreen=a)&&a.elements){w&&tny(q);w=[];G=new g.Xo(a.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});w.push(G);q.player.B().U||(q.W=new g.u({G:"div",N:"ytp-ce-shadow"}),g.DZ(q.player,q.W.element,4),q.D=new g.zs(q.W,200));for(G=0;G<a.elements.length;++G){k=a.elements[G];var b=v07(q,k);if(b){q.U[k.id]=b;q.L[k.id]=k;g.DZ(q.player,b.element,4);var O=new g.Xo(k.startMs,k.endMs,{id:"ytp-ce-element-"+
k.id,namespace:"creatorendscreen"});w.push(O);ziB(q,b,k)}else g.Qa(new g.UH("buildEndscreenElement null",k))}q.player.N9(w);q.sA()}},tny=function(q){var a=g.TX(),w=g.$f();
w&&a&&q.endscreen.visualElement&&g.tK(g.cC)(void 0,w,a,q.endscreen.visualElement)},v07=function(q,a){var w=null;
switch(a.type){case "VIDEO":q={G:"div",vT:["ytp-ce-element","ytp-ce-video"],Z:{tabindex:"0","aria-label":a.cA||"","aria-hidden":"true"},K:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",Z:UM(a)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",Z:{href:XO(q,a.targetUrl),tabindex:"-1"},K:[{G:"div",vT:["ytp-ce-video-title","ytp-webkit-ellipsis"],Z:{dir:g.YX(a.title||"")},ue:a.title},{G:"div",N:a.Jy?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ue:a.videoDuration||void 0}]}]};w=new g.u(q);break;case "PLAYLIST":q={G:"div",vT:["ytp-ce-element","ytp-ce-playlist"],Z:{tabindex:"0","aria-label":a.cA||"","aria-hidden":"true"},K:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",Z:UM(a)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",Z:{href:XO(q,a.targetUrl),tabindex:"-1"},K:[{G:"div",vT:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Z:{dir:g.YX(a.title||"")},ue:a.title},{G:"div",N:"ytp-ce-playlist-count",
K:[{G:"div",N:"ytp-ce-playlist-icon"},{G:"div",N:"ytp-ce-playlist-count-text",ue:a.playlistLength||void 0}]}]}]};w=new g.u(q);break;case "CHANNEL":w={G:"div",vT:["ytp-ce-element","ytp-ce-channel",a.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Z:{tabindex:"0","aria-label":a.cA||"","aria-hidden":"true"},K:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",K:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
K:[{G:"div",N:"ytp-ce-expanding-overlay-body",K:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",K:[{G:"a",vT:["ytp-ce-channel-title","ytp-ce-link"],Z:{href:XO(q,a.targetUrl),target:"_blank",tabindex:"-1",dir:g.YX(a.title||"")},ue:a.title},a.subscribeButton?{G:"div",N:"ytp-ce-subscribe-container",K:[{G:"div",N:"ytp-ce-channel-subscribe"}]}:"",a.subscribersText?{G:"div",N:"ytp-ce-channel-subscribers-text",ue:a.subscribersText}:"",a.metadata?{G:"div",vT:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ue:a.metadata}:""]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",Z:UM(a)}]};w=new g.u(w);var G=g.ON(document,"div","ytp-ce-channel-subscribe",w.element)[0];if(a.subscribeButton&&a.channelId){g.gU(G,"ytp-ce-subscribe-button");if(q.player.B().U){var k=null;var b=a.sessionData.itct}else k="endscreen",b=null;k=new g.wm(a.subscribeButton.subscribeText,a.subscribeButton.subscribeCount,a.subscribeButton.unsubscribeText,a.subscribeButton.unsubscribeCount,!!a.subscribeButton.enabled,!!a.subscribeButton.classic,
a.channelId,!!a.subscribeButton.subscribed,k,b,q.player,!1);G.appendChild(k.element);q.S.push(k)}break;case "WEBSITE":q={G:"div",vT:["ytp-ce-element","ytp-ce-website"],Z:{tabindex:"0","aria-label":a.cA||"","aria-hidden":"true"},K:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",K:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",K:[{G:"div",N:"ytp-ce-expanding-overlay-body",K:[{G:"div",
N:"ytp-ce-expanding-overlay-body-padding",K:[{G:"div",N:"ytp-ce-website-title",Z:{dir:g.YX(a.title||"")},ue:a.title},{G:"div",N:"ytp-ce-website-metadata",ue:a.metadata},{G:"a",vT:["ytp-ce-website-goto","ytp-ce-link"],Z:{href:XO(q,a.targetUrl),target:"_blank",tabindex:"-1"},ue:a.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",Z:UM(a)},{G:"div",N:"ytp-ce-expanding-icon",Z:iiV(a.iconUrl)}]};w=new g.u(q);break;case "CREATOR_MERCHANDISE":w="",a.productPrice&&(w={G:"div",N:"ytp-ce-merchandise-price-container",
K:[{G:"div",N:"ytp-ce-merchandise-price",ue:a.productPrice}]},a.additionalFeesText&&w.K.push({G:"div",N:"ytp-ce-merchandise-additional-fees",ue:a.additionalFeesText})),q={G:"div",vT:["ytp-ce-element","ytp-ce-merchandise"],Z:{tabindex:"0","aria-label":a.cA||"","aria-hidden":"true"},K:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",K:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
K:[{G:"div",N:"ytp-ce-expanding-overlay-body",K:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",K:[{G:"div",N:"ytp-ce-merchandise-title",Z:{dir:g.YX(a.title||"")},ue:a.title},w,{G:"div",N:"ytp-ce-merchandise-metadata",ue:a.metadata},{G:"a",vT:["ytp-ce-merchandise-goto","ytp-ce-link"],Z:{href:XO(q,a.targetUrl),target:"_blank",tabindex:"-1"},ue:a.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",Z:UM(a)},{G:"div",N:"ytp-ce-merchandise-invideo-cta-container",K:[{G:"div",N:"ytp-ce-merchandise-invideo-cta",
ue:a.callToAction||void 0}]}]},w=new g.u(q)}a.isPlaceholder&&g.gU(w.element,"ytp-ce-placeholder");return w},UM=function(q){if(q.mw)var a=q.mw.thumbnails;
return iiV(a?a[a.length-1].url:null)},iiV=function(q){return q?{style:"background-image: url("+q+")"}:{}},ziB=function(q,a,w){function G(N){N&&(a.listen("blur",function(){N.style.display!="none"&&q.F9&&N.focus()}),a.C(N,"focus",b),a.C(N,"blur",O))}
function k(N){q.X+=N;q.X>0?(g.gU(a.element,"ytp-ce-force-expand"),jh(q,w.id,!0)):(g.wU(a.element,"ytp-ce-force-expand"),g.wU(a.element,"ytp-ce-element-hover"),jh(q,w.id,!1))}
function b(){k(1)}
function O(){k(-1)}
a.listen("mouseenter",function(){WC7(q,a,w)});
a.listen("mouseleave",function(){D0y(q,a,w)});
q.player.B().U||a.listen("click",function(){g.gU(a.element,"ytp-ce-element-hover")});
a.listen("click",function(N){RiK(q,w,N)});
a.listen("keypress",function(N){RiK(q,w,N)});
a.listen("focus",function(){WC7(q,a,w)});
a.listen("blur",function(){D0y(q,a,w)});
a.listen("touchstart",function(){WC7(q,a,w)});
var e=g.lh("ytp-ce-expanding-overlay-hider",a.element);e&&a.C(e,"touchstart",function(N){N.stopPropagation();g.wU(a.element,"ytp-ce-element-hover");g.wU(a.element,"ytp-ce-force-expand")});
a.listen("keydown",function(N){q.F9=N.keyCode===9&&!N.shiftKey});
G(g.lh("ytp-sb-subscribe",a.element));G(g.lh("ytp-sb-unsubscribe",a.element));a.listen("focus",b);a.listen("blur",O)},RiK=function(q,a,w){if(a.targetUrl&&(!w||w.type!=="keypress"||w.keyCode===13)){for(var G=w.target;G&&!g.qG(G,"ytp-ce-element");){g.qG(G,"subscribe-label")&&yny(q,a);
if(g.qG(G,"ytp-ce-channel-subscribe"))return;G=G.parentElement||null}if(!G||g.qG(G,"ytp-ce-element-hover")){w.preventDefault();w.stopPropagation();if(G=q.U[a.id])D0y(q,G,a),G.element.blur();if(w.ctrlKey||w.metaKey||a.MZh==="new")yny(q,a),q.player.sendVideoStatsEngageEvent(17,void 0),q.player.pauseVideo(),w=g.OX(XO(q,a.targetUrl)),w=g.GR(w),g.HA(w,void 0,a.sessionData);else{var k=g.Zg(q.player.B())||q.player.getVideoData().J8,b=function(){var O=XO(q,a.targetUrl),e=a.sessionData,N=a.watchEndpoint,Y=
g.RI(O);k&&Y&&(Y.v||Y.list)?q.player.Fj(Y.v,e,Y.list,!1,void 0,N||void 0):g.fj(O,e)};
yny(q,a,function(){q.player.sendVideoStatsEngageEvent(17,b)})}}}},XO=function(q,a){q=q.player.B();
if(a){if(a.startsWith("//"))return q.protocol+":"+a;if(a.startsWith("/"))return g.LA(q)+a}else return"";return a},WC7=function(q,a,w){g.qG(a.element,"ytp-ce-element-hover")||(w.type==="VIDEO"||w.type==="PLAYLIST"?g.gU(a.element,"ytp-ce-element-hover"):q.player.B().U?(new g.o1(function(){g.gU(a.element,"ytp-ce-element-hover")},200)).start():g.gU(a.element,"ytp-ce-element-hover"),oC(q,w.Hy),jh(q,w.id,!0))},D0y=function(q,a,w){g.wU(a.element,"ytp-ce-element-hover");
g.wU(a.element,"ytp-ce-force-expand");jh(q,w.id,!1)},jh=function(q,a,w){q.W&&(w?q.D.show():q.D.hide());
for(var G=g.V(Object.keys(q.U)),k=G.next();!k.done;k=G.next())k=k.value,k!==a&&g.kX(q.U[k].element,"ytp-ce-element-shadow-show",w)},oC=function(q,a,w){function G(){b||(k++,k===a.length&&(O.stop(),w&&w()))}
if(!a||a.length===0||cx(q))w&&w();else{a=qg6(q,a);var k=0,b=!1,O=new g.o1(function(){b=!0;w&&w()},1E3,q);
O.start();for(q=0;q<a.length;q++)g.re(a[q],G)}},yny=function(q,a,w){oC(q,a.clickUrls,w);
(q=g.$f())&&a.wD&&g.id(q,a.visualElement)},qg6=function(q,a){var w=q.player.getVideoData().clientPlaybackNonce;
q=q.player.getCurrentTime().toFixed(2);w={CPN:w,AD_CPN:w,MT:q};q=[];for(var G=0;G<a.length;G++)q.push(gNy(a[G],w));return q},gNy=function(q,a){return q.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(w){var G=unescape(w);
G=G.substring(1,G.length-1);return a[G]?escape(a[G]):w})},a$e=function(q){return typeof q==="string"?q:""},IC=function(q,a,w){for(var G in a)if(a[G]===q)return q;
return w},w$J=function(q,a,w,G){this.value=q;
this.target=a;this.showLinkIcon=w;this.V=G},uK=function(q){return q.value?q.value:null},ti=function(q){if(!q)return null;
var a=g.OX(a$e(q.value));a=g.GR(a);if(!a)return null;var w=IC(q.target,GU7,"current");if(w==null)q=null;else{var G=q.show_link_icon;q=new w$J(a,w,G==="true"||G==="false"?G==="true":!0,q.pause_on_navigation!=null?q.pause_on_navigation:!0)}return q},kUl=function(q,a,w){this.type=q;
this.trigger=a;this.url=w},l$K=function(q){if(!q)return null;
var a=IC(q.type,blR),w=IC(q.trigger,OlI);q=q.url;q=Array.isArray(q)&&q.length?q[0]:q;q=ti(q?q:null);return a?new kUl(a,w,q):null},evw=function(q,a,w,G,k){this.id=q;
this.type=a;this.style=w;this.data=k;this.action=G||[]},NbJ=function(q,a){return g.Z7(q.action,a)},Ygx=function(q,a){this.context=q;
this.V=a},PQy=function(q){return q.customMessage?vx("div","iv-card-message",q.customMessage):""},zW=function(q,a){q="background-image: url("+q+");";
var w=[];a&&w.push(a);return{G:"div",N:"iv-card-image",Z:{style:q},K:w}},KAe=function(q){if(!q.metaInfo||q.metaInfo.length===0)return"";
var a=[];q=g.V(q.metaInfo);for(var w=q.next();!w.done;w=q.next())a.push(vx("li","",w.value));return{G:"ul",N:"iv-card-meta-info",K:a}},vx=function(q,a,w){a?typeof a==="string"?a={"class":a}:Array.isArray(a)&&(a={"class":a.join(" ")}):a={};
a.dir=g.YX(w);return{G:q,Z:a,ue:w}},duV=function(q){if(!q.customMessage)return"";
var a=["iv-card-action","iv-card-primary-link"],w={};q.Es&&(a.push("iv-card-action-icon"),w.style="background-image: url("+q.Es+");");w.dir=g.YX(q.customMessage);var G=[{G:"span",ue:q.customMessage}];q.showLinkIcon&&(G.push("\u00a0"),G.push({G:"span",N:"iv-card-link-icon"}));return{G:"div",vT:a,Z:w,K:G}},iK=function(q,a,w,G){if(G){a=g.V(a);
for(var k=a.next();!k.done;k=a.next())q.V(k.value,G,w.id,w.sessionData,w.dT.click,5)}},Tbe=function(q,a){this.merchant=q;
this.price=a},$u8=function(q){var a;
(a=q)&&!(a=q.length>1?q.charAt(0)==="/"&&q.charAt(1)!=="/":q==="/")&&(a=q.replace(/^(https?:)?\/\//,"").split("/",1),a=!a||a.length<1||!a[0]?[]:a[0].toLowerCase().split(".").reverse(),a=a[0]==="com"&&a[1]==="youtube"||a[0]==="be"&&a[1]==="youtu");return a?q.indexOf("/redirect?")===-1:!1},sjU=function(q,a){return a?a:$u8(q)?"current":"new"},Wx=function(q,a){g.c.call(this);
var w=this;this.element=q;this.context=a;this.IW=!1;this.St=new Map;this.A2=new Map;this.context.j.addEventListener(g.oM("annotations_module"),function(G){(G=w.St.get(G))&&G.apply(w)});
this.context.j.addEventListener(g.IM("annotations_module"),function(G){(G=w.A2.get(G))&&G.apply(w)})},DY=function(q,a,w,G,k,b,O){q.context.V.listen(a,"click",function(e){q.rb(w,G,k,b||[],O||0,e)});
q.context.V.listen(a,"touchstart",function(){q.IW=!1});
q.context.V.listen(a,"touchmove",function(){q.IW=!0})},FA6=function(q){var a;
return((a=g.I(q,g.Be))==null?0:a.url)?g.I(q,g.Be).url:(q=g.I(q,g.Er))&&q.videoId?(a="/watch?v="+q.videoId,q.playlistId&&(a+="&list="+q.playlistId),q.index&&(a+="&index="+q.index),q.startTimeSeconds&&(a+="&t="+q.startTimeSeconds),a):null},RC=function(q,a,w){return{RR:(q.impressionLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""}),
click:(w.loggingUrls||[]).map(function(G){return G.baseUrl||""}),
close:(a.dismissLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""}),
E0:(a.impressionLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""}),
p9:(a.clickLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""})}},CQB=function(q,a,w){Wx.call(this,a,w);
var G=this;this.j=q;this.eventId=null;this.uF=this.L7=this.yN=this.W=this.isInitialized=!1;this.cards=[];this.VN=this.D=this.EK=this.L=this.le=this.V=null;this.F9=[];this.UK=this.S=this.So=this.f7=null;this.X=0;this.jt=new g.o1(function(){},w.V7.mP?4E3:3E3);
g.p(this,this.jt);this.BT=new g.o1(function(){});
g.p(this,this.BT);this.y7=new Ygx(w,function(k,b,O,e,N,Y){DY(G,k,b,O,e,N,Y)});
this.J=new g.u({G:"div",N:"iv-drawer",Z:{id:"iv-drawer"},K:[{G:"div",N:"iv-drawer-header",Z:{"aria-role":"heading"},K:[{G:"span",N:"iv-drawer-header-text"},{G:"button",vT:["iv-drawer-close-button","ytp-button"],Z:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",N:"iv-drawer-content"}]});g.p(this,this.J);this.Y=this.J.element;this.h2=new g.zs(this.J,330);g.p(this,this.h2);this.OA=g.lh("iv-drawer-header-text",this.Y);this.U=g.lh("iv-drawer-content",this.Y);this.addCueRange(0,w.videoData.lengthSeconds*
1E3,"",function(){G.yN&&yA(G,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(G.yN=G.W)&&q1(G)});
this.Tl=new g.Ee(this);g.p(this,this.Tl);this.j.addEventListener("videodatachange",this.jR.bind(this))},Zll=function(q,a){a=a.data;
a.autoOpenMs&&q.addCueRange(a.autoOpenMs,0x8000000000000,"",function(){yA(q,"YOUTUBE_DRAWER_AUTO_OPEN")});
a.autoCloseMs&&q.addCueRange(a.autoCloseMs,0x8000000000000,"",function(){q1(q)});
var w=a.headerText;g.EN(q.OA,w);q.D&&(q.j.T("player_tooltip_data_title_killswitch")?q.D.setAttribute("title",w):q.D.setAttribute("data-tooltip-title",w));a.eventId&&(q.eventId=a.eventId);q.f7=g.KF(a.trackingParams);q.S=g.KF(a.closeTrackingParams);q.So=g.KF(a.iconTrackingParams)},ENV=function(q,a){var w=a.cardId?a.cardId:"cr:"+q.X,G=q.j.B().experiments.Zh("enable_error_corrections_infocard_web_client");
if(!a.content&&a.teaser.simpleCardTeaserRenderer&&G){var k=a.teaser.simpleCardTeaserRenderer,b=a.icon?a.icon.infoCardIconRenderer:null;if(k.channelAvatar&&k.channelAvatar.thumbnails&&k.channelAvatar.thumbnails.length>0)var O=gE(k.channelAvatar.thumbnails,22,22).url;a={id:w,timestamp:q.X,type:"simple",teaserText:g.OE(k.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:{},sponsored:!1,dT:{},Xx:null,Sc:k.trackingParams?
g.KF(k.trackingParams):null,So:b&&b.trackingParams?g.KF(b.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Es:null,title:"",customMessage:"",url:null,onClickCommand:k.onTapCommand||null,eQ:O};aD(q,a)}else{var e;if((e=a.content)==null?0:e.simpleCardContentRenderer){if(!a.cueRanges.length)return;O=(k=a.content)==null?void 0:k.simpleCardContentRenderer;k=a.teaser.simpleCardTeaserRenderer;b=a.icon?a.icon.infoCardIconRenderer:null;a={id:w,timestamp:q.X,type:"simple",teaserText:g.OE(k.message),
teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:wE(q,w,a,O),sponsored:!1,dT:RC(O,k,O.command),Xx:O.trackingParams?g.KF(O.trackingParams):null,Sc:k.trackingParams?g.KF(k.trackingParams):null,So:b&&b.trackingParams?g.KF(b.trackingParams):null,imageUrl:gE(O.image.thumbnails,290,290).url,displayDomain:O.displayDomain?g.OE(O.displayDomain):null,showLinkIcon:!!O.showLinkIcon,Es:null,title:O.title?g.OE(O.title):"",
customMessage:O.callToAction?g.OE(O.callToAction):"",url:g.I(O.command,g.Be).url?ti({pause_on_navigation:!q.context.videoData.isLivePlayback,target:"new",value:g.I(O.command,g.Be).url}):null,onClickCommand:null};aD(q,a)}else{var N;if((N=a.content)==null?0:N.collaboratorInfoCardContentRenderer){if(!a.cueRanges.length)return;O=(b=a.content)==null?void 0:b.collaboratorInfoCardContentRenderer;k=a.teaser.simpleCardTeaserRenderer;b=a.icon?a.icon.infoCardIconRenderer:null;a={id:w,timestamp:q.X,type:"collaborator",
teaserText:g.OE(k.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:wE(q,w,a,O),sponsored:!1,dT:RC(O,k,O.endpoint),Xx:O.trackingParams?g.KF(O.trackingParams):null,Sc:k.trackingParams?g.KF(k.trackingParams):null,So:b&&b.trackingParams?g.KF(b.trackingParams):null,channelId:g.I(O.endpoint,g.zO).browseId,customMessage:O.customText?g.OE(O.customText):null,profileImageUrl:gE(O.channelAvatar.thumbnails,290,
290).url,title:O.channelName?g.OE(O.channelName):"",metaInfo:[O.subscriberCountText?g.OE(O.subscriberCountText):""],url:ti({pause_on_navigation:!q.context.videoData.isLivePlayback,target:"new",value:g.I(O.endpoint,g.zO).canonicalBaseUrl?g.I(O.endpoint,g.zO).canonicalBaseUrl:"/channel/"+g.I(O.endpoint,g.zO).browseId}),onClickCommand:null};aD(q,a)}else{var Y;if((Y=a.content)==null?0:Y.playlistInfoCardContentRenderer){if(!a.cueRanges.length)return;var P;O=(P=a.content)==null?void 0:P.playlistInfoCardContentRenderer;
k=a.teaser.simpleCardTeaserRenderer;b=a.icon?a.icon.infoCardIconRenderer:null;a={id:w,timestamp:q.X,type:"playlist",teaserText:g.OE(k.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:wE(q,w,a,O),sponsored:!1,dT:RC(O,k,O.action),Xx:O.trackingParams?g.KF(O.trackingParams):null,Sc:k.trackingParams?g.KF(k.trackingParams):null,So:b&&b.trackingParams?g.KF(b.trackingParams):null,X4:gE(O.playlistThumbnail.thumbnails,
258,290).url,customMessage:O.customMessage?g.OE(O.customMessage):null,playlistVideoCount:g.OE(O.playlistVideoCount),title:O.playlistTitle?g.OE(O.playlistTitle):"",metaInfo:[O.channelName?g.OE(O.channelName):"",O.videoCountText?g.OE(O.videoCountText):""],url:ti({pause_on_navigation:!q.context.videoData.isLivePlayback,target:"new",value:FA6(O.action)}),onClickCommand:null};aD(q,a)}else{var K;if((K=a.content)==null?0:K.videoInfoCardContentRenderer){if(!a.cueRanges.length)return;var d;O=(d=a.content)==
null?void 0:d.videoInfoCardContentRenderer;k=a.teaser.simpleCardTeaserRenderer;b=a.icon?a.icon.infoCardIconRenderer:null;a={id:w,timestamp:q.X,type:"video",teaserText:g.OE(k.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:wE(q,w,a,O),sponsored:!1,dT:RC(O,k,O.action),Xx:O.trackingParams?g.KF(O.trackingParams):null,Sc:k.trackingParams?g.KF(k.trackingParams):null,So:b&&b.trackingParams?g.KF(b.trackingParams):
null,X4:gE(O.videoThumbnail.thumbnails,258,290).url,videoDuration:O.lengthString?g.OE(O.lengthString):null,customMessage:O.customMessage?g.OE(O.customMessage):null,title:O.videoTitle?g.OE(O.videoTitle):"",metaInfo:[O.channelName?g.OE(O.channelName):"",O.viewCountText?g.OE(O.viewCountText):""],isLiveNow:!!O.badge,url:ti({pause_on_navigation:!q.context.videoData.isLivePlayback,target:"new",value:FA6(O.action)}),onClickCommand:null};aD(q,a)}}}}}q.X++},gE=function(q,a,w){for(var G=-1,k=-1,b=0;b<q.length;b++){if(q[b].height===
a||q[b].width===w)return q[b];
((q[b].height||0)<a||(q[b].width||0)<w)&&(G<0||(q[G].height||0)<(q[b].height||0)||(q[G].width||0)<(q[b].width||0))?G=b:((q[b].height||0)>=a||(q[b].width||0)>=w)&&(k<0||(q[k].height||0)>(q[b].height||0)||(q[k].width||0)>(q[b].width||0))&&(k=b)}return q[k>=0?k:G]},wE=function(q,a,w,G){return{feature:w.feature?w.feature:"cards",
src_vid:q.context.videoData.videoId,annotation_id:a,ei:q.context.videoData.eventId||"",itct:G.trackingParams||""}},JYJ=function(q,a){if(a=V8U(q,a))a===q.V&&(q.V=null),q.j.removeCueRange(a.ly.id),g.Cn(a.GQ),g.mU(q.cards,a),q.JC(),Gc(q)},yA=function(q,a,w){if(!q.W){q.h2.show();
q.le=new g.o1(function(){g.gU(q.context.j.getRootNode(),g.El.IV_DRAWER_OPEN)},0);
q.le.start();q.Tl.C(q.U,"mousewheel",function(O){q.jt.start();O.preventDefault();O=O||window.event;var e=0;O.type=="MozMousePixelScroll"?e=0==(O.axis==O.HORIZONTAL_AXIS)?O.detail:0:window.opera?e=O.detail:e=O.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?O.wheelDeltaY/-30:O.wheelDeltaY/-1.2:O.wheelDelta/-1.6:O.wheelDeltaY/-3;if(O=e)q.U.scrollTop+=O});
q.W=!0;var G=g.$f();G&&q.f7&&q.S&&g.vC(G,[q.f7,q.S]);a={TRIGGER_TYPE:a};for(var k=g.V(q.cards),b=k.next();!b.done;b=k.next())b=b.value,b.GJ||(b.GJ=!0,muB(q.context.logger,b.ly.dT.RR,a)),G&&g.vC(G,[b.ly.Xx]);Lv(q.j);w&&(q.L=new g.o1(function(){q.EK=q.D;q.VN.focus()},330),q.L.start())}},q1=function(q){q.W&&(q.h2.hide(),g.JE(q.Tl),g.wU(q.context.j.getRootNode(),g.El.IV_DRAWER_OPEN),q.W=!1,Lv(q.j),q.L&&q.L.stop(),q.L=new g.o1(function(){q.EK&&(q.EK.focus(),q.EK=null)},330),q.L.start())},QjR=function(q){g.ah(q.cq(),
[g.El.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.DZ(q.j,q.Y,5);q.bP();q.D=g.lh("ytp-cards-button",q.j.getRootNode());q.VN=g.lh("iv-drawer-close-button",q.Y);q.isInitialized=!0},AYV=function(q){q.F9.push(g.i$("iv-teaser-shown",q.L8,q));
q.F9.push(g.i$("iv-teaser-hidden",q.u9t,q));q.F9.push(g.i$("iv-teaser-clicked",q.RU,q));q.uF=!0},xue=function(q,a){var w;
return a.onClickCommand&&((w=g.I(a.onClickCommand,g.aMK))==null?void 0:w.targetId)==="engagement-panel-error-corrections"?(q.UK=a,!0):!1},LAR=function(q,a){q.UK=a;
var w=q.j.getVideoData();if(!w)return!1;w=g.Rv(w);if(w==null?0:w.markersMap)for(var G,k=0;((G=w)==null?void 0:G.markersMap.length)>k;k++){var b=void 0,O=(b=w)==null?void 0:b.markersMap[k];if(O.key==="ERROR_CORRECTION_MARKERS"&&(b=void 0,(O=(b=O.value)==null?void 0:b.markers)&&O.length>0))return G=void 0,a.startMs=((G=g.I(O[0],g.J_l))==null?void 0:G.timeRangeStartMillis)||0,q.UK=null,!0}return!1},aD=function(q,a){if(!xue(q,a)||LAR(q,a)){var w=Bb8(q,a);
if(w){var G={ly:a,GQ:w.element,GJ:!1};if(a.onClickCommand)q.j.T("web_infocards_teaser_show_logging_fix")&&(q.uF||AYV(q),JYJ(q,a.id),w=q.findLastIndex(G),g.U6(q.cards,w,0,G));else{q.isInitialized||QjR(q);JYJ(q,a.id);var k=q.findLastIndex(G);g.U6(q.cards,k,0,G);w.HT(q.U,k);q.JC()}a.autoOpen?q.addCueRange(a.startMs,0x8000000000000,a.id,function(){q.W||(q.V=G,Gc(q),rYy(q,G),yA(q,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(w=q.context.j.getCurrentTime()*1E3,w<5E3&&w>a.startMs&&nNc(q,G),q.addCueRange(a.startMs,
a.startMs+1,a.id,function(){nNc(q,G)}),Gc(q))}}},Bb8=function(q,a){switch(a.type){case "simple":q=q.y7;
var w=a.displayDomain?{G:"div",N:"iv-card-image-text",ue:a.displayDomain}:void 0;var G=duV(a);w={G:"div",vT:["iv-card"],K:[{G:"a",N:"iv-click-target",Z:{href:a.url?uK(a.url)||"":""},K:[zW(a.imageUrl,w),{G:"div",N:"iv-card-content",K:[vx("h2",void 0,a.title),G]}]}]};w=new g.u(w);iK(q,g.bh("iv-click-target",w.element),a,a.url);a=w;break;case "collaborator":q=q.y7;w={G:"div",vT:["iv-card","iv-card-channel"],K:[{G:"a",vT:["iv-click-target"],Z:{href:uK(a.url)||"","data-ytid":a.channelId},K:[zW(a.profileImageUrl),
{G:"div",N:"iv-card-content",K:[PQy(a),{G:"h2",N:"iv-card-primary-link",ue:a.title},KAe(a)]}]}]};w=new g.u(w);iK(q,g.bh("iv-click-target",w.element),a,a.url);a=w;break;case "playlist":q=q.y7;w={G:"div",vT:["iv-card","iv-card-playlist"],K:[{G:"a",N:"iv-click-target",Z:{href:uK(a.url)||""},K:[zW(a.X4,{G:"div",N:"iv-card-image-overlay",K:[{G:"span",N:"iv-card-playlist-video-count",ue:a.playlistVideoCount}]}),{G:"div",N:"iv-card-content",K:[PQy(a),vx("h2","iv-card-primary-link",a.title),KAe(a)]}]}]};
w=new g.u(w);iK(q,g.bh("iv-click-target",w.element),a,a.url);a=w;break;case "productListing":q=q.y7;var k=a.offers.length!=0;w=["iv-card"];G="";var b=duV(a);k&&(w.push("iv-card-product-listing"),G="iv-card-primary-link",b=a.offers[0],k=[],b.price&&k.push({G:"div",N:"iv-card-offer-price",ue:b.price}),b.merchant&&k.push({G:"div",N:"iv-card-offer-merchant",ue:b.merchant}),b={G:"div",K:k});k=a.url?uK(a.url)||"":"";w={G:"div",vT:w,Z:{tabindex:"0"},K:[{G:"a",vT:["iv-card-image","iv-click-target"],Z:{style:"background-image: url("+
a.imageUrl+");",href:k,"aria-hidden":"true",tabindex:"-1"}},{G:"div",N:"iv-card-content",K:[a.sponsored?{G:"div",N:"iv-card-sponsored",K:["Sponsored",{G:"div",N:"iv-ad-info-container",K:[{G:"div",N:"iv-ad-info",ue:"{{adInfo}}"},{G:"div",N:"iv-ad-info-icon-container",K:[{G:"div",N:"iv-ad-info-icon"},{G:"div",N:"iv-ad-info-callout"}]}]}]}:"",{G:"a",N:"iv-click-target",Z:{href:k},K:[vx("h2",G,a.title),b]}]}]};w=new g.u(w);G=g.dp("span");g.EN(G,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
w.z0(G,"adInfo");iK(q,g.bh("iv-click-target",w.element),a,a.url);a=w;break;case "video":q=q.y7;G=a.videoDuration?{G:"span",N:"iv-card-video-duration",ue:a.videoDuration}:void 0;b=a.isLiveNow?{G:"span",vT:["yt-badge","yt-badge-live"],ue:"LIVE NOW"}:null;k={G:"div",vT:["iv-card","iv-card-video"],K:[{G:"a",N:"iv-click-target",Z:{href:((w=a.url)==null?void 0:uK(w))||""},K:[zW(a.X4,G),{G:"div",N:"iv-card-content",K:[PQy(a),vx("h2","iv-card-primary-link",a.title),KAe(a),b]}]}]};w=new g.u(k);iK(q,g.bh("iv-click-target",
w.element),a,a.url);a=w;break;default:return null}return a},M86=function(q){if(q.V)return q.V.ly.type==="productListing";
if(q.j.T("enable_wn_infocards")){var a;return!((a=q.cards)==null||!a.length)&&g.Fx(q.cards,function(w){return w.ly.type==="productListing"})}return g.Fx(q.cards,function(w){return w.ly.type==="productListing"})},Gc=function(q){g.kX(q.j.getRootNode(),"ytp-cards-shopping-active",M86(q))},nNc=function(q,a){if(!g.qG(q.j.getRootNode(),"ytp-cards-teaser-shown")){if(q.V!==a){var w=g.$f(),G=q.V?q.V.ly.So:q.So;
w&&G&&g.zX(w,[G]);q.V=a;Gc(q)}(w=q.isInitialized&&q.cq().style.display=="none")||(w=q.context.j.getPlayerState(),G=w===0&&q.context.j.getCurrentTime()===0,w=!(w===1||w===3||G));if(!w&&a.ly.teaserDurationMs){var k;w={teaserText:a.ly.teaserText,durationMs:a.ly.teaserDurationMs,onClickCommand:a.ly.onClickCommand,eQ:(k=a.ly.eQ)!=null?k:null};q.j.v_(!0,w)}q.BT.isActive()||((!q.W||!q.jt.isActive()&&q.L7)&&rYy(q,a),q.BT.start(910+a.ly.teaserDurationMs))}},rYy=function(q,a){q.J.Fw?(a=new hi([0,
q.U.scrollTop],[0,a.GQ.offsetTop],600,p3I),q.context.W.listen(a,"animate",function(w){q.U.scrollTop=w.y}),q.context.W.listen(a,"finish",function(w){q.U.scrollTop=w.y}),a.play()):(q.J.Ji(!0),q.U.scrollTop=a.GQ.offsetTop,q.J.Ji(!1))},kS=function(q){return q.V&&q.V.ly?q.V.ly:q.cards[0]&&q.cards[0].ly?q.cards[0].ly:null},V8U=function(q,a){return g.Z7(q.cards,function(w){return w.ly.id===a})},b8=function(q,a,w){Wx.call(this,q,a);
this.annotation=w;this.isActive=!1},hvy=function(q){var a=q.annotation.data;
"start_ms"in a&&"end_ms"in a&&q.addCueRange(Number(a.start_ms),Number(a.end_ms),q.annotation.id,function(){q.show()},function(){q.hide()})},Ov=function(q,a,w){b8.call(this,q,a,w);
this.U=null;this.X=!1;this.W=null;this.Y=!1;this.V=this.L=this.D=null},Sgc=function(q,a){var w=w===void 0?0:w;
var G=Bae(a).width;g.Wa(a,G);w=new Hi6(a,[G,a.offsetTop],[G-G-w,a.offsetTop],200,cnc);g.p(q,w);q.context.W.listen(w,"begin",function(){g.aT(a,!0)});
w.play()},cYe=function(q,a){if(a.channel_name){var w=q.createElement({G:"div",
vT:["iv-branding-context-name"],ue:a.channel_name}),G=q.createElement({G:"div",vT:["iv-branding-context-subscribe"]}),k=a.standalone_subscribe_button_data;k&&(q.V=new g.wm(k.subscribeText,k.subscribeCount,k.unsubscribeText,k.unsubscribeCount,!!k.enabled,!!k.classic,a.channel_id,!!k.subscribed,k.feature,a.session_data.itct,q.context.j,!1),q.V.HT(G));var b=q.createElement({G:"div",vT:["iv-branding-context-subscribe-caret"]}),O=q.createElement({G:"div",vT:["branding-context-container-inner"]});O.appendChild(b);
O.appendChild(w);O.appendChild(G);g.aT(O,!1);var e=q.createElement({G:"div",vT:["branding-context-container-outer"]});e.appendChild(O);g.IR(e,"right",a.image_width+"px");g.$A(q.cq(),e);q.W=new g.o1(function(){f$y(q,O,e)},500);
g.p(q,q.W);q.context.V.listen(q.cq(),"mouseover",function(){HlB(q,O,e,b,a.image_height)});
q.context.V.listen(q.cq(),"mouseout",function(){q.W.start()})}},HlB=function(q,a,w,G,k){q.W.stop();
if(!q.Y){var b=g.gh(a);q.V||(a.style.width=g.ih(b.width,!0),w.style.width=g.ih(b.width,!0));g.IR(G,"top",b.height-Math.max(Math.min(b.height,k)/2+10,20)+"px");g.IR(G,"right","1px");q.Y=!0;g.aT(a,!0);q.D=new g.o1(function(){g.gU(this.cq(),"iv-branding-active")},0,q);
q.D.start()}},f$y=function(q,a,w){g.wU(q.cq(),"iv-branding-active");
q.L=new g.o1(function(){g.aT(a,!1);q.V||(w.style.width=g.ih(0,!0))},250);
q.L.start();q.Y=!1},p$K=function(q,a,w,G,k,b,O){this.V=q;
this.W=a;this.V7=w;this.videoData=G;this.logger=k;this.j=b;this.U=O},Uu8=function(q,a,w){b8.call(this,q,a,w);
var G=this;this.S=this.isCollapsed=this.J=!1;this.L=5E3;this.U=this.W=this.V=this.Y=null;this.X=this.createElement({G:"div",vT:["iv-promo-contents"]});this.D=new g.o1(function(){G.V.setAttribute("aria-hidden","true");g.aT(G.W,!1);g.aT(G.U,!0)},700,this);
g.p(this,this.D)},jjV=function(q){var a=q.annotation.data;
if(q.annotation.style==="cta")var w=6;else if(q.annotation.style==="video"||q.annotation.style==="playlist")w=7;q.L=a.collapsedelay_ms||q.L;var G=["iv-promo","iv-promo-inactive"];q.cq().setAttribute("aria-hidden","true");q.cq().setAttribute("aria-label","Promotion");q.cq().tabIndex=0;var k=q.annotation.Do(),b=a.image_url;if(b){var O=q.createElement({G:"div",vT:["iv-promo-img","iv-click-target"]});b=q.createElement({G:"img",Z:{src:b,"aria-hidden":"true"}});O.appendChild(b);a.video_duration&&!a.is_live?
(b=q.createElement({G:"span",N:"iv-promo-video-duration",ue:a.video_duration}),O.appendChild(b)):a.playlist_length&&(b=q.createElement({G:"span",N:"iv-promo-playlist-length",ue:a.playlist_length.toString()}),O.appendChild(b));k&&DY(q,O,k,q.annotation.id,a.session_data,void 0,w)}k?(b=q.createElement({G:"a",N:"iv-promo-txt"}),g.NO(b,uK(k)),q.V=b):q.V=q.createElement({G:"div",N:"iv-promo-txt"});switch(q.annotation.style){case "cta":case "website":var e=q.createElement({G:"p",K:[{G:"strong",ue:a.text_line_1}]});
var N=q.createElement({G:"p",K:[{G:"span",N:"iv-promo-link",ue:a.text_line_2}]});if(b=a.text_line_3){G.push("iv-promo-website-card-cta-redesign");var Y=q.createElement({G:"button",vT:["iv-promo-round-expand-icon","ytp-button"]});b=q.createElement({G:"button",vT:["iv-button","iv-promo-button"],K:[{G:"span",N:"iv-button-content",ue:b}]});var P=q.createElement({G:"div",N:"iv-promo-button-container"});P.appendChild(b);k&&DY(q,q.cq(),k,q.annotation.id,a.session_data,void 0,w)}g.gU(q.V,"iv-click-target");
k&&DY(q,q.V,k,q.annotation.id,a.session_data,void 0,w);break;case "playlist":case "video":e=q.createElement({G:"p",K:[{G:"span",ue:a.text_line_1}]}),N=q.createElement({G:"p",K:[{G:"strong",ue:a.text_line_2}]}),a.is_live&&(e=N,N=q.createElement({G:"span",vT:["yt-badge","iv-promo-badge-live"],ue:"LIVE NOW"})),g.gU(q.V,"iv-click-target"),k&&DY(q,q.V,k,q.annotation.id,a.session_data,void 0,w),G.push("iv-promo-video")}e&&q.V.appendChild(e);N&&q.V.appendChild(N);q.X.appendChild(q.V);P&&q.X.appendChild(P);
w=q.createElement({G:"div",N:"iv-promo-actions"});q.U=q.createElement({G:"button",vT:["iv-promo-expand","ytp-button"]});q.U.title="Expand";q.context.V.listen(q.U,"click",function(K){X$c(q,5E3,K)});
w.appendChild(q.U);g.aT(q.U,!1);q.context.V.listen(q.cq(),"mouseover",q.zz,q);q.context.V.listen(q.cq(),"mouseout",q.A_,q);q.context.V.listen(q.cq(),"touchend",function(K){X$c(q,5E3,K)});
q.W=q.createElement({G:"button",vT:["iv-promo-close","ytp-button"]});q.W.title="Close";q.context.V.listen(q.W,"click",q.annotation.style==="cta"&&a.text_line_3?q.h_:q.bQ,q);w.appendChild(q.W);g.ah(q.cq(),G);O&&(g.$A(q.cq(),O),Y&&O.appendChild(Y));g.$A(q.cq(),q.X);g.$A(q.cq(),w)},X$c=function(q,a,w){w.stopPropagation();
oNe(q);I$6(q,a);q.V.focus()},uJy=function(q){q.isCollapsed||q.S||q.Y||(g.gU(q.cq(),"iv-promo-collapsed"),q.isCollapsed=!0,q.D.start())},oNe=function(q){q.D.stop();
q.isCollapsed&&(g.GM(q.cq(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),q.isCollapsed=!1,q.V&&q.V.removeAttribute("aria-hidden"),g.aT(q.U,!1),g.aT(q.W,!0))},I$6=function(q,a){q.Y||(q.Y=g.HO(function(){t88(this);
uJy(this)},a,q))},t88=function(q){q.Y&&(g.yV.clearTimeout(q.Y),q.Y=null)},vNw=function(q){this.j=q},muB=function(q,a,w){a&&(w?l8(q,a.map(function(G){return g.AD(G,w)})):l8(q,a))},l8=function(q,a,w,G){var k=1,b=void 0,O=-1;
if(w){var e=!1;b=function(){k--;k||e||(clearTimeout(O),e=!0,w())};
O=setTimeout(function(){e=!0;w()},1E3)}a=g.V(a||[]);
for(var N=a.next();!N.done;N=a.next())N=N.value,k++,g.re(N,b);G&&(k++,G!==0&&q.j.sendVideoStatsEngageEvent(G,b))},zvc=function(q){g.md.call(this,q);
var a=this;this.F9=this.S=!1;this.loadNumber=0;this.L={};this.logger=new vNw(this.player);this.Y=new g.Ee(this);this.D=this.X=null;this.events=new g.Ee(this);this.PH=this.J=this.V=null;this.UK=[];g.p(this,this.Y);this.Y.C(this.player,"onVideoAreaChange",function(){a.publish("onVideoAreaChange")});
this.Y.C(this.player,"onHideControls",function(){a.publish("onHideControls")});
this.Y.C(this.player,"onShowControls",function(){a.publish("onShowControls")});
this.Y.C(this.player,"resize",function(G){a.publish("resize",G)});
this.Y.C(this.player,"presentingplayerstatechange",function(G){a.publish("presentingplayerstatechange",G)});
this.subscribe("presentingplayerstatechange",this.Di,this);this.subscribe("resize",this.A9,this);this.player.B().L7.subscribe("vast_info_card_add",this.wV,this);g.p(this,this.events);this.y7=this.createElement({G:"div",N:"video-custom-annotations"});this.U=new g.u({G:"div",vT:["ytp-player-content","ytp-iv-player-content"]});g.p(this,this.U);g.DZ(this.player,this.U.element,4);this.U.hide();this.W=new g.u({G:"div",vT:["ytp-iv-video-content"]});g.p(this,this.W);q=this.createElement({G:"div",N:"video-annotations"});
q.appendChild(this.y7);this.W.element.appendChild(q);this.zR()&&this.load();var w=this.createElement({G:"style"});(g.kA("HEAD")[0]||document.body).appendChild(w);this.addOnDisposeCallback(function(){g.Cn(w)});
if(q=w.sheet)q.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),q.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),q.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),q.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),q.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),q.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),q.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),q.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),q.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),q.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ill=function(q){q=q.createElement({G:"div",
vT:["annotation","annotation-type-custom"]});g.aT(q,!1);return q},WAJ=function(q,a){a=!a.isCued()&&!g.v(a,1024);
q.U.Ji(a);q.W.Ji(a)},Du8=function(q,a,w){q.S=!0;
q.D=g.Cy(a,w)},RvR=function(q,a){for(var w={},G=g.V(a.attributes),k=G.next();!k.done;k=G.next())k=k.value,w[k.name]=k.nodeValue;
for(G=0;G<a.childNodes.length;G++)if(k=a.childNodes[G],g.bV(k)&&k.nodeType==1){if(w[k.tagName])var b=w[k.tagName];else if(k.tagName==="data"){k.childNodes.length>0&&(b=k.childNodes[0].nodeValue,w[k.tagName]=typeof b==="string"?b.trim():b);continue}else b=[],w[k.tagName]=b;k&&k.tagName==="TEXT"?k.childNodes.length===1&&k.childNodes[0].nodeType===3?b.push(k.childNodes[0].nodeValue):b.push(""):k&&b.push(RvR(q,k))}return w},aBU=function(q){var a=q.player.getVideoData();
if(a.Tl){var w=q.player.B().L7.get(a.videoId);if(w){var G={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(k,b,O){k=q.loadNumber;b=a.videoId;q.loaded&&q.loadNumber===k&&q.player.getVideoData().videoId===b&&(O=g.lO(O)&&O.responseXML?O.responseXML:null)&&yY7(q,O)}};
g.zV()&&(G.onFinish=qK6(q,G.onFinish));G.postParams={ic_only:"1"};g6K(G,w);q.S=!0;g.Cy(a.Tl,G)}}},g6K=function(q,a){q.method="POST";
q.postParams=q.postParams||{};a.dH&&(q.postParams.ic_coll=a.dH);a.fY&&(q.postParams.ic_xml=a.fY);a.z3&&(q.postParams.ic_track=a.z3)},wI7=function(q){var a=new g.u({G:"div"});
g.aT(a.element,!1);var w=new CQB(q.player,a.element,ea(q));g.p(w,a);a.HT(q.U.element);w.y6();return w},kNx=function(q,a){var w,G;
if(a=(w=a.getWatchNextResponse())==null?void 0:(G=w.cards)==null?void 0:G.cardCollectionRenderer)q.F9=!0,GN8(q,a),a.headerText&&q.PH&&(w=g.OE(a.headerText),q.player.T("player_tooltip_data_title_killswitch")?q.PH.setAttribute("title",w):q.PH.setAttribute("data-tooltip-title",w))},ea=function(q){if(!q.J){var a=new U0R(q);
g.p(q,a);var w=new g.d_(q);g.p(q,w);q.J=new p$K(a,w,q.player.B(),q.player.getVideoData(),q.logger,q.player,q.ym)}return q.J},yY7=function(q,a){var w=!1,G=a.getElementsByTagName("annotations");
if(G&&!(G.length<1)&&(G=G[0].getAttribute("itct"))){var k=g.$f();if(k){var b=g.TX();b&&g.tK(g.HC)(void 0,k,b,[g.KF(G)])}}a=a.getElementsByTagName("annotation");for(G=0;G<a.length;G++){b=RvR(q,a[G]);k=null;try{if(b){var O=b.id,e=/.+/;var N=typeof O==="string"&&e!=null&&O!=null&&O.match(e)?O:"";var Y=IC(b.type,bbR),P=IC(b.style,Ob7),K=a$e(b.data),d=K.length!==0?JSON.parse(K):{};var T=b.action;b=l$K;if(T==null)var F=null;else if(g.kc(T)){e=[];for(var J=g.V(T),Q=J.next();!Q.done;Q=J.next()){var B=b(Q.value);
B&&e.push(B)}F=e}else{var L=b(T);F=L?[L]:[]}k=N&&Y?new evw(N,Y,P,F,d):null}else k=null}catch(Oj){}if(k)if(k.type==="branding"||k.type==="promotion"){b=q;e=k;var M=ill(b),H=null;switch(e.type){case "branding":if(b.player.B().C0)break;b.player.T("web_player_overlay_positioned_layout")?(M.setAttribute("data-overlay-order","11"),b.player.kL(M,4,!0)):b.U.element.appendChild(M);H=new Ov(M,ea(b),e);break;case "promotion":g.DZ(b.player,M,4),H=new Uu8(M,ea(b),e)}H&&H.y6();if(b=H)g.p(q,b),q.L[k.id]=b}else if(k.type===
"card"||k.type==="drawer"){q.V||(q.V=wI7(q),g.p(q,q.V));if(k.type==="card"){M=q.V;var X=(w=k)&&w.data&&w.data.card_type;k=w.data;if(X)switch(b=k.tracking||{},b={RR:b.impression,click:b.click,close:b.close,E0:b.teaser_impression,p9:b.teaser_click},e=k.tracking_params||{},H=null,X){case "collaborator":w={id:w.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||
!1,dT:b,Xx:e.card?g.KF(e.card):null,Sc:e.teaser?g.KF(e.teaser):null,So:e.icon?g.KF(e.icon):null,channelId:k.channel_id,customMessage:k.custom_message?k.custom_message:null,profileImageUrl:k.image_url,title:k.title,metaInfo:k.meta_info,url:ti({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};aD(M,w);break;case "playlist":w={id:w.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,
autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,dT:b,Xx:e.card?g.KF(e.card):null,Sc:e.teaser?g.KF(e.teaser):null,So:e.icon?g.KF(e.icon):null,X4:k.image_url,playlistVideoCount:k.playlist_video_count,customMessage:k.custom_message?k.custom_message:null,title:k.title,metaInfo:k.meta_info,url:ti({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};aD(M,w);break;case "productListing":k.signin_url&&(H=ti({target:"current",
value:k.signin_url}));X=[];for(var D=k.offers||[],z=0;z<D.length;z++)X.push(new Tbe(g.nS(D[z].merchant),g.nS(D[z].price)));w={id:w.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,dT:b,Xx:e.card?g.KF(e.card):null,Sc:e.teaser?g.KF(e.teaser):null,So:e.icon?g.KF(e.icon):null,imageUrl:k.image_url,displayDomain:k.display_domain?k.display_domain:
null,showLinkIcon:!!k.show_link_icon,Es:k.button_icon_url?k.button_icon_url:null,title:k.title,customMessage:k.custom_message?k.custom_message:null,url:ti({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),EVl:H,taW:k.signin_title?k.signin_title:void 0,p3G:k.signin_message?k.signin_message:void 0,offers:X,onClickCommand:null};aD(M,w);break;case "simple":w={id:w.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,
startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,dT:b,Xx:e.card?g.KF(e.card):null,Sc:e.teaser?g.KF(e.teaser):null,So:e.icon?g.KF(e.icon):null,imageUrl:k.image_url,displayDomain:k.display_domain?k.display_domain:null,showLinkIcon:!!k.show_link_icon,Es:k.button_icon_url?k.button_icon_url:null,title:k.title,customMessage:k.custom_message?k.custom_message:null,url:ti({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};
aD(M,w);break;case "video":w={id:w.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,dT:b,Xx:e.card?g.KF(e.card):null,Sc:e.teaser?g.KF(e.teaser):null,So:e.icon?g.KF(e.icon):null,X4:k.image_url,videoDuration:k.video_duration||null,customMessage:k.custom_message?k.custom_message:null,title:k.title,metaInfo:k.meta_info,isLiveNow:!!k.is_live_now,
url:ti({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null},aD(M,w)}}else Zll(q.V,k);w=!0}}w&&(Lv(q.player),q.A9())},GN8=function(q,a){var w=!1;
q.V||(q.V=wI7(q),g.p(q,q.V));for(var G=g.V(a.cards||[]),k=G.next();!k.done;k=G.next())k=k.value,k.cardRenderer&&(ENV(q.V,k.cardRenderer),w=!0);if(w){var b;(b=q.player.getVideoData())!=null&&g.g6(b)||(w=q.V,G=a.headerText?g.OE(a.headerText):"",g.EN(w.OA,G),w.D&&(w.j.T("player_tooltip_data_title_killswitch")?w.D.setAttribute("title",G):w.D.setAttribute("data-tooltip-title",G)),w.context.videoData.eventId&&(w.eventId=w.context.videoData.eventId),w.f7=a.trackingParams?g.KF(a.trackingParams):null,w.S=
a.closeButton.infoCardIconRenderer.trackingParams?g.KF(a.closeButton.infoCardIconRenderer.trackingParams):null,w.So=a.icon.infoCardIconRenderer.trackingParams?g.KF(a.icon.infoCardIconRenderer.trackingParams):null,q.A9());Lv(q.player)}},lBy=function(q,a,w,G,k){if(!q.player.B().C0){var b=[];
a.navigationEndpoint&&g.I(a.navigationEndpoint,g.zO)&&g.I(a.navigationEndpoint,g.zO).browseId&&b.push(new kUl("openUrl","click",new w$J("/channel/"+g.I(a.navigationEndpoint,g.zO).browseId,"new",!0,!0)));var O=a.watermark.thumbnails[0];G={channel_name:a.channelName,end_ms:a.endTimeMs,image_height:O.height,image_type:1,image_url:O.url,image_width:O.width,is_mobile:!1,session_data:{annotation_id:w,ei:k,feature:"iv",itct:a.trackingParams,src_vid:G},start_ms:a.startTimeMs};if(a.subscribeButton&&g.I(a.subscribeButton,
g.iN)){G.channel_id=g.I(a.subscribeButton,g.iN).channelId;var e;a=g.I(a.subscribeButton,g.iN);O=k=null;a.subscribed?(a.subscriberCountWithUnsubscribeText&&(k=g.OE(a.subscriberCountWithUnsubscribeText)),a.subscriberCountText&&(O=g.OE(a.subscriberCountText))):(a.subscriberCountText&&(k=g.OE(a.subscriberCountText)),a.subscriberCountWithSubscribeText&&(O=g.OE(a.subscriberCountWithSubscribeText)));var N,Y=((N=g.I((e=a.signInEndpoint)==null?void 0:e.commandMetadata,g.Zk))==null?void 0:N.url)||"";e={subscribeText:g.OE(a.unsubscribedButtonText),
subscribeCount:k||"",unsubscribeText:g.OE(a.subscribedButtonText),unsubscribeCount:O||"",enabled:a.enabled||!1,classic:!1,subscribed:a.subscribed||!1,feature:"iv",signInUrl:Y};G.standalone_subscribe_button_data=e}b=new evw(w,"branding","branding",b,G);e=ill(q);q.player.T("web_player_overlay_positioned_layout")?(e.setAttribute("data-overlay-order","11"),q.player.kL(e,4,!0)):q.U.element.appendChild(e);b=new Ov(e,ea(q),b);b.y6();g.p(b,b);q.L[w]=b}},qK6=function(q,a){return function(){var w=g.XU.apply(0,
arguments);
q.t2()||q.UK.push(g.fJ.gh(function(){a.apply(null,g.Tf(w))}))}},er7=function(q){return q==="annotation-editor"||q==="live-dashboard"};
g.o$.prototype.v_=g.kl(39,function(q,a){var w=g.H1(this.Hq());w&&w.v_(q,a)});
var rG={},nv=null;g.TJ(hi,g.b9);g.C=hi.prototype;g.C.getDuration=function(){return this.duration};
g.C.play=function(q){if(q||this.V==0)this.progress=0,this.coords=this.U;else if(this.isPlaying())return!1;My(this);this.startTime=q=g.Kw();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Y=this.startTime;this.progress||this.nX();this.Ld("play");this.isPaused()&&this.Ld("resume");this.V=1;var a=g.lV(this);a in rG||(rG[a]=this);Mn8();hiy(this,q);return!0};
g.C.stop=function(q){My(this);this.V=0;q&&(this.progress=1);SzI(this,this.progress);this.onStop();this.Km()};
g.C.pause=function(){this.isPlaying()&&(My(this),this.V=-1,this.Ld("pause"))};
g.C.qB=function(){this.V==0||this.stop(!1);this.Ld("destroy");hi.mG.qB.call(this)};
g.C.destroy=function(){this.dispose()};
g.C.JN=function(){this.Ld("animate")};
g.C.Ld=function(q){this.dispatchEvent(new fLI(q,this))};
g.TJ(fLI,g.t1);g.TJ(Sh,hi);Sh.prototype.W=function(){};
Sh.prototype.JN=function(){this.W();Sh.mG.JN.call(this)};
Sh.prototype.Km=function(){this.W();Sh.mG.Km.call(this)};
Sh.prototype.nX=function(){this.W();Sh.mG.nX.call(this)};
g.TJ(Hi6,Sh);Hi6.prototype.W=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.Z(U0R,g.c);g.C=U0R.prototype;g.C.listen=function(q,a,w,G){w=(0,g.Ne)(w,G||this.U);q=g.$t(q,a,w);this.V.push(q);return q};
g.C.HU=function(q,a,w,G){w=(0,g.Ne)(w,G||this.U);q=rn6(q,a,w);this.V.push(q);return q};
g.C.v5=function(q){g.sH(q);g.mU(this.V,q)};
g.C.removeAll=function(){g.sH(this.V);this.V.length=0};
g.C.qB=function(){this.removeAll();g.c.prototype.qB.call(this)};g.Z(o0l,g.md);g.C=o0l.prototype;g.C.load=function(){g.md.prototype.load.call(this);if(!cx(this)){var q=g.t9U(this.player.getVideoData());q?(q=jLx(q,ILe(this)),pv(this,q,!1)):uix(this)}};
g.C.unload=function(){pv(this,null);this.Y&&(this.Y.abort(),this.Y=null);g.md.prototype.unload.call(this)};
g.C.KW=function(q,a){return cx(this)?q==="loadCustomEndscreenRenderer"?(q=jLx(a,"new"),pv(this,q),!0):null:null};
g.C.getOptions=function(){return cx(this)?["loadCustomEndscreenRenderer"]:[]};
g.C.sA=function(){if(this.endscreen&&this.endscreen.elements){var q=this.player.getVideoContentRect();if(q&&q.width!==0&&q.height!==0){var a=this.player.getPlayerSize();if(a&&a.width!==0&&a.height!==0){var w=q.width/q.height;var G=0;for(var k=-1,b=0;b<NxV.length;b++){var O=Math.abs(a.width-NxV[b]);if(k===-1||G>=O)k=b,G=O}G=YKx[k];this.W&&g.IR(this.W.element,"outline-width",Math.max(a.width,a.height)+"px");for(a=0;a<this.endscreen.elements.length;++a)if(b=this.endscreen.elements[a].id,k=this.U[b],
O=this.L[b],k&&O){var e=O.width*w/O.aspectRatio,N=Math.round(O.width*q.width);b=Math.round(e*q.height);var Y=q.left+Math.round(O.left*q.width),P=q.top+Math.round(O.top*q.height);g.qz(k.element,N,b);g.Wa(k.element,Y,P);g.GM(k.element,P2w);N>256||b>256?g.gU(k.element,"ytp-ce-large-round"):N>96||b>96?g.gU(k.element,"ytp-ce-medium-round"):g.gU(k.element,"ytp-ce-small-round");g.GM(k.element,K1K);N=O.left+O.width/2;O=O.top+e/2;g.gU(k.element,N<=.5&&O<=.5?"ytp-ce-top-left-quad":N>.5&&O<=.5?"ytp-ce-top-right-quad":
N<=.5&&O>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.GM(k.element,YKx);g.gU(k.element,G);(k=g.ON(document,"div","ytp-ce-expanding-overlay-body",k.element)[0])&&g.IR(k,"height",b+"px")}}}}};
g.C.onCueRangeEnter=function(q){if(this.endscreen)if(q.getId()==="ytp-ce-in-endscreen")oC(this,this.endscreen.impressionUrls),(q=g.$f())&&this.endscreen.visualElement&&g.tW(q,this.endscreen.visualElement),this.V&&(g.gU(this.V,"ytp-ce-element-show"),this.V.removeAttribute("aria-hidden"),this.player.aO()?g.gU(this.V,"ytp-ce-hide-button-lower"):g.wU(this.V,"ytp-ce-hide-button-lower"));else{q=q.getId().substring(15);var a=this.U[q],w=this.L[q];g.gU(a.element,"ytp-ce-element-show");a.element.removeAttribute("aria-hidden");
a=this.player.getRootNode();g.gU(a,"ytp-ce-shown");oC(this,w.impressionUrls);(a=g.$f())&&g.tW(a,w.visualElement);this.player.B().S&&this.player.zl("endscreenelementshown",q)}};
g.C.onCueRangeExit=function(q){if(q.getId()==="ytp-ce-in-endscreen")this.V&&(g.wU(this.V,"ytp-ce-element-show"),this.V.setAttribute("aria-hidden","true"));else{q=q.getId().substring(15);var a=this.U[q];g.wU(a.element,"ytp-ce-element-show");a.element.setAttribute("aria-hidden","true");a=this.player.getRootNode();g.wU(a,"ytp-ce-shown");this.player.B().S&&this.player.zl("endscreenelementhidden",q)}};
g.C.M4Q=function(q){var a=this;q.target===window&&(new g.o1(function(){for(var w=g.V(Object.values(a.U)),G=w.next();!G.done;G=w.next())g.GM(G.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.C.Ji=function(q){for(var a=g.V(Object.values(this.U)),w=a.next();!w.done;w=a.next())w=w.value,q?w.element.setAttribute("hidden",""):w.element.removeAttribute("hidden")};
g.C.VZ2=function(q){this.V&&this.player.getRootNode().removeChild(this.V);q&&(g.gU(q,"ytp-ce-hide-button-container"),this.V=q,g.DZ(this.player,this.V,4))};
var NxV=[346,426,470,506,570,640,853,1280,1920],YKx="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),K1K=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],P2w=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var GU7={j_t:"current",sgK:"new"};var blR={CLOSE:"close",am8:"openUrl",SUBSCRIBE:"subscribe"},OlI={JLK:"click",CLOSE:"close",Rl2:"hidden",SoQ:"rollOut",AZT:"rollOver",dZh:"shown"};evw.prototype.Do=function(){var q=NbJ(this,function(a){return a.type==="openUrl"&&a.url!=null});
return q?q.url:null};
var Ob7={dM7:"anchored",s2:"branding",CHANNEL:"channel",fw7:"cta",L72:"highlightText",WnK:"label",PLAYLIST:"playlist",POPUP:"popup",YMe:"speech",SUBSCRIBE:"subscribe",t_9:"title",VIDEO:"video",WX9:"website"},bbR={s2:"branding",xMt:"card",XQe:"drawer",vE9:"highlight",EKW:"marker",DQG:"promotion",TEXT:"text",hv8:"widget"};g.Z(Wx,g.c);g.C=Wx.prototype;g.C.addCueRange=function(q,a,w,G,k){q=new g.Xo(q,a,{id:w,namespace:"annotations_module"});G&&this.St.set(q,G);k&&this.A2.set(q,k);this.context.j.N9([q],1)};
g.C.y6=function(){this.context.U.subscribe("resize",this.JC,this)};
g.C.cq=function(){return this.element};
g.C.rb=function(q,a,w,G,k,b){if(this.IW)return!1;b&&(b.stopPropagation(),b.preventDefault());this.navigate(q,w,G,k);return!1};
g.C.show=function(){};
g.C.hide=function(){};
g.C.destroy=function(){g.Cn(this.cq())};
g.C.JC=function(){};
g.C.navigate=function(q,a,w,G){var k=this,b=uK(q);if(b){var O=sjU(b,q.target),e=function(){q.V&&k.context.j.pauseVideo();var N=k.context.videoData.J8||!1,Y=g.RI(b||"");N&&Y&&(Y.v||Y.list)?k.context.j.Fj(Y.v,a,Y.list,!1):g.HA(b||"",O==="current"?"_top":void 0,a)};
O==="new"&&(e(),e=null);l8(this.context.logger,w,e,G);$u8(b)||(w=g.$f(),G=a.itct,w&&G&&g.id(w,g.KF(G)))}};
g.C.qB=function(){this.St.clear();this.A2.clear();g.c.prototype.qB.call(this)};
g.C.createElement=function(q){q=new g.u(q);g.p(this,q);return q.element};g.Z(CQB,Wx);g.C=CQB.prototype;g.C.jR=function(){this.UK&&aD(this,this.UK)};
g.C.isAvailable=function(){var q;if(q=!!this.cards.length)(q=this.j.getRootNode())?(q=g.gh(q),q=173<q.width&&173<q.height):q=!1;return q};
g.C.JC=function(){var q=this.isAvailable();g.aT(this.cq(),q);g.kX(this.context.j.getRootNode(),g.El.IV_DRAWER_ENABLED,q);Lv(this.j)};
g.C.destroy=function(){this.j.v_(!1);try{this.j.getRootNode().removeChild(this.Y)}catch(q){}g.W0(this.F9);g.JE(this.Tl);this.le&&this.le.dispose();this.L&&this.L.dispose();Wx.prototype.destroy.call(this)};
g.C.bP=function(){var q=this;this.context.V.listen(g.lh("iv-drawer-close-button",this.Y),"click",this.Pp,this);this.context.V.listen(this.U,"touchend",function(){q.jt.start()});
this.context.V.listen(this.U,"scroll",this.QZ,this);this.context.U.subscribe("onHideControls",function(){q.L7=!0});
this.context.U.subscribe("onShowControls",function(){q.L7=!1});
this.context.U.subscribe("onVideoAreaChange",function(){q.L7=g.qG(q.j.getRootNode(),"ytp-autohide")});
this.F9.push(g.i$("iv-button-shown",this.O7h,this));this.F9.push(g.i$("iv-button-hidden",this.dB9,this));AYV(this)};
g.C.findLastIndex=function(q){if(this.cards.length===0)return 0;var a=g.E6(this.cards,function(w){return q.ly.startMs>w.ly.startMs||q.ly.startMs===w.ly.startMs&&q.ly.timestamp>=w.ly.timestamp?!0:!1});
return a===-1?0:a+1};
g.C.Pp=function(){if(this.W){l8(this.context.logger,kS(this).dT.close);var q=g.$f();q&&this.S&&g.id(q,this.S);q1(this)}};
g.C.QZ=function(){g.kX(this.Y,"iv-drawer-scrolled",this.U.scrollTop>0)};
g.C.O7h=function(){var q=g.$f(),a=kS(this);a=a?a.So:this.So;q&&a&&g.vC(q,[a])};
g.C.dB9=function(){var q=g.$f(),a=kS(this);a=a?a.So:this.So;q&&a&&g.zX(q,[a])};
g.C.L8=function(){var q=kS(this);l8(this.context.logger,q.dT.E0);var a=g.$f();if(a&&q)if(this.j.T("web_infocards_teaser_show_logging_fix")){var w=[];q.Sc&&w.push(q.Sc);q.So&&w.push(q.So);w.length>0&&g.vC(a,w)}else g.vC(a,[q.Sc,q.So])};
g.C.u9t=function(){var q=g.$f(),a=kS(this);q&&a&&g.zX(q,[a.Sc])};
g.C.RU=function(q){var a=kS(this),w=g.$f();this.V?q?(q=this.context.logger,l8(q,a.dT.p9),q.j.sendVideoStatsEngageEvent(4,void 0),w&&a.Sc&&g.id(w,a.Sc)):(q=this.context.logger,l8(q,a.dT.p9),q.j.sendVideoStatsEngageEvent(4,void 0),w&&a.So&&g.id(w,a.So)):(q=this.context.logger,l8(q,a.dT.p9),q.j.sendVideoStatsEngageEvent(4,void 0),w&&this.So&&g.id(w,this.So))};g.Z(b8,Wx);b8.prototype.y6=function(){Wx.prototype.y6.call(this);hvy(this)};
b8.prototype.show=function(){Wx.prototype.show.call(this);var q=g.$f(),a=this.annotation.data;q&&a&&(a=a.session_data)&&g.vC(q,[g.KF(a.itct)])};
b8.prototype.hide=function(){Wx.prototype.hide.call(this);var q=g.$f(),a=this.annotation.data;q&&a&&(a=a.session_data)&&g.zX(q,[g.KF(a.itct)])};g.Z(Ov,b8);
Ov.prototype.show=function(){if(!this.isActive){b8.prototype.show.call(this);if(!this.X){g.gU(this.cq(),"iv-branding");var q=this.annotation.data;this.U=this.createElement({G:"img",vT:["branding-img","iv-click-target"],Z:{"aria-label":"Channel watermark",src:q.image_url,width:q.image_width,height:q.image_height}});g.aT(this.U,!1);var a=this.createElement({G:"button",vT:["branding-img-container","ytp-button"]});a.appendChild(this.U);this.cq().appendChild(a);var w=this.annotation.Do();w&&DY(this,a,
w,this.annotation.id,q.session_data);this.context.j.T("disable_branding_context")||cYe(this,q);this.X=!0}g.aT(this.cq(),!0);this.isActive=!0;if(this.U){try{Sgc(this,this.U)}catch(G){}g.gU(this.context.j.getRootNode(),"ytp-branding-shown");this.context.j.getRootNode().style.setProperty("--branding-image-width",this.U.getAttribute("width")+"px")}}};
Ov.prototype.hide=function(){this.isActive&&(b8.prototype.hide.call(this),g.aT(this.cq(),!1),this.isActive=!1,g.wU(this.context.j.getRootNode(),"ytp-branding-shown"))};
Ov.prototype.destroy=function(){this.V&&(this.V.dispose(),this.V=null);g.wU(this.context.j.getRootNode(),"ytp-branding-shown");b8.prototype.destroy.call(this)};g.Z(Uu8,b8);g.C=Uu8.prototype;g.C.show=function(){this.isActive||(b8.prototype.show.call(this),this.J||(jjV(this),this.J=!0),g.aT(this.cq(),!0),g.HO(function(){g.wU(this.cq(),"iv-promo-inactive")},100,this),this.cq().removeAttribute("aria-hidden"),this.isActive=!0,t88(this),oNe(this),I$6(this,this.L))};
g.C.hide=function(){this.isActive&&(g.gU(this.cq(),"iv-promo-inactive"),this.isActive=!1,this.cq().setAttribute("aria-hidden","true"))};
g.C.rb=function(q,a,w,G,k,b){return this.isCollapsed?!1:b8.prototype.rb.call(this,q,a,w,G,k,b)};
g.C.zz=function(q){this.S=!0;X$c(this,500,q)};
g.C.A_=function(){this.S=!1;uJy(this)};
g.C.bQ=function(q){q.stopPropagation();this.hide()};
g.C.h_=function(q){q.stopPropagation();t88(this);this.isCollapsed=!0;g.gU(this.cq(),"iv-promo-collapsed-no-delay");this.D.start()};
g.C.destroy=function(){this.D.dispose();b8.prototype.destroy.call(this)};g.Z(zvc,g.md);g.C=zvc.prototype;g.C.KW=function(q,a){if(!er7(this.player.B().playerStyle))return null;switch(q){case "loadCustomAnnotationsXml":return(q=g.i7(a))&&yY7(this,q),!0;case "removeCustomAnnotationById":return a&&this.V&&(JYJ(this.V,a),Lv(this.player)),!0}return null};
g.C.getOptions=function(){return er7(this.player.B().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.C.zR=function(){var q=this.player.B(),a=this.player.getVideoData(),w=q.annotationsLoadPolicy||a.annotationsLoadPolicy;return a.J8||this.player.isMutedByEmbedsMutedAutoplay()?!1:w===1&&!a.Bw||q.L7.get(a.videoId)||g.a$(a)||g.w6(a)?!0:!1};
g.C.A9=function(){if(this.W){var q=this.player.mQ().getVideoContentRect(!0);g.qz(this.W.element,q.width,q.height);g.Wa(this.W.element,q.left,q.top)}if(this.V){var a=this.player.f3();q=this.V;a=a.width;g.kX(q.Y,"iv-drawer-small",a<=426);g.kX(q.Y,"iv-drawer-big",a>=1280)}};
g.C.Di=function(q){WAJ(this,q.state);g.v(q.state,2)&&(this.aO()&&this.Ew()&&this.player.getPresentingPlayerType()!==2&&this.LZ(!1),this.v_(!1))};
g.C.load=function(){function q(O){var e=a.loadNumber;a.D=null;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===G&&(O=g.lO(O)&&O.responseXML?O.responseXML:null)&&(yY7(a,O),g.gU(a.player.getRootNode(),"iv-module-loaded"))}
var a=this;g.md.prototype.load.call(this);WAJ(this,this.player.getPlayerStateObject());this.loadNumber++;var w=this.player.getVideoData(),G=w.videoId;g.zV()&&(q=qK6(this,q));var k={format:"XML",onFinish:q,onError:function(){a.D=null},
urlParams:{}};w.isPharma&&(k.urlParams.pharma="1");k.method="POST";k.withCredentials=!0;var b=this.player.B().L7.get(G);b&&g6K(k,b);b=b&&(b.fY||b.dH);if(!w.VO||b)w.Tl?Du8(this,w.Tl,k):(this.X=function(){if(!a.S)a.onVideoDataChange(k);var O=a.player.getVideoData();(O==null?0:g.g6(O))&&!a.F9&&kNx(a,O)},this.player.addEventListener("videodatachange",this.X));
g.DZ(this.player,this.W.element,4);this.A9();(b=g.a$(w))&&GN8(this,b);(b=g.w6(w))&&b.featuredChannel&&lBy(this,b.featuredChannel,b.annotationId||"branding",w.videoId||null,w.eventId||null);this.PH=g.lh("ytp-cards-button",this.player.getRootNode());g.g6(w)&&kNx(this,w)};
g.C.onVideoDataChange=function(q){var a=this.player.getVideoData();a.Tl&&Du8(this,a.Tl,q)};
g.C.unload=function(){this.player.XC("annotations_module");for(var q=g.V(Object.keys(this.L)),a=q.next();!a.done;a=q.next())this.L[a.value].destroy();this.J=null;this.V&&(this.V.destroy(),this.V=null,Lv(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.F9=!1;this.L={};this.U.hide();g.md.prototype.unload.call(this);this.W.detach();this.X&&(this.player.removeEventListener("videodatachange",this.X),this.X=null)};
g.C.wV=function(q){q===this.player.getVideoData().videoId&&(this.loaded?aBU(this):this.load())};
g.C.aO=function(){var q;return((q=this.V)==null?void 0:q.isAvailable())||this.F9};
g.C.Ew=function(){return!!this.V&&this.V.W};
g.C.LZ=function(q,a,w){a=a===void 0?!1:a;this.aO();this.V&&(q?w?yA(this.V,w,a):yA(this.V,"YOUTUBE_DRAWER_AUTO_OPEN",a):q1(this.V))};
g.C.v_=function(q,a){this.player.publish(q?"cardsteasershow":"cardsteaserhide",a)};
g.C.qB=function(){this.player.B().L7.unsubscribe("vast_info_card_add",this.wV,this);g.wU(this.player.getRootNode(),g.El.IV_DRAWER_OPEN);for(var q=this.UK,a=g.fJ,w=0,G=q.length;w<G;w++)a.FS(q[w]);this.UK.length=0;g.md.prototype.qB.call(this)};
g.C.createElement=function(q){q=new g.u(q);g.p(this,q);return q.element};g.Jq("annotations_module",zvc);g.Jq("creatorendscreen",o0l);})(_yt_player);
