(function(g){var window=this;'use strict';var $MJ=function(q,a,w){g.h(function(G){q.V=g.Cy(a,w);g.Jm(G)})},N1=function(q){q.isActive()||q.start()},sby=function(q,a){return a?q.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},F16=function(q){return g.Zg(q)||q.T("web_enable_caption_language_preference_stickiness")},C27=function(q,a){var w=new g.pA;
w.languageCode=q.languageCode;w.languageName=q.languageName;w.name=q.name;w.displayName=q.displayName;w.kind=q.kind;w.isDefault=!1;w.V=q.V;w.isTranslateable=q.isTranslateable;w.vssId=q.vssId;w.url=q.url;w.translationLanguage=a;q.xtags&&(w.xtags=q.xtags);q.captionId&&(w.captionId=q.captionId);return w},Zb8=function(q,a){var w,G,k;
return g.h(function(b){if(b.U==1)return w=q+"|"+a,g.n(b,g.t2(),2);if(b.U!=3){G=b.V;if(!G)throw g.dw("gct");return g.n(b,g.wM(G),3)}k=b.V;return b.return(k.get("captions",w))})},E6l=function(q,a,w){Zb8(q,a).then(function(G){G&&w(G.trackData,new g.pA(G.metadata))})},mMl=function(q){if(!Vc7.test(q))throw Error("'"+q+"' is not a valid hex color");
q.length==4&&(q=q.replace(JxJ,"#$1$1$2$2$3$3"));q=q.toLowerCase();q=parseInt(q.slice(1),16);return[q>>16,q>>8&255,q&255]},Qb6=function(){var q=void 0;
q=q===void 0?{}:q;var a="suggest_correction"in g.vAx?g.vAx.suggest_correction:"Edit caption";a=a||"";var w={},G;for(G in q){w={WU:w.WU};w.WU=G;var k=function(b){return function(){return String(q[b.WU])}}(w);
a=a.replace(new RegExp("\\$\\{"+w.WU+"\\}","gi"),k);a=a.replace(new RegExp("\\$"+w.WU,"gi"),k)}return a},AxK=function(){return g.xt("yt-player-caption-display-settings")},YS=function(){this.segments=[]},xMK=function(q,a){var w=g.oB(q.segments,a);
w>=0||w<0&&(-w-1)%2===1||(w=-w-1,w>0&&a-q.segments[w-1]===1&&w<q.segments.length&&q.segments[w]-a===1?(g.Jl(q.segments,w),g.Jl(q.segments,w-1)):w>0&&a-q.segments[w-1]===1?q.segments[w-1]=a:w<q.segments.length&&q.segments[w]-a===1?q.segments[w]=a:(g.U6(q.segments,w,0,a),g.U6(q.segments,w+1,0,a)))},L1J=function(q,a,w,G,k,b){g.c.call(this);
this.policy=q;this.player=a;this.F9=w;this.S=G;this.D=k;this.J=b;this.Y=new YS;this.L=-1;this.W=this.U=this.V=null;this.UK=0;this.X=new g.o1(this.q0,1E3,this);this.events=new g.Ee(this);g.p(this,this.X);g.p(this,this.events);this.events.C(a,"SEEK_COMPLETE",this.hD);this.hD();this.q0()},BxK=function(q){return q.V&&q.V.L?q.V.L+q.player.g$()<q.player.getCurrentTime():!1},rxc=function(q,a){if(q.policy.u9&&q.player.g2()){var w=g.eS(a,q.policy,{});
w.set("pot",q.player.g2());w=w.Do()}else w=g.eS(a,q.policy,{}).Do();var G={format:"RAW",withCredentials:!0};if(q.policy.EK){G.method="POST";var k=a.Y;k&&Object.keys(k).length>0?G.postBody=g.oe(k,g.rl):G.postBody=(0,g.SF)([120,0])}q.D&&(G.responseType="arraybuffer");var b=++q.UK,O=(0,g.Zj)();q.W=g.JG(w,G,3,100,-1,function(e){e.errorCode==="net.timeout"&&q.player.d8("capnt",{rn:b++})}).then(function(e){if(q.policy.wN&&b%100===1){var N=(0,g.Zj)();
q.player.d8("caprsp",{rn:b,ms:N-O,kb:(e.xhr.responseText.length/1024).toFixed()})}a:{e=e.xhr;q.t2();if(q.U){var Y=!(q.D?e.response:e.responseText)||e.status>=400;if(N=g.lhc(e)){e=g.eS(q.U,q.policy,{});q.U.fF(e,N);rxc(q,q.U);break a}if(Y)q.player.d8("capfail",{status:e.status});else{var P;g.qx("fcb_r",(0,g.Zj)(),((P=q.player.getVideoData())==null?void 0:P.F9)||"");P=q.U.sK[0].Dh;q.S!=null&&q.L!==P&&(N=q.U.sK[0],q.D?q.S(e.response,(N.startTime+q.player.g$())*1E3):q.S(e.responseText,(N.startTime+q.player.g$())*
1E3),q.L=P)}}q.U=null;q.W=null}}).AK(function(e){q.U=null;
q.W=null;var N;q.player.d8("capfail",{rn:b,status:(N=e.xhr)==null?void 0:N.status})});
q.U=a;xMK(q.Y,q.U.sK[0].Dh)},Pq=function(q,a){g.Aq.call(this,a);
this.V=q;this.j=a;this.Y=null;this.L=!1;this.logger=new g.Zw("caps");this.X=g.q$l(this.j,this.V)},McB=function(q,a){var w=[],G;
for(G in q.V.V)if(q.V.V.hasOwnProperty(G)){var k=q.V.V[G];if(g.Lo(k,a||null)){var b=k.info.id,O=b,e="."+b,N="",Y="";if(k=k.info.captionTrack)b=k.languageCode,O=k.displayName,e=k.vssId,N=k.kind,Y=k.id;else{k=b;var P=g.sLJ.get(k);P==null&&(P=n68[k]||n68[k.replace(/-/g,"_")],g.sLJ.set(k,P));k=P;O=k||O}w.push(new g.pA({id:G,languageCode:b,languageName:O,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:e,kind:N,captionId:Y}))}}return w},hrc=function(q,a){return a!=null&&a in q.V.V?q.V.V[a]:null},
SKB=function(q,a,w){var G=[],k;
for(k in q.V.V)if(q.V.V.hasOwnProperty(k)){var b=q.V.V[k];if(g.Lo(b,w||null)){var O=b.info.captionTrack;O&&O.languageCode===a&&G.push(b)}}return G.length?G[0]:null},Kd=function(q,a,w,G,k,b,O,e,N,Y){var P=Y.isInline()&&!0,K={};
Object.assign(K,a);Object.assign(K,q.params);Object.assign(K,w);var d={};Object.assign(d,a.FN);q.params.FN&&Object.assign(d,q.params.FN);Object.assign(d,w.FN);P&&(K.windowOpacity=.6,d.backgroundOpacity=0);K.FN=d;var T=K.MM===1,F=[{G:"span",N:"captions-text",Z:{style:"word-wrap: normal; display: block;"}}],J,Q,B;(e=e.Zh("caption_edit_on_hover")&&((J=Y.getVideoData().getPlayerResponse())==null?void 0:(Q=J.captions)==null?void 0:(B=Q.playerCaptionsTracklistRenderer)==null?void 0:B.openTranscriptCommand))&&
F.unshift({G:"button",N:"caption-edit",Z:{tabindex:"0","aria-label":Qb6()},K:[{G:"svg",Z:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},K:[{G:"path",Z:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.u.call(this,{G:"div",N:"caption-window",Z:{id:"caption-window-"+q.id,dir:T?"rtl":"ltr",tabindex:"0",lang:K.lang},K:F});var L=
this;this.X=[];this.f7=!1;this.U=q;this.L7=this.EK=null;this.L0=b;this.OQ=O;this.S=null;this.maxWidth=b*.96;this.maxHeight=O*.96;this.V=K;this.Ai=w;this.UK=a;this.Y=this.oW("captions-text");this.yN=this.Y.style.getPropertyValue("box-decoration-break")!==""||this.Y.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.le=fBK(G,k,b,O);this.Ck=N;e&&(this.L=this.oW("caption-edit"),this.C(this.L,"click",function(){L.Ck()}));
this.type=0;this.St=this.le*HbU(d);this.VN=P;q=new g.UB(this.element,!0);g.p(this,q);q.subscribe("dragstart",this.EN,this);q.subscribe("dragmove",this.tY,this);q.subscribe("dragend",this.p8,this);this.h2=this.A2=this.IW=this.BT=0;q="";this.V.windowOpacity&&(q=mMl(this.V.windowColor),q="rgba("+q[0]+","+q[1]+","+q[2]+","+this.V.windowOpacity+")");a={"background-color":q,display:this.V.isVisible===!1?"none":"","text-align":cxI[this.V.textAlign]};this.yN&&(a["border-radius"]=q?this.St/8+"px":"");(this.W=
this.U.params.MM===2||this.U.params.MM===3)&&pIc(this,this.element);g.IR(this.element,a);if(P){var M;(M=this.element.parentElement)==null||M.style.setProperty("--caption-window-color",q)}switch(this.V.Wc){case 0:case 1:case 2:g.gU(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.gU(this.element,"ytp-caption-window-bottom")}},pIc=function(q,a){var w="vertical-rl";
q.V.Ty===1&&(w="vertical-lr");g.eL&&(w=w==="vertical-lr"?"tb-lr":"tb-rl");g.IR(a,"-o-writing-mode",w);g.IR(a,"-webkit-writing-mode",w);g.IR(a,"writing-mode",w);g.IR(a,"text-orientation","upright");g.gU(a,"ytp-vertical-caption");q.U.params.MM===3&&(g.IR(a,"text-orientation",""),g.IR(a,"transform","rotate(180deg)"))},HbU=function(q){var a=1+.25*(q.fontSizeIncrement||0);
if(q.offset===0||q.offset===2)a*=.8;return a},UM6=function(q,a){var w={},G=a.background?a.background:q.V.FN.background;
if(a.backgroundOpacity!=null||a.background){var k=a.backgroundOpacity!=null?a.backgroundOpacity:q.V.FN.backgroundOpacity;G=mMl(G);w.background="rgba("+G[0]+","+G[1]+","+G[2]+","+k+")";q.yN&&(w["box-decoration-break"]="clone",w["border-radius"]=q.St/8+"px")}if(a.fontSizeIncrement!=null||a.offset!=null)w["font-size"]=q.le*HbU(a)+"px";G=1;k=a.color||q.V.FN.color;if(a.color||a.textOpacity!=null)k=mMl(k),G=a.textOpacity==null?q.V.FN.textOpacity:a.textOpacity,k="rgba("+k[0]+","+k[1]+","+k[2]+","+G+")",
w.color=k,w.fill=k;var b=a.charEdgeStyle;b===0&&(b=void 0);if(b){k="rgba(34, 34, 34, "+G+")";var O="rgba(204, 204, 204, "+G+")";a.j3&&(O=k=a.j3);var e=q.le/16/2,N=Math.max(e,1),Y=Math.max(2*e,1),P=Math.max(3*e,1),K=Math.max(5*e,1);G=[];switch(b){case 4:for(;P<=K;P+=e)G.push(Y+"px "+Y+"px "+P+"px "+k);break;case 1:Y=window.devicePixelRatio>=2?.5:1;for(b=N;b<=P;b+=Y)G.push(b+"px "+b+"px "+k);break;case 2:G.push(N+"px "+N+"px "+O);G.push("-"+N+"px -"+N+"px "+k);break;case 3:for(P=0;P<5;P++)G.push("0 0 "+
Y+"px "+k)}w["text-shadow"]=G.join(", ")}k="";switch(a.fontFamily){case 1:k='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:k='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:k='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:k='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:k='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:k=g.py()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:k='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}k&&(w["font-family"]=k);k=a.offset;k==null&&(k=q.V.FN.offset);switch(k){case 0:w["vertical-align"]="sub";break;case 2:w["vertical-align"]="super"}a.fontFamily===7&&(w["font-variant"]="small-caps");a.bold&&(w["font-weight"]="bold");a.italic&&(w["font-style"]="italic");a.underline&&(w["text-decoration"]=
"underline");a.fB&&(w.visibility="hidden");a.H$===1&&q.W&&(w["text-combine-upright"]="all",w["text-orientation"]="mixed",k=g.mv||g.Ph,q.U.params.MM===3?w.transform=k?"rotate(90deg)":"rotate(180deg)":k&&(w.transform="rotate(-90deg)"));if(a.textEmphasis===1||a.textEmphasis===2||a.textEmphasis===3||a.textEmphasis===4||a.textEmphasis===5)if(g.mv)w["font-weight"]="bold";else switch(w["text-emphasis-style"]="filled circle",w["text-emphasis-color"]="currentcolor",w["webkit-text-emphasis"]="filled circle",
a.textEmphasis){case 4:case 3:w["text-emphasis-position"]="under left";w["webkit-text-emphasis-position"]="under left";break;case 5:case 2:w["text-emphasis-position"]="over right",w["webkit-text-emphasis-position"]="over right"}return w},dE=function(q){q=q.split("px");
return q.length>0?(q=Number(q[0]))?q:0:0},XIR=function(q){q.S=g.dp("SPAN");
g.IR(q.S,{display:"block"});g.gU(q.S,"caption-visual-line");q.Y.appendChild(q.S)},jbc=function(q,a){var w=g.dp("SPAN");
g.IR(w,{display:"inline-block","white-space":"pre-wrap"});g.IR(w,UM6(q,a));w.classList.add("ytp-caption-segment");q.S.appendChild(w);w.previousElementSibling&&(g.IR(w.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.IR(w,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return w},o66=function(q,a,w){q.f7=q.f7||!!w;
var G={};Object.assign(G,q.V.FN);Object.assign(G,w||a.V);Object.assign(G,q.Ai.FN);(w=!q.S)&&XIR(q);for(var k=q.EK&&q.L7&&g.TB(G,q.L7)?q.EK:jbc(q,G),b=typeof a.text==="string",O=b?a.text.split("\n"):[a.text],e=0;e<O.length;e++){var N=e>0||!a.append,Y=O[e];N&&!w?(XIR(q),k=jbc(q,G)):N&&w&&(w=!1);Y&&(k.appendChild(b?g.TY(Y):Y),b||Y.tagName!=="RUBY"||Y.childElementCount!==4||g.mv||!g.tM(Y.children[2],"text-emphasis")||(N=q.W?"padding-right":"padding-top",g.tM(Y.children[2],"text-emphasis-position")&&(N=
q.W?"padding-left":"padding-bottom"),g.NP?g.IR(k,N,"1em"):g.IR(k,N,"0.5em")))}q.L7=G;q.EK=k;q.X.push(a)},fBK=function(q,a,w,G){var k=a/360*16;
a>=q&&(q=640,G>w*1.3&&(q=480),k=w/q*16);return k},u$y=function(){this.W=this.time=this.mode=this.U=0;
this.Y=new IBe(this);this.D=new IBe(this);this.V=[];this.clear()},v6U=function(q,a,w){if(q===255&&a===255||!q&&!a)return{ZX:q,
Kv:a,result:0};q=tcl[q];a=tcl[a];if(q&128){var G;if(G=!(a&128))G=a,G=w.PN()&&w.Kv===G;if(G)return{ZX:q,Kv:a,result:1}}else if(a&128&&1<=q&&q<=31)return{ZX:q,Kv:a,result:2};return{ZX:q,Kv:a,result:3}},ibK=function(q,a,w,G){a===255&&w===255||!a&&!w?(++q.W===45&&q.reset(),q.Y.U.clear(),q.D.U.clear()):(q.W=0,zr8(q.Y,a,w,G))},W1l=function(q,a){q.V.sort(function(k,b){var O=k.time-b.time;
return O===0?k.order-b.order:O});
for(var w=g.V(q.V),G=w.next();!G.done;G=w.next())G=G.value,q.time=G.time,G.type===0?ibK(q,G.qR,G.QF,a):G.type===1&&q.U&496&&zr8(q.D,G.qR,G.QF,a);q.V.length=0},Tc=function(){this.type=0},$S=function(){this.state=this.Kv=this.ZX=0},DMy=function(){this.timestamp=this.V=0},FC=function(q){this.D=q;
this.W=[];this.V=this.U=this.row=0;this.style=new Tc;for(q=this.Y=0;q<=15;q++){this.W[q]=[];for(var a=0;a<=32;a++)this.W[q][a]=new DMy}},Cd=function(q,a){if(q.style.type===3){for(var w=0,G=0,k=q.D.time+0,b="",O="",e=k,N=1;N<=15;++N){for(var Y=!1,P=G?G:1;P<=32;++P){var K=q.W[N][P];
if(K.V!==0){w===0&&(w=N,G=P);Y=String.fromCharCode(K.V);var d=K.timestamp;d<k&&(k=d);K.timestamp=e;O&&(b+=O,O="");b+=Y;Y=!0}if((K.V===0||P===32)&&Y){O="\n";break}else if(G&&!Y)break}if(w&&!Y)break}b&&a.Y(w,G,k,e,b)}else for(G=w=0,b=k=q.D.time+0,O=1;O<=15;++O)for(e="",N=1;N<=32;++N)if(P=q.W[O][N],K=P.V,K!==0&&(w===0&&(w=O,G=N),Y=String.fromCharCode(K),d=P.timestamp,d<=k&&(k=d),e+=Y,P.reset()),N===32||K===0)e&&a.Y(w,G,k,b,e),k=b,e="",G=w=0},a9y=function(q,a){switch(q){case 0:return Rrl[(a&127)-32];
case 1:return yx8[a&15];case 2:return qky[a&31];case 3:return g$U[a&31]}return 0},ZF=function(q){return q.W[q.row][q.U]},Ev=function(q,a,w){a>=2&&q.U>1&&(--q.U,ZF(q).V=0);
var G=ZF(q);G.timestamp=q.D.time+0;G.V=a9y(a,w);q.U<32&&q.U++},wlI=function(q,a,w,G){for(var k=0;k<G;k++)for(var b=0;b<=32;b++){var O=q.W[a+k][b],e=q.W[w+k][b];
O.V=e.V;O.timestamp=e.timestamp}},V4=function(q,a,w){for(var G=0;G<w;G++)for(var k=0;k<=32;k++)q.W[a+G][k].reset()},G7K=function(q){q.row=q.V>0?q.V:1;
q.U=1;V4(q,0,15)},k7y=function(q){this.W=q;
this.D=0;this.style=new Tc;this.L=new FC(this.W);this.X=new FC(this.W);this.text=new FC(this.W);this.U=this.L;this.Y=this.X;this.V=this.U},b3I=function(q,a,w){var G=q.U,k=!1;
switch(q.style.get()){case 4:case 1:case 2:q.style.get()===4&&G.V>0||(Cd(G,w),G7K(q.U),G7K(q.Y),G.row=15,G.V=a,k=!0)}q.style.set(3);q.V=G;q.V.style=q.style;q.W.mode=1<<G.Y;k?G.U=1:G.V!==a&&(G.V>a?(Cd(G,w),V4(G,G.row-G.V,a)):G.row<a&&(a=G.V),G.V=a)},O3I=function(q){q.style.set(1);
q.V=q.Y;q.V.V=0;q.V.style=q.style;q.W.mode=1<<q.V.Y},l9e=function(q){q.style.set(4);
q.V=q.text;q.V.style=q.style;q.W.mode=1<<q.V.Y},IBe=function(q){this.V=q;
this.D=0;this.W=new k7y(this.V);this.L=new k7y(this.V);this.U=new $S;this.Y=this.W},zr8=function(q,a,w,G){q.U.update();
a=v6U(a,w,q.U);switch(a.result){case 0:return;case 1:case 2:return}var k=a.ZX;w=a.Kv;if(32<=k||!k)q.V.mode&q.V.U&&(a=k,a&128&&(a=127),w&128&&(w=127),q=q.Y.V,a&96&&Ev(q,0,a),w&96&&Ev(q,0,w),a!==0&&w!==0&&q.style.type===3&&Cd(q,G));else if(k&16)a:if(!q.U.matches(k,w)&&(a=q.U,a.ZX=k,a.Kv=w,a.state=2,a=k&8?q.L:q.W,q.Y=a,q.V.mode=1<<(q.D<<2)+(a.D<<1)+(a.style.type===4?1:0),(q.V.mode|1<<(q.D<<2)+(a.D<<1)+(a.style.type!==4?1:0))&q.V.U))if(w&64){G=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(k&7)<<1|w>>5&1];
q=w&16?((w&14)>>1)*4:0;w=a.V;switch(a.style.get()){case 4:G=w.row;break;case 3:if(G!==w.row){if(G<w.V&&(G=w.V,G===w.row))break;var b=1+w.row-w.V,O=1+G-w.V;wlI(w,O,b,w.V);a=b;k=w.V;O<b?(b=O+k-b,b>0&&(a+=b,k-=b)):(b=b+k-O,b>0&&(k-=b));V4(w,a,k)}}w.row=G;w.U=q+1}else switch(k&7){case 1:switch(w&112){case 32:Ev(a.V,0,32);break a;case 48:w===57?(G=a.V,ZF(G).V=0,G.U<32&&G.U++):Ev(a.V,1,w&15)}break;case 2:w&32&&Ev(a.V,2,w&31);break;case 3:w&32&&Ev(a.V,3,w&31);break;case 4:case 5:if(32<=w&&w<=47)switch(w){case 32:O3I(a);
break;case 33:G=a.V;G.U>1&&(--G.U,ZF(G).V=0);break;case 36:G=a.V;a=ZF(G);for(q=0;q<=15;q++)for(w=0;w<=32;w++)if(G.W[q][w]===a){for(;w<=32;w++)G.W[q][w].reset();break}break;case 37:b3I(a,2,G);break;case 38:b3I(a,3,G);break;case 39:b3I(a,4,G);break;case 40:Ev(a.V,0,32);break;case 41:a.style.set(2);a.V=a.U;a.V.V=0;a.V.style=a.style;a.W.mode=1<<a.V.Y;break;case 42:G=a.text;G.V=15;G.style.set(4);G7K(G);l9e(a);break;case 43:l9e(a);break;case 44:q=a.U;switch(a.style.get()){case 1:case 2:case 3:Cd(q,G)}V4(q,
0,15);break;case 45:b:{q=a.V;switch(a.style.get()){default:case 2:case 1:break b;case 4:if(q.row<15){++q.row;q.U=1;break b}break;case 3:}q.V<2&&(q.V=2,q.row<q.V&&(q.row=q.V));a=q.row-q.V+1;Cd(q,G);wlI(q,a,a+1,q.V-1);V4(q,q.row,1)}break;case 46:V4(a.Y,0,15);break;case 47:Cd(a.U,G),a.Y.updateTime(a.W.time+0),G=a.Y,a.Y=a.U,a.U=G,O3I(a)}break;case 7:switch(w){case 33:case 34:case 35:G=a.V,(G.U+=w&3)>32&&(G.U=32)}}},e$V=function(){},J_=function(q,a,w,G,k,b,O){b=b===void 0?!1:b;
O=O===void 0?null:O;g.Xo.call(this,q,q+a,{priority:w,namespace:"captions"});this.windowId=G;this.text=k;this.append=b;this.V=O},YkU=function(q,a,w,G,k,b,O){var e=b[0],N=O[e.getAttribute("p")];
if(N.WH===1){var Y=b[1],P=b[2];b=b[3];e.getAttribute("t");Y.getAttribute("t");P.getAttribute("t");b.getAttribute("t");e.getAttribute("p");Y.getAttribute("p");b.getAttribute("p");O=O[P.getAttribute("p")];e=NYc(e.textContent,Y.textContent,P.textContent,b.textContent,O);return new J_(q,a,k,w,e,G,N)}switch(N.WH){case 9:case 10:N.textEmphasis=1;break;case 11:N.textEmphasis=2;break;case 12:N.textEmphasis=3;break;case 13:N.textEmphasis=4;break;case 14:N.textEmphasis=5}return new J_(q,a,k,w,e.textContent||
"",G,N)},NYc=function(q,a,w,G,k){var b=g.py(),O=b?g.dp("DIV"):g.dp("RUBY"),e=g.dp("SPAN");
e.textContent=q;O.appendChild(e);q=b?g.dp("DIV"):g.dp("RP");q.textContent=a;O.appendChild(q);a=b?g.dp("DIV"):g.dp("RT");a.textContent=w;O.appendChild(a);w=k.WH;if(w===10||w===11||w===12||w===13||w===14)if(g.IR(a,"text-emphasis-style","filled circle"),g.IR(a,"text-emphasis-color","currentcolor"),g.IR(a,"webkit-text-emphasis","filled circle"),k.WH===11||k.WH===13)g.IR(a,"webkit-text-emphasis-position","under left"),g.IR(a,"text-emphasis-position","under left");w=!0;if(k.WH===4||k.WH===7||k.WH===12||
k.WH===14)g.IR(O,"ruby-position","over"),g.IR(O,"-webkit-ruby-position","before");else if(k.WH===5||k.WH===6||k.WH===11||k.WH===13)g.IR(O,"ruby-position","under"),g.IR(O,"-webkit-ruby-position","after"),w=!1;k=b?g.dp("DIV"):g.dp("RP");k.textContent=G;O.appendChild(k);b&&(G=w,g.IR(O,{display:"inline-block",position:"relative"}),b=O.firstElementChild.nextElementSibling,g.IR(b,"display","none"),b=b.nextElementSibling,g.IR(b,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.IR(O.lastElementChild,"display","none"),G?(g.IR(O,"padding-top","0.6em"),g.IR(b,"top","0")):(g.IR(O,"padding-bottom","0.6em"),g.IR(b,"bottom","0")));return O},mM=function(){g.c.apply(this,arguments)},Q4=function(q,a,w,G,k){g.Xo.call(this,q,q+a,{priority:w,
namespace:"captions"});this.id=G;this.params=k;this.V=[]},P6U=function(q){var a="_"+A_++;
return new Q4(0,0x8000000000000,0,a,q)},xS=function(q){mM.call(this);
this.Y=q;this.pens={};this.S={};this.J={};this.D="_"+A_++;this.X={};this.U=this.V=null;this.L=!0},Ld=function(q,a){q=q.getAttribute(a);
if(q!=null)return Number(q)},Bq=function(q,a){q=q.getAttribute(a);
if(q!=null)return q==="1"},rE=function(q,a){q=Ld(q,a);
return q!==void 0?q:null},M1=function(q,a){q=q.getAttribute(a);
if(q!=null)return nd.test(q),q},KGw=function(q,a){var w={},G=a.getAttribute("ws");
Object.assign(w,G?q.J[G]:q.Y);q=rE(a,"mh");q!=null&&(w.kJ=q);q=rE(a,"ju");q!=null&&(w.textAlign=q);q=rE(a,"pd");q!=null&&(w.MM=q);q=rE(a,"sd");q!=null&&(w.Ty=q);q=M1(a,"wfc");q!=null&&(w.windowColor=q);a=Ld(a,"wfo");a!==void 0&&(w.windowOpacity=a/255);return w},drI=function(q,a){var w={},G=a.getAttribute("wp");
G&&Object.assign(w,q.S[G]);q=rE(a,"ap");q!=null&&(w.Wc=q);q=Ld(a,"cc");q!=null&&(w.Vc=q);q=Ld(a,"ah");q!=null&&(w.iO=q);q=Ld(a,"rc");q!=null&&(w.GH=q);a=Ld(a,"av");a!=null&&(w.oE=a);return w},TYl=function(q,a,w,G){var k={};
Object.assign(k,drI(q,a));Object.assign(k,KGw(q,a));G?g.TB(k,q.Y)?(G=q.D,k=q.Y):G="_"+A_++:G=a.getAttribute("id")||"_"+A_++;q=Ld(a,"t")+w;a=Ld(a,"d")||0x8000000000000;if(k.MM===2||k.MM===3)w=k.GH,k.GH=k.Vc,k.Vc=w;return new Q4(q,a,0,G,k)},h_=function(q){mM.call(this);
this.L=q;this.V=new Map;this.Y=new Map;this.D=new Map;this.U=new Map},Sa=function(q){q=g.X1(Math.round(q),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-q.length)+q},$rI=function(q,a,w,G,k){G===0&&(G=0x8000000000000);
var b={};a.wpWinPosId&&Object.assign(b,q.Y.get(a.wpWinPosId));a.wsWinStyleId&&Object.assign(b,q.D.get(a.wsWinStyleId));q=a.rcRowCount;q!==void 0&&(b.GH=q);a=a.ccColCount;a!==void 0&&(b.Vc=a);if(b.MM===2||b.MM===3)a=b.GH,b.GH=b.Vc,b.Vc=a;return new Q4(w,G,0,k,b)},fd=function(q,a,w){g.Aq.call(this,q);
this.videoData=a;this.audioTrack=w;this.D=a.Ol},Hq=function(q,a,w,G,k,b,O,e,N,Y){Kd.call(this,q,a,w,G,k,b,O,e,N,Y);
this.type=1},cq=function(q,a,w){this.trackData=q;
this.L=w;this.version=this.D=this.W=this.byteOffset=0;this.U=[];this.V=new DataView(this.trackData)},pd=function(q){var a=q.byteOffset;
q.byteOffset+=1;return q.V.getUint8(a)},Uv=function(q){var a=q.byteOffset;
q.byteOffset+=4;return q.V.getUint32(a)},XC=function(q,a){mM.call(this);
this.U=q;this.Y=a;this.track=this.Y.languageName==="CC3"?4:0;this.V=new u$y;this.V.U=1<<this.track},FGV=function(q){if(typeof q==="string")return!1;
q=new cq(q,8,0);return snB(q)},snB=function(q){if(!(q.byteOffset<q.V.byteLength)||Uv(q)!==1380139777)return!1;
q.version=pd(q);if(q.version>1)return!1;pd(q);pd(q);pd(q);return!0},oD=function(q,a,w,G,k,b,O,e,N,Y){Kd.call(this,q,a,w,G,k,b,O,e,N,Y);
var P=this;this.type=2;this.y7=[];this.F9=this.J=this.Tl=0;this.jt=NaN;this.OA=0;this.N1=null;this.uF=new g.o1(this.TO,433,this);this.L&&(Y.createClientVe(this.L,this,167342),this.C(this.L,"click",function(){Y.logClick(P.L)}),q=new g.UB(this.element,!0),g.p(this,q),q.subscribe("hoverstart",function(){Y.logVisibility(P.L,!0)},this));
g.gU(this.element,"ytp-caption-window-rollup");g.p(this,this.uF);g.IR(this.element,"overflow","hidden")},C6K=function(q,a){if(!a)return"";
q.W&&q.U.params.Ty!==1&&(a*=-1);return"translate"+(q.W?"X":"Y")+"("+a+"px)"},Z3l=function(q){q.y7=Array.from(q.element.getElementsByClassName("caption-visual-line"));
for(var a=q.U.params.GH,w=0,G=0,k=q.y7.length-1;w<a&&k>-1;){var b=q.y7[k];G+=q.W?b.offsetWidth:b.offsetHeight;w++;k--}q.J=G;a=Math;w=a.max;isNaN(q.jt)&&((G=q.V.Vc)?(k=g.dp("SPAN"),g.EN(k,"\u2013".repeat(G)),g.IR(k,UM6(q,q.V.FN)),q.Y.appendChild(k),q.jt=k.offsetWidth,q.Y.removeChild(k)):q.jt=0);G=q.Y;q.F9=w.call(a,q.jt,q.OA,(q.W?G.offsetHeight:G.offsetWidth)+1)},E$I=function(q,a){Z3l(q);
var w=q.y7.reduce(function(b,O){return(q.W?O.offsetWidth:O.offsetHeight)+b},0);
w=q.J-w;if(w!==q.Tl){var G=w>0&&q.Tl===0,k=w<q.Tl;a||isNaN(w)||G||!k||(g.gU(q.element,"ytp-rollup-mode"),q.C(q.element,"transitionend",q.TO));g.IR(q.Y,"transform",C6K(q,w));q.Tl=w}Z3l(q)},VsB=function(q,a,w,G){var k=this;
this.j=q;this.W=a;this.logger=w;this.pk=G;this.uK=[];this.wy=[];this.V=null;this.qh={EYh:function(){return k.V},
xe:function(){return k.uK}};
q=g.Wo(this.j.B().experiments,"html5_override_micro_discontinuities_threshold_ms");this.U=q>0?q:10},Qn8=function(q,a){q.V=function(w,G){if(w.info.Y){var k=w;
if(q.wy.length>0){for(k=q.wy.shift();q.wy.length>0;)k=g.mo(k,q.wy.shift());k=g.mo(k,w)}if(k){w=k;try{var b=g.QW(w)*1E3}catch(Y){b=w.info.startTime*1E3}try{var O=g.RVl(w)*1E3}catch(Y){O=w.info.duration*1E3}if(b<0||O<0)b<0&&(b=w.info.startTime*1E3),O<0&&(O=w.info.duration*1E3);w.info.startTime=b/1E3;w.info.D=b/1E3;w.info.duration=O/1E3;w.info.S=O/1E3;b=q.Db(k);O=b.Dh;b={formatId:b.formatId,startTimeMs:b.startTimeMs,durationMs:b.durationMs,Fa:O,IN:O};O=Jo7(q.uK,b.startTimeMs);var e=(w=O>=0?q.uK[O]:null)?
w.startTimeMs+w.durationMs:0,N=b.startTimeMs+b.durationMs;!w||b.startTimeMs-e>q.U?q.uK.splice(O+1,0,b):(w.durationMs=Math.max(e,N)-w.startTimeMs,w.IN=Math.max(w.IN,b.IN));G(q.uK);G=g.Jw(k);mrx(q.W,G.buffer.slice(G.byteOffset,G.byteLength+G.byteOffset),a,k.info.D)}else q.logger.V(350058965,"Empty slice")}else q.wy.push(w)};
q.j.addEventListener("sabrCaptionsDataLoaded",q.V)},Jo7=function(q,a){q=g.oB(q,{startTimeMs:a},function(w,G){return w.startTimeMs-G.startTimeMs});
return q>=0?q:-q-2},ID=function(q,a){g.Aq.call(this,a);
this.V=q;this.j=a;this.logger=new g.Zw("caps");this.Y=this.L=null;this.X=new VsB(this.j,this,this.logger,this.V.pk)},mrx=function(q,a,w,G){q.logger.debug(function(){return"SABR captions data received for "+G});
q.L?q.Y==null?q.logger.V(350058965,"Null loaded track meta data at captions data received"):w.Hd(a,q.Y,G*1E3):q.logger.V(350058965,"Null Representation at captions data received")},Aow=function(q,a){var w=[],G;
for(G in q.V.V)if(q.V.V.hasOwnProperty(G)){var k=q.V.V[G];if(g.Lo(k,a||null)){var b=k.info.id,O=b,e="."+b,N="",Y="";if(k=k.info.captionTrack)b=k.languageCode,O=k.displayName,e=k.vssId,N=k.kind,Y=k.id;w.push(new g.pA({id:G,languageCode:b,languageName:O,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:e,kind:N,captionId:Y}))}}return w},xrw=function(q,a,w){var G=[],k;
for(k in q.V.V)if(q.V.V.hasOwnProperty(k)){var b=q.V.V[k];if(g.Lo(b,w||null)){var O=b.info.captionTrack;O&&O.languageCode===a&&G.push(b)}}return G.length?G[0]:null},LG7=function(q,a){if(!g.Dvm(q)||q.V!=null&&g.q$l(a,q.V)&&q.V.V.rawcc!=null)return!1;
a=!!q.V&&q.V.isManifestless&&Object.values(q.V.V).some(function(w){return g.Lo(w,"386")});
q=!!q.V&&!q.V.isManifestless&&g.PwG(q.V);return a||q},BYe=function(){mM.call(this)},n$I=function(q){var a=roy.length;
if(q.byteLength<a)return!1;q=new Uint8Array(q,0,a);for(var w=0;w<a;w++)if(roy[w]!==q[w])return!1;return!0},MsB=function(q,a,w,G,k,b,O,e,N){switch(O.tagName){case "b":e.bold=!0;
break;case "i":e.italic=!0;break;case "u":e.underline=!0}for(var Y=0;Y<O.childNodes.length;Y++){var P=O.childNodes[Y];if(P.nodeType===3)P=new J_(a,w,G,k.id,P.nodeValue,b||Y>0,g.KH(e)?void 0:e),N.push(P),k.V.push(P);else{var K={};Object.assign(K,e);MsB(q,a,w,G,k,!0,P,K,N)}}},h$U=function(q){var a=q.split(":");
q=0;a=g.V(a);for(var w=a.next();!w.done;w=a.next())q=q*60+Number(w.value);return q*1E3},Skw=function(q,a,w,G){G=Object.assign({kJ:0},G);
return new Q4(q,a,w,"_"+A_++,G)},u8=function(q,a){g.c.call(this);
this.j=q;this.V7=a;this.V=null;this.U=this.j.NZ();this.logger=new g.Zw("caps")},H3B=function(q,a,w){if(typeof a==="string"||FGV(a))return[{trackData:a,
vV:w}];if(typeof a==="string"&&a.substring(0,6)==="WEBVTT"||typeof a!=="string"&&n$I(a))return[{trackData:a,vV:w}];var G=new DataView(a);if(G.byteLength<=8||G.getUint32(4)!==1718909296)return[];var k=g.qem(G);if(q.U&&k){var b=g.tHU(k),O=g.vJ_(k);k=k.wk;b&&k&&q.U.IM(k,b,O)}q=g.EY(G,1835295092);if(!q||!q.length||!q[0].size)return[];b=[];for(O=0;O<q.length;O++)k=q[O],k=new Uint8Array(a,k.dataOffset,k.size-(k.dataOffset-k.offset)),k=g.Nj(k),b.push({trackData:k,vV:w+O*1E3});f9l(G,b,w);return b=b.filter(function(e){return!!e.trackData})},
f9l=function(q,a,w){var G=g.PG(q,0,1836476516),k=9E4;
G&&(k=g.K0(G)||9E4);G=0;for(var b=g.EY(q,1836019558),O=0;O<b.length;O++){var e=b[O];O<a.length&&(e=g.PG(q,e.dataOffset,1953653094))&&(e=g.PG(q,e.dataOffset,1952867444))&&(e=g.C0(e)/k*1E3,O===0&&(G=e),a[O].vV=e-G+w||w*O*1E3)}},coR=function(q,a,w){q.V||(q.V=new BYe);
q=q.V.W(a,w);Math.random()<.01&&g.Qa(Error("Deprecated subtitles format in web player: WebVTT"));return q},ple=function(q){var a={};
if(q=g.j6(q))a.lang=q,g.QsU.test(q)&&(a.MM=1);return a},jny=function(q){g.md.call(this,q);
var a=this;this.j=q;this.EK=[];this.y7={};this.St={};this.S=!1;this.Y="NONE";this.V=this.J=this.F9=this.le=this.BT=null;this.uF={lM:function(){a.lM()},
Hd:function(b,O,e,N){a.Hd(b,O,e,N)}};
this.U=null;this.V7=this.j.B();this.videoData=this.j.getVideoData();this.IW=this.j.mQ();this.W={FN:{}};this.L={FN:{}};g.T4(this.videoData)?this.Y="OFFLINE":LG7(this.videoData,this.j)?this.Y="SABR_LIVE":g.gCm(this.videoData,this.j)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.M9&&(this.Y="TTS");this.A2=this.V7.controlsType==="3";this.h2=new u8(this.j,this.V7);this.f7=new g.Ee(this);this.X=new g.u({G:"div",N:"ytp-caption-window-container",Z:{id:"ytp-caption-window-container"}});
this.UK={top:0,right:0,bottom:0,left:0,width:1,height:1};var w=null,G=g.na("yt-html5-player-modules::subtitlesModuleData");G&&(w=new g.Vp(G));this.storage=w;var k;this.VN=!((k=q.Z0())==null||!k.p5());this.D=Ur6(this);this.jt=!this.D&&this.A2&&this.VN&&(this.Y==="LIVE"||this.Y==="SABR_LIVE");g.p(this,this.h2);this.D?this.Tl=this.L7=null:(this.L7=new g.jd(this.qx,void 0,this),g.p(this,this.L7),this.Tl=new g.o1(this.toT,2E3,this),g.p(this,this.Tl));g.p(this,this.f7);g.DZ(this.player,this.X.element,4);
g.p(this,this.X);this.D||this.f7.C(q,"resize",this.B6);(this.OA=g.Gu(this.V7)&&!g.Yt()&&!this.j.isFullscreen()&&!this.D&&!this.jt)&&this.f7.C(q,"resize",this.nlh);this.f7.C(q,"onPlaybackAudioChange",this.zGT);this.f7.C(q,g.oM("captions"),function(b){a.onCueRangeEnter(b)});
this.f7.C(q,g.IM("captions"),function(b){a.onCueRangeExit(b)});
Xl6(this,AxK()||{});this.player.WN("onCaptionsModuleAvailable")},uRy=function(q){if(q.V7.zj===1||q.videoData.Nu===1||g.tF(q.videoData,"yt:cc")==="alwayson")return!0;
if(q.videoData.captionTracks.length)var a=q.getAudioTrack().U;if(q.V7.zj===2){if(g.Zg(q.V7))var w=o$K(q);else if(q.storage)try{w=q.storage.get("module-enabled")}catch(k){q.storage.remove("module-enabled")}else w=null;if(w!=null)return!!w}w=sby(q.player.getAudioTrack(),g.Zg(q.V7));var G=g.tF(q.videoData,"yt:cc");if(I9c(q)===void 0){if(w==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return G?G==="on":!0;if(w==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return G==="on"}else return G==="on";return a==="ON"||
g.tF(q.videoData,"yt:cc")==="on"},t_=function(q,a){if(q.U&&(a===void 0||!a)||!q.videoData.captionTracks.length)return!1;
q=q.getAudioTrack();return!!q.V||q.U==="FORCED_ON"},I9c=function(q){var a=void 0,w=g.S2(g.hE(),65);
if(g.Zg(q.V7)&&w!=null){if(o$K(q)!=null)return!1;a=!w}return a},zc=function(q,a){if(!q.V)return null;
if(q.J&&q.J.Y)return q.J.Y;a=tsI(q,a);a=g.Gg(q.V.U,a);var w=null;if(F16(q.V7)){var G=q.j.isInline()?void 0:g.xt("yt-player-caption-sticky-language");for(var k=[G,q.videoData.captionsLanguagePreference,q.V7.captionsLanguagePreference,g.tF(q.videoData,"yt:cc_default_lang")],b=!1,O=0;O<k.length;O++){var e=k[O];if(e){b=!0;for(var N=0;N<a.length;N++)if(g.j6(a[N])===e)return a[N];for(N=0;N<a.length;N++)if(g.j6(a[N]).split("-")[0]===e.split("-")[0])return a[N]}}if(b&&q.V&&(k=q.V.D,k.length))for(k=g.V(k),
b=k.next();!b.done;b=k.next())if(b=b.value,b.languageCode===G){w=b;break}}else for(G=[q.videoData.captionsLanguagePreference,q.V7.captionsLanguagePreference,g.tF(q.videoData,"yt:cc_default_lang")],k=0;k<G.length;k++)for(b=0;b<a.length;b++)if(g.j6(a[b])===G[k])return a[b];G=null;q.J&&q.J.W&&(G=q.J.W);G||(G=a.find(function(Y){return Y.isDefault})||null);
G||(G=a[0]||vq(q));G&&w&&g.j6(G).split("-")[0]!==w.languageCode.split("-")[0]&&(G=C27(G,w));return G},vq=function(q){return q.J&&q.J.V},i8=function(q){var a=vq(q);
return!!a&&q.U===a},v$8=function(q,a){var w=q.j.Z0().cq().textTracks;
q=q.U.toString();for(var G=0;G<w.length;G++){var k=w[G];k.id===q&&(a?k.mode!=="showing"&&(k.mode="showing"):k.mode==="showing"&&(k.mode="disabled"))}},RD=function(q,a,w){q.loaded&&q.unload();
w!=null&&(q.S=w,q.S&&(g.Zg(q.V7)?Wq(q,!!a):DF(q,!!a)));a!==null||t_(q,!0)||q.h4(a,!!a,q.S?"m":"s");q.U=a;t_(q)&&(q.U=vq(q));var G;z$U(q,(G=q.U)!=null?G:void 0);q.load()},WGl=function(q,a){if(a instanceof Q4){var w=q.y7[a.id];
w&&w.U!==a&&(w.dispose(),delete q.y7[a.id],w=null);w||(w=i3R(q,a))&&(q.y7[a.id]=w)}else w=a.windowId,q.St[w]||(q.St[w]=[]),q.St[w].push(a)},i3R=function(q,a){var w=DrR(q);
if(!w)return null;var G=q.U?g.j6(q.U):null;G&&g.QsU.test(G)&&(a.params.MM=1);var k=q.IW.getPlayerSize();G=k.height*q.UK.height;k=k.width*q.UK.width;q.V7.playerStyle!=="google-live"||q.W.isDefault||Object.assign(a.params,q.W);switch(a.params.kJ!=null?a.params.kJ:a.V.length>1?1:0){case 1:return new Hq(a,q.W,q.L,w.width,w.height,k,G,q.V7.experiments,q.V3.bind(q),q.j);case 2:return new oD(a,q.W,q.L,w.width,w.height,k,G,q.V7.experiments,q.V3.bind(q),q.j);default:return new Kd(a,q.W,q.L,w.width,w.height,
k,G,q.V7.experiments,q.V3.bind(q),q.j)}},Xl6=function(q,a,w){w=w===void 0?!1:w;
var G=y4.FN;q.W={};Object.assign(q.W,y4);q.W.FN={};Object.assign(q.W.FN,G);q.L={FN:{}};var k=a.backgroundOverride?q.L:q.W,b=a.background||G.background;nd.test(b);k.FN.background=b;k=a.colorOverride?q.L:q.W;b=a.color||G.color;nd.test(b);k.FN.color=b;k=a.windowColorOverride?q.L:q.W;b=a.windowColor||y4.windowColor;nd.test(b);k.windowColor=b;k=a.backgroundOpacityOverride?q.L:q.W;b=a.backgroundOpacity;b==null&&(b=G.backgroundOpacity);k.FN.backgroundOpacity=b;k=a.fontSizeIncrementOverride?q.L:q.W;b=a.fontSizeIncrement;
b==null&&(b=G.fontSizeIncrement);k.FN.fontSizeIncrement=b;b=a.fontStyleOverride?q.L:q.W;k=a.fontStyle;k==null&&(k=G.bold&&G.italic?3:G.bold?1:G.italic?2:0);b=b.FN;switch(k){case 1:b.bold=!0;delete b.italic;break;case 2:delete b.bold;b.italic=!0;break;case 3:b.bold=!0;b.italic=!0;break;default:delete b.bold,delete b.italic}k=a.textOpacityOverride?q.L:q.W;b=a.textOpacity;b==null&&(b=G.textOpacity);k.FN.textOpacity=b;k=a.windowOpacityOverride?q.L:q.W;b=a.windowOpacity;b==null&&(b=y4.windowOpacity);k.windowOpacity=
b;k=a.charEdgeStyleOverride?q.L:q.W;b=a.charEdgeStyle;b==null&&(b=G.charEdgeStyle);k.FN.charEdgeStyle=b;k=a.fontFamilyOverride?q.L:q.W;b=a.fontFamily;b==null&&(b=G.fontFamily);k.FN.fontFamily=b;q.loaded&&q.B6();w&&g.AE("yt-player-caption-display-settings",a,2592E3)},R$B=function(q,a){if(!q.V)return{};
if(a){g.KH(a)||q.Pm(a.vss_id,"m");if(q.D||!g.bV(a))return;if(g.KH(a)){RD(q,null,!0);return}for(var w,G=g.Gg(q.V.U,!0),k=0;k<G.length;k++){var b=G[k];b.languageCode!==a.languageCode||w&&(b.languageName!==a.languageName||(b.captionId||"")!==(a.captionId||"")||g.UV(b)!==a.displayName)||(w=a.translationLanguage?C27(b,a.translationLanguage):b)}q.gb(a.position);!w||w===q.U&&q.loaded||(a=g.Cx(),G=g.j6(w),a.length&&G===a[a.length-1]||(a.push(G),g.AE("yt-player-caption-language-preferences",a)),F16(q.V7)&&
!q.j.isInline()&&g.AE("yt-player-caption-sticky-language",G,2592E3),RD(q,w,!0))}else return q.loaded&&q.U&&!i8(q)?g.XY(q.U):{};return""},qAw=function(q,a,w){a&&!q.F9?(a=P6U({MM:0,
lang:"en-GB"}),q.F9=[a,new J_(a.start,a.end-a.start,0,a.id,w!=null?w:"Captions look like this")],q.player.N9(q.F9)):!a&&q.F9&&(yow(q,q.F9),q.F9=null)},yow=function(q,a){q.player.kE(a);
a=g.V(a);for(var w=a.next();!w.done;w=a.next())g.mU(q.EK,w.value);N1(q.L7)},z$U=function(q,a){q.V7.T("html5_modify_caption_vss_logging")&&(q.videoData.zW=a)},DrR=function(q){var a=q.IW.getVideoContentRect(!0).height,w=q.IW.getVideoContentRect(!0).width;
if(!a||!w)return null;a*=q.UK.height;w*=q.UK.width;return{width:w,height:a}},DF=function(q,a){if(q.storage)try{q.storage.set("module-enabled",a)}catch(w){}},Wq=function(q,a){q.j.isInline()||g.AE("yt-player-sticky-caption",a,2592E3)},o$K=function(q){if(!q.j.isInline())return g.xt("yt-player-sticky-caption")},Ur6=function(q){var a,w=!((a=q.j.Z0())==null||!a.DH());
return q.A2&&w&&q.Y!=="LIVE"&&q.Y!=="SABR_LIVE"},tsI=function(q,a){g.kU(q.videoData)&&(a=!0);
a||(a=q.Y==="TTS"?!1:q.Y==="INNERTUBE"?!1:!0);return a||q.V7.T("web_deprecate_always_includes_asr_setting")&&g.Zg(q.V7)?!0:!!g.S2(g.hE(),66)};
g.Aq.prototype.VR=g.kl(71,function(){return!1});
g.Aq.prototype.xY=g.kl(70,function(){});
g.xq.prototype.xY=g.kl(69,function(q,a,w){var G=this;this.t2();a=this.ea(q,a);var k=this.MB.B().T("html5_report_captions_ctmp_qoe"),b=(0,g.Zj)();this.YA();$MJ(this,a,{format:"RAW",onSuccess:function(O){G.V=null;if(k){var e=(O.responseText.length/1024).toFixed(),N=(0,g.Zj)();G.videoData.d8("capresp",{ms:N-b,kb:e})}w.Hd(O.responseText,q)},
onError:k?function(O){var e;O=(e=O==null?void 0:O.status)!=null?e:0;G.videoData.d8("capfail",{status:O})}:void 0,
withCredentials:!0})});
g.B1.prototype.xY=g.kl(68,function(q,a,w){var G=this;this.t2();a=this.ea(q,a);this.YA();this.V=g.Cy(a,{format:"RAW",onSuccess:function(k){G.V=null;w.Hd(k.responseText,q)},
withCredentials:!0})});
g.zQ.prototype.qk=g.kl(67,function(){for(var q=g.ON(document,"track",void 0,this.V),a=0;a<q.length;a++)g.Cn(q[a])});
g.UD.prototype.qk=g.kl(66,function(){this.mediaElement.qk()});
g.zQ.prototype.p5=g.kl(65,function(){return!(!this.V.textTracks||!this.V.textTracks.addEventListener)});
g.UD.prototype.p5=g.kl(64,function(){return this.mediaElement.p5()});
g.zQ.prototype.DH=g.kl(63,function(){return!!this.V.textTracks});
g.UD.prototype.DH=g.kl(62,function(){return this.mediaElement.DH()});
g.zQ.prototype.HA=g.kl(61,function(q){for(var a=0;a<q.length;a++)this.V.appendChild(q[a])});
g.UD.prototype.HA=g.kl(60,function(q){this.mediaElement.HA(q)});
g.ex.prototype.IM=g.kl(59,function(q,a,w){this.T0.IM(q,a,w)});
g.yK.prototype.IM=g.kl(58,function(q,a,w){this.U.set(q,{cY:a,Kx:w})});
g.qN.prototype.IM=g.kl(57,function(q,a,w){this.UK.IM(q,a,w)});
g.ex.prototype.c7=g.kl(56,function(q){return this.T0.c7(q)});
g.qN.prototype.c7=g.kl(55,function(q){var a=2;this.D.has(q)?a=0:g.bYc(this,q)&&(a=1);return a});
g.o$.prototype.K6=g.kl(43,function(q){var a=this.app.lK({playerType:void 0});return a?a.K6(q):!1});
g.wL.prototype.K6=g.kl(42,function(q){return this.aW.oG.K6(q)});
g.hP.prototype.K6=g.kl(41,function(q){return this.Me().some(function(a){return a.namespace===q})});
g.uR.prototype.K6=g.kl(40,function(){return!1});
g.o$.prototype.Pm=g.kl(38,function(q,a){this.app.xT().Pm(q,a)});
g.wL.prototype.Pm=g.kl(37,function(q,a){this.aW.Pm(q,a)});
g.gk.prototype.Pm=g.kl(36,function(q,a){q=[q,a];g.q_(this,g.wk(this.provider),"cfi",q)});
g.M_.prototype.Pm=g.kl(35,function(q,a){this.qoe&&this.qoe.Pm(q,a)});
g.GQ.prototype.Pm=g.kl(34,function(q,a){this.nk.Pm(q,a)});
g.uR.prototype.Pm=g.kl(33,function(){});
g.o$.prototype.h4=g.kl(32,function(q,a,w){this.app.xT().h4(q,a,w)});
g.wL.prototype.h4=g.kl(31,function(q,a,w){this.aW.h4(q,a,w)});
g.gk.prototype.h4=g.kl(30,function(q,a,w){if(this.L7!==q||this.Ck!==a)a=a==="rawcc"?"":a,w=[q,a,this.L7,w],g.q_(this,g.wk(this.provider),"cfs",w),this.L7=q,this.Ck=a});
g.M_.prototype.h4=g.kl(29,function(q,a,w){this.qoe&&this.qoe.h4(q,a,w)});
g.GQ.prototype.h4=g.kl(28,function(q,a,w){this.nk.h4(q,a,w)});
g.uR.prototype.h4=g.kl(27,function(){});
g.lA.prototype.Mo=g.kl(12,function(){return this.S});
g.Tb.prototype.Mo=g.kl(11,function(){return this.xT().NZ()});
g.o$.prototype.NZ=g.kl(10,function(){return this.app.Mo()});
g.wL.prototype.NZ=g.kl(9,function(){return this.aW.NZ()});
g.GQ.prototype.NZ=g.kl(8,function(){var q;return((q=this.loader)==null?void 0:q.Mo())||null});
g.uR.prototype.NZ=g.kl(7,function(){return null});
g.yo.prototype.QA=g.kl(1,function(q){return(q=this.tG(q))?q.V:0});
g.Bw.prototype.QA=g.kl(0,function(){return 0});
var JxJ=/#(.)(.)(.)/,Vc7=/^#(?:[0-9a-f]{3}){1,2}$/i,n68={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};YS.prototype.contains=function(q){q=g.oB(this.segments,q);return q>=0||q<0&&(-q-1)%2===1};
YS.prototype.length=function(){return this.segments.length/2};
g.Z(L1J,g.c);g.C=L1J.prototype;g.C.qB=function(){g.c.prototype.qB.call(this);this.W&&this.W.cancel()};
g.C.hD=function(){this.seekTo(this.player.getCurrentTime())};
g.C.seekTo=function(q){q-=this.player.g$();var a=this.V;this.V=g.s6(this.F9.tb(q).sK);a!==this.V&&this.J&&this.J()};
g.C.reset=function(){this.Y=new YS;this.L=-1;this.W&&(this.W.cancel(),this.W=null)};
g.C.q0=function(){this.t2();var q;if(q=this.V!=null)q=this.V,q=q.V.Cv(q);if(q&&!this.W&&!(this.V&&this.V.startTime-this.player.getCurrentTime()>30)){q=this.V;q=q.V.ww(q);var a=q.sK[0],w;if((w=this.player.getVideoData())==null?0:w.enableServerStitchedDai)if(w=this.player.NZ()){var G=a.V.info.id,k=a.Dh,b=q.sK[0].D;if(this.policy.EK){if(w=w.Yy(b,k,G,3))q.Y=w}else if(G=w.Nk(b,k,G,3))if(w=w.c7(k),w===0)G&&(q.V=new g.u5(G));else if(w===2){this.X.start();BxK(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.V.index.PF(a.Dh)?(this.Y.contains(q.sK[0].Dh)||rxc(this,q),this.V=g.s6(q.sK)):BxK(this)&&this.seekTo(this.player.getCurrentTime())}this.X.start()};
g.Z(Pq,g.Aq);g.C=Pq.prototype;g.C.xY=function(q,a,w){var G=this;this.YA();a=hrc(this,q.getId());a||(a=q.languageCode,a=this.V.isManifestless?SKB(this,a,"386"):SKB(this,a));if(a){var k=(a.index.QA(a.index.l9())-a.index.getStartTime(a.index.l9()))*1E3,b=this.j.B(),O=new g.jWl(b),e=function(){G.Y&&G.Y.reset();G.L=!0};
b.T("html5_keep_caption_data_after_seek")&&(e=null);this.Y=new L1J(O,this.j,a,function(N,Y){w.Hd(N,q,Y,k)},this.X||g.vY(a.info),e)}};
g.C.VR=function(){var q=this.L;this.L=!1;return q};
g.C.Oi=function(q){var a=this.j.B().T("html5_fallback_if_rawcc_missing");var w=this.V.V.rawcc!=null;if(!this.X||!w&&a)a=this.V.isManifestless?McB(this,"386"):McB(this);else{if(!w){this.logger.V(386248249,"rawcc used but unavailable");return}a=[new g.pA({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.pA({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}a=g.V(a);
for(w=a.next();!w.done;w=a.next())g.Ql(this.U,w.value);q.lM()};
g.C.YA=function(){this.Y&&(this.Y.dispose(),this.Y=null)};
g.C.ea=function(){return""};
var nd=/^#(?:[0-9a-f]{3}){1,2}$/i;var cxI=["left","right","center","justify"];g.Z(Kd,g.u);g.C=Kd.prototype;g.C.EN=function(q,a){this.A2=q;this.h2=a;var w=g.yD(this.element,this.element.parentElement);this.BT=q-w.x;this.IW=a-w.y};
g.C.tY=function(q,a){if(q!==this.A2||a!==this.h2){g.qG(this.element,"ytp-dragging")||g.gU(this.element,"ytp-dragging");var w=g.gh(this.element);q=q-this.BT-.02*this.L0;var G=a-this.IW-.02*this.OQ,k=(q+w.width/2)/this.maxWidth*3;k=Math.floor(g.X1(k,0,2));var b=(G+w.height/2)/this.maxHeight*3;b=Math.floor(g.X1(b,0,2));a=k+b*3;q=(q+k/2*w.width)/this.maxWidth;q=g.X1(q,0,1)*100;w=(G+b/2*w.height)/this.maxHeight;w=g.X1(w,0,1)*100;this.U.params.Wc=a;this.U.params.oE=w;this.U.params.iO=q;this.U.params.isDefault=
!1;this.V.Wc=a;this.V.oE=w;this.V.iO=q;this.V.isDefault=!1;this.UK.Wc=a;this.UK.oE=w;this.UK.iO=q;this.UK.isDefault=!1;this.TF()}};
g.C.p8=function(){g.wU(this.element,"ytp-dragging")};
g.C.TF=function(){this.T7(this.X)};
g.C.T7=function(q){var a=this.VN?0:Math.min(this.pI(),this.maxWidth),w=this.DI(),G=this.VN;if(G){var k=getComputedStyle(this.Y.parentNode);k=dE(k.borderLeftWidth)+dE(k.borderRightWidth)+dE(k.paddingLeft)+dE(k.paddingRight)}else k=0;var b=k;k="";this.U.params.MM===3&&(k="rotate(180deg)");var O=G?"calc(96% - "+b+"px)":"96%";g.IR(this.element,{top:0,left:0,right:"",bottom:"",width:a?a+"px":"",height:w?w+"px":"","max-width":O,"max-height":O,margin:"",transform:""});this.ID(q);k={transform:k,top:"",left:"",
width:a?a+"px":"",height:w?w+"px":"","max-width":"","max-height":""};var e=this.V.iO*.96+2;O=this.V.Wc;switch(O){case 0:case 3:case 6:(G=this.V.FN.fontSizeIncrement)&&G>0&&this.V.MM!==2&&this.V.MM!==3&&(e=Math.max(e/(1+G*2),2));k.left=e+"%";break;case 1:case 4:case 7:k.left=e+"%";e=this.Y.offsetWidth;a||e?(a=a||e+1,k.width=a+"px",k["margin-left"]=G?a/-2-b/2+"px":a/-2+"px"):k.transform+=" translateX(-50%)";break;case 2:case 5:case 8:k.right=100-e+"%"}G=this.V.oE*.96+2;switch(O){case 0:case 1:case 2:k.top=
G+"%";break;case 3:case 4:case 5:k.top=G+"%";(w=w||this.element.clientHeight)?(k.height=w+"px",k["margin-top"]=w/-2+"px"):k.transform+=" translateY(-50%)";break;case 6:case 7:case 8:k.bottom=100-G+"%"}g.IR(this.element,k);if(this.L){w=this.Y.offsetHeight;G=1;for(a=0;a<q.length;a++)k=q[a],typeof k.text==="string"&&(G+=k.text.split("\n").length-1,k.append||a===0||G++);w/=G;this.L.style.height=w+"px";this.L.style.width=w+"px";this.element.style.paddingLeft=w+5+"px";this.element.style.paddingRight=w+
5+"px";q=Number(this.element.style.marginLeft.replace("px",""))-w-5;w=Number(this.element.style.marginRight.replace("px",""))-w-5;this.element.style.marginLeft=q+"px";this.element.style.marginRight=w+"px"}};
g.C.ID=function(q){var a;for(a=0;a<q.length&&q[a]===this.X[a];a++);if(this.f7||this.X.length>a)a=0,this.f7=!1,this.X=[],this.S=this.L7=this.EK=null,g.sN(this.Y);for(;a<q.length;a++)o66(this,q[a])};
g.C.pI=function(){return 0};
g.C.DI=function(){return 0};
g.C.toString=function(){return g.u.prototype.toString.call(this)};u$y.prototype.clear=function(){this.W=this.time=this.mode=0;this.V=[];this.reset()};
u$y.prototype.reset=function(){this.mode=0;this.Y.reset(0);this.D.reset(1)};
var tcl=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Tc.prototype.set=function(q){this.type=q};
Tc.prototype.get=function(){return this.type};
$S.prototype.clear=function(){this.state=0};
$S.prototype.update=function(){this.state=this.state===2?1:0};
$S.prototype.PN=function(){return this.state!==0};
$S.prototype.matches=function(q,a){return this.PN()&&q===this.ZX&&a===this.Kv};
DMy.prototype.reset=function(){this.timestamp=this.V=0};
FC.prototype.updateTime=function(q){for(var a=1;a<=15;++a)for(var w=1;w<=32;++w)this.W[a][w].timestamp=q};
FC.prototype.debugString=function(){for(var q="\n",a=1;a<=15;++a){for(var w=1;w<=32;++w){var G=this.W[a][w];q=G.V===0?q+"_":q+String.fromCharCode(G.V)}q+="\n"}return q};
FC.prototype.reset=function(q){for(var a=0;a<=15;a++)for(var w=0;w<=32;w++)this.W[a][w].reset();this.Y=q;this.V=0;this.U=this.row=1};
var Rrl=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],yx8=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],qky=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],g$U=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];k7y.prototype.reset=function(q,a){this.D=a;this.style.set(2);this.U=this.L;this.Y=this.X;this.V=this.U;var w=(q<<2)+(a<<1);this.L.reset(w);this.X.reset(w);this.text.reset((q<<2)+(a<<1)+1)};
IBe.prototype.reset=function(q){this.D=q;this.U.clear();this.Y=this.W;this.W.reset(q,0);this.L.reset(q,1)};e$V.prototype.Y=function(){};g.Z(J_,g.Xo);J_.prototype.toString=function(){return g.Xo.prototype.toString.call(this)};g.Z(mM,g.c);mM.prototype.reset=function(){};g.Z(Q4,g.Xo);Q4.prototype.toString=function(){return g.Xo.prototype.toString.call(this)};
var A_=0;g.Z(xS,mM);xS.prototype.reset=function(){this.X={};this.U=this.V=null;this.L=!0};
xS.prototype.W=function(q,a){q=q.firstChild;q.getAttribute("format");a=a||0;Number.isFinite(a);q=Array.from(q.childNodes);q=g.V(q);for(var w=q.next();!w.done;w=q.next())if(w=w.value,w.nodeType===1)switch(w.tagName){case "head":var G=w;break;case "body":var k=w}if(G)for(G=Array.from(G.childNodes),G=g.V(G),q=G.next();!q.done;q=G.next())if(q=q.value,q.nodeType===1)switch(q.tagName){case "pen":w=q.getAttribute("id");var b=this.pens,O={},e=q.getAttribute("p");e&&Object.assign(O,this.pens[e]);e=Bq(q,"b");
e!=null&&(O.bold=e);e=Bq(q,"i");e!=null&&(O.italic=e);e=Bq(q,"u");e!=null&&(O.underline=e);e=rE(q,"et");e!=null&&(O.charEdgeStyle=e);e=rE(q,"of");e!=null&&(O.offset=e);e=M1(q,"bc");e!=null&&(O.background=e);e=M1(q,"ec");e!=null&&(O.j3=e);e=M1(q,"fc");e!=null&&(O.color=e);e=rE(q,"fs");e!=null&&e!==0&&(O.fontFamily=e);e=Ld(q,"sz");e!==void 0&&(O.fontSizeIncrement=e/100-1);e=Ld(q,"bo");e!==void 0&&(O.backgroundOpacity=e/255);e=Ld(q,"fo");e!==void 0&&(O.textOpacity=e/255);e=rE(q,"rb");e!=null&&e!==10&&
e!==0&&(O.WH=e>10?e-1:e);q=rE(q,"hg");q!=null&&(O.H$=q);b[w]=O;break;case "ws":w=q.getAttribute("id");this.J[w]=KGw(this,q);break;case "wp":w=q.getAttribute("id"),this.S[w]=drI(this,q)}if(k){G=[];k=Array.from(k.childNodes);k=g.V(k);for(q=k.next();!q.done;q=k.next())if(q=q.value,q.nodeType===1)switch(q.tagName){case "w":this.V=TYl(this,q,a,!1);(q=this.X[this.V.id])&&q.end>this.V.start&&(q.end=this.V.start);this.X[this.V.id]=this.V;G.push(this.V);break;case "p":var N=q;e=a;w=[];b=N.getAttribute("w")||
this.D;O=!!Bq(N,"a");e=(Ld(N,"t")||0)+e;var Y=Ld(N,"d")||5E3;O||(!this.L&&this.U&&this.U.windowId===b&&this.U.end>e&&(this.U.end=e),this.U&&this.U.text==="\n"&&(this.U.text=""));var P=O?6:5,K=N.getAttribute("p");K=K?this.pens[K]:null;var d=Array.from(N.childNodes);d.length&&(this.L=N.getAttribute("d")!=null);for(N=0;N<d.length;N++){var T=d[N],F=void 0;N>0&&(O=!0);var J=void 0;T.nodeType===1&&(J=T);if(J&&J.tagName==="s"){if((T=(T=J.getAttribute("p"))?this.pens[T]:null)&&T.WH&&(T.WH===1?(T=d.slice(N,
N+4),T.length===4&&(F=YkU(e,Y,b,O,P,T,this.pens),N+=3)):F=YkU(e,Y,b,O,P,[J],this.pens)),!F){var Q=J;F=e;J=Y;T=b;var B=O,L=P,M=Q.textContent?Q.textContent:"",H=Q.getAttribute("p");H=H?this.pens[H]:null;Q=Ld(Q,"t")||0;F=new J_(F+Q,J-Q,L,T,M,B,H)}}else F=new J_(e,Y,P,b,T.textContent||"",O,K);w.push(F);this.U=F}if(w.length>0)for(w[0].windowId===this.D&&(this.V=TYl(this,q,a,!0),G.push(this.V)),q=g.V(w),w=q.next();!w.done;w=q.next())w=w.value,w.windowId=this.V.id,this.V.V.push(w),G.push(w)}a=G}else a=[];
return a};var gYR=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.Z(h_,mM);h_.prototype.reset=function(){this.U.clear()};
h_.prototype.W=function(q,a){var w=JSON.parse(q);if(!w)return[];if(w.pens){q=0;for(var G=g.V(w.pens),k=G.next();!k.done;k=G.next()){k=k.value;var b={},O=k.pParentId;O&&Object.assign(b,this.V.get(O));k.bAttr&&(b.bold=!0);k.iAttr&&(b.italic=!0);k.uAttr&&(b.underline=!0);O=k.ofOffset;O!=null&&(b.offset=O);k.szPenSize!==void 0&&(b.fontSizeIncrement=k.szPenSize/100-1);O=k.etEdgeType;O!=null&&(b.charEdgeStyle=O);k.ecEdgeColor!==void 0&&(b.j3=Sa(k.ecEdgeColor));O=k.fsFontStyle;O!=null&&O!==0&&(b.fontFamily=
O);k.fcForeColor!==void 0&&(b.color=Sa(k.fcForeColor));k.foForeAlpha!==void 0&&(b.textOpacity=k.foForeAlpha/255);k.bcBackColor!==void 0&&(b.background=Sa(k.bcBackColor));k.boBackAlpha!==void 0&&(b.backgroundOpacity=k.boBackAlpha/255);(O=k.rbRuby)&&O!==10&&(b.WH=O>10?O-1:O,b.textEmphasis=gYR.get(b.WH));k.hgHorizGroup&&(b.H$=k.hgHorizGroup);this.V.set(q++,b)}}if(w.wsWinStyles)for(q=0,G=g.V(w.wsWinStyles),k=G.next();!k.done;k=G.next())k=k.value,b={},(O=k.wsParentId)?Object.assign(b,this.D.get(O)):Object.assign(b,
this.L),k.mhModeHint!==void 0&&(b.kJ=k.mhModeHint),k.juJustifCode!==void 0&&(b.textAlign=k.juJustifCode),k.pdPrintDir!==void 0&&(b.MM=k.pdPrintDir),k.sdScrollDir!==void 0&&(b.Ty=k.sdScrollDir),k.wfcWinFillColor!==void 0&&(b.windowColor=Sa(k.wfcWinFillColor)),k.wfoWinFillAlpha!==void 0&&(b.windowOpacity=k.wfoWinFillAlpha/255),this.D.set(q++,b);if(w.wpWinPositions)for(q=0,G=g.V(w.wpWinPositions),k=G.next();!k.done;k=G.next())k=k.value,b={},(O=k.wpParentId)&&Object.assign(b,this.Y.get(O)),k.ahHorPos!==
void 0&&(b.iO=k.ahHorPos),k.apPoint!==void 0&&(b.Wc=k.apPoint),k.avVerPos!==void 0&&(b.oE=k.avVerPos),k.ccCols!==void 0&&(b.Vc=k.ccCols),k.rcRows!==void 0&&(b.GH=k.rcRows),this.Y.set(q++,b);if(w.events){q=[];w=g.V(w.events);for(G=w.next();!G.done;G=w.next()){var e=G.value;k=(e.tStartMs||0)+a;b=e.dDurationMs||0;if(e.id)O=String(e.id),G=$rI(this,e,k,b,O),q.push(G),this.U.set(O,G);else{e.wWinId?O=e.wWinId.toString():(O="_"+A_++,G=$rI(this,e,k,b,O),q.push(G),this.U.set(O,G));G=q;var N=e;b===0&&(b=5E3);
e=this.U.get(O);var Y=!!N.aAppend,P=Y?6:5,K=N.segs,d=null;N.pPenId&&(d=this.V.get(N.pPenId));for(N=0;N<K.length;N++){var T=K[N],F=T.utf8;if(F){var J=T.tOffsetMs||0,Q=null;T.pPenId&&(Q=this.V.get(T.pPenId));if((e.params.kJ!=null?e.params.kJ:e.V.length>1?1:0)===2&&Y&&F==="\n")continue;T=null;var B=[],L;if(L=Q&&Q.WH===1){L=K;var M=N;if(M+3>=L.length||!L[M+1].pPenId||!L[M+2].pPenId||!L[M+3].pPenId)L=!1;else{var H=L[M+1].pPenId;(H=this.V.get(H))&&H.WH&&H.WH===2?(H=L[M+2].pPenId,H=this.V.get(H),!H||!H.WH||
H.WH<3?L=!1:(H=L[M+3].pPenId,L=(H=this.V.get(H))&&H.WH&&H.WH===2?!0:!1)):L=!1}}if(L)J=K[N+1].utf8,T=K[N+3].utf8,L=K[N+2].utf8,M=this.V.get(K[N+2].pPenId),F=NYc(F,J,L,T,M),T=new J_(k,b,P,O,F,Y,Q),N+=3;else{if(F.indexOf("<")>-1){var X=void 0;B=Q;L=d;M=k;H=b;var D=J,z=P,Oj=Y,$l=[],ey=g.i7("<html>"+F+"</html>");if(!ey.getElementsByTagName("parsererror").length&&((X=ey.firstChild)==null?0:X.childNodes.length))for(X=g.V(ey.firstChild.childNodes),ey=X.next();!ey.done;ey=X.next()){ey=ey.value;var Nm=void 0,
a_=void 0,BJ=(a_=(Nm=ey.textContent)==null?void 0:Nm.replace(/\n/g,""))!=null?a_:"";if(ey.nodeType!==3||BJ&&BJ.match(/^ *$/)==null){Nm={};Object.assign(Nm,B||L);a_=void 0;switch((a_=ey)==null?void 0:a_.tagName){case "b":Nm.bold=!0;break;case "i":Nm.italic=!0;break;case "u":Nm.underline=!0}$l.push(new J_(M+D,H-D,z,e.id,BJ,Oj,Nm))}}B=$l}B.length||(B=[new J_(k+J,b-J,P,e.id,F,Y,Q||d)])}if(B.length)for(Y=g.V(B),Q=Y.next();!Q.done;Q=Y.next())Q=Q.value,G.push(Q),e.V.push(Q);else T&&(G.push(T),e.V.push(T))}Y=
!0}}}a=q}else a=[];return a};g.Z(fd,g.Aq);fd.prototype.xY=function(q,a,w){E6l(this.videoData.videoId,q.vssId,w.Hd)};
fd.prototype.Oi=function(q){if(this.audioTrack)for(var a=g.V(this.audioTrack.captionTracks),w=a.next();!w.done;w=a.next())g.Ql(this.U,w.value);q.lM()};g.Z(Hq,Kd);Hq.prototype.ID=function(q){var a=this.U.V;Kd.prototype.ID.call(this,q);for(q=q.length;q<a.length;q++){var w=a[q];if(b&&w.V===k)var G=b;else{G={};Object.assign(G,w.V);Object.assign(G,aO7);var k=w.V;var b=G}o66(this,w,G)}};
var aO7={fB:!0};g.Z(cq,e$V);cq.prototype.Y=function(q,a,w,G,k){if(w<G){var b="_"+A_++;w=w/1E3-this.L;G=G/1E3-this.L;q=new Q4(w,G-w,5,b,{textAlign:0,Wc:0,iO:a*2.5,oE:q*5.33});k=new J_(w,G-w,5,b,k);this.U.push(q);this.U.push(k)}};
g.Z(XC,mM);XC.prototype.W=function(q){q=new cq(q,q.byteLength,this.U);if(snB(q)){for(;q.byteOffset<q.V.byteLength;)for(q.version===0?q.W=Uv(q)*(1E3/45):q.version===1&&(q.W=Uv(q)*4294967296+Uv(q)),q.D=pd(q);q.D>0;q.D--){var a=pd(q),w=pd(q),G=pd(q);a&4&&(a&3)===this.track&&(this.track===0||this.track===1)&&(a=this.V,a.V.push({time:q.W,type:this.track,qR:w,QF:G,order:a.V.length}))}W1l(this.V,q);return q.U}return[]};
XC.prototype.reset=function(){this.V.clear()};g.Z(oD,Kd);g.C=oD.prototype;g.C.TF=function(){g.vv(this.uF)};
g.C.TO=function(){this.element.removeEventListener("transitionend",this.TO,!1);g.wU(this.element,"ytp-rollup-mode");this.T7(this.N1,!0)};
g.C.DI=function(){return this.W?this.F9:this.J};
g.C.pI=function(){return this.W?this.J:this.F9};
g.C.T7=function(q,a){this.N1=q;if(this.U.params.GH){for(var w=0,G=0;G<this.X.length&&w<q.length;G++)this.X[G]===q[w]&&w++;w>0&&w<q.length&&(q=this.X.concat(q.slice(w)));this.OA=this.F9;this.J=this.F9=0;Kd.prototype.T7.call(this,q);E$I(this,a)}Kd.prototype.T7.call(this,q)};VsB.prototype.unload=function(){this.V!=null&&(this.j.removeEventListener("sabrCaptionsDataLoaded",this.V),this.V=null);this.uK=[];this.j.publish("sabrCaptionsBufferedRangesUpdated",this.uK)};
VsB.prototype.Db=function(q){return{formatId:g.WY(q.info.V.info,this.pk),Dh:q.info.Dh+(this.pk?0:1),startTimeMs:q.info.D*1E3,durationMs:q.info.S*1E3}};g.Z(ID,g.Aq);ID.prototype.xY=function(q,a,w){this.YA();a=q.getId();a=a!=null&&a in this.V.V?this.V.V[a]:null;a||(a=q.languageCode,a=this.V.isManifestless?xrw(this,a,"386"):xrw(this,a));a&&(this.Y=q,this.L=a,Qn8(this.X,w),this.j.publish("sabrCaptionsTrackChanged",g.WY(a.info,this.V.pk)))};
ID.prototype.Oi=function(q){var a=this.V.isManifestless?Aow(this,"386"):Aow(this);a=g.V(a);for(var w=a.next();!w.done;w=a.next())g.Ql(this.U,w.value);q.lM()};
ID.prototype.YA=function(){this.Y&&(this.Y=this.L=null,this.X.unload(),this.j.publish("sabrCaptionsTrackChanged",null))};
ID.prototype.ea=function(){return""};var roy="WEBVTT".split("").map(function(q){return q.charCodeAt(0)});
g.Z(BYe,mM);
BYe.prototype.W=function(q,a){q instanceof ArrayBuffer&&(q=g.Nj(new Uint8Array(q)));var w=[];q=q.split(wQy);for(var G=1;G<q.length;G++){var k=q[G],b=a;if(k!==""&&!Gr7.test(k)){var O=krR.exec(k);if(O&&O.length>=4){var e=h$U(O[1]),N=h$U(O[2])-e;e+=b;var Y=(O=O[3])?O.split(" "):[];O={};var P=null;var K="";var d=null,T="";Y=g.V(Y);for(var F=Y.next();!F.done;F=Y.next())if(F=F.value.split(":"),F.length===2){var J=F[1];switch(F[0]){case "line":F=J.split(",");F[0].endsWith("%")&&(P=F[0],O.oE=Number.parseInt(P,
10),F.length===2&&(K=F[1].trim()));break;case "position":F=J.split(",");d=F[0];O.iO=Number.parseInt(d,10);F.length===2&&(T=F[1].trim());break;case "align":switch(J){case "start":O.textAlign=0;break;case "middle":O.textAlign=2;break;case "end":O.textAlign=1}}}P||K||(K="end");if(!d)switch(O.textAlign){case 0:O.iO=0;break;case 1:O.iO=100;break;case 2:O.iO=50}if(O.textAlign!=null){P=0;switch(K){case "center":P+=3;break;case "end":P+=6;break;default:P+=0}switch(T){case "line-left":P+=0;break;case "center":P+=
1;break;case "line-right":P+=2;break;default:switch(O.textAlign){case 0:P+=0;break;case 2:P+=1;break;case 1:P+=2}}K=P<0||P>8?7:P;O.Wc=K}k=k.substring(krR.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");T=O;O=k;k={};if(O.indexOf("<")<0&&O.indexOf("&")<0)b=Skw(e,N,5,T),N=new J_(e,N,5,b.id,O,!1,g.KH(k)?void 0:k),w.push(b),w.push(N),b.V.push(N);else for(K=O.split(b$B),K.length===1?(O=5,T=Skw(e,N,O,T)):(P=O=6,T=Object.assign({Vc:32},T),T=new Q4(e,N,P,"_"+A_++,T)),w.push(T),P=e,d=0;d<K.length;d++)Y=K[d],
d%2===0?(F=g.i7("<html>"+Y+"</html>"),F.getElementsByTagName("parsererror").length?(J=F.createElement("span"),J.appendChild(F.createTextNode(Y))):J=F.firstChild,MsB(this,P,N-(P-e),O,T,d>0,J,k,w)):P=h$U(Y)+b}krR.lastIndex=0}}return w};
var Gr7=/^NOTE/,wQy=/(?:\r\n|\r|\n){2,}/,krR=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),b$B=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.Z(u8,g.c);u8.prototype.clear=function(){this.V&&this.V.dispose();this.V=null};
u8.prototype.reset=function(){this.V&&this.V.reset()};
u8.prototype.qB=function(){g.c.prototype.qB.call(this);this.clear()};var y4={windowColor:"#080808",windowOpacity:0,textAlign:2,Wc:7,iO:50,oE:100,isDefault:!0,FN:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.Z(jny,g.md);g.C=jny.prototype;g.C.qB=function(){if(this.D||this.jt){var q=this.j.Z0();q&&!q.t2()&&q.qk()}else qAw(this,!1);g.md.prototype.qB.call(this)};
g.C.ub=function(){return this.V7.T("html5_honor_caption_availabilities_in_audio_track")&&this.Y!=="LIVE"&&this.Y!=="SABR_LIVE"};
g.C.zR=function(){if(this.A2)return this.D||this.jt;var q=this.getAudioTrack();if(this.ub()){if(!q.captionTracks.length)return!1;if(!this.V)return!0}q=sby(q,g.Zg(this.V7));return q==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:q==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?t_(this):I9c(this)||t_(this)?!0:uRy(this)};
g.C.load=function(){g.md.prototype.load.call(this);this.J=this.getAudioTrack();if(this.V)this.U&&(this.h2.clear(),this.D?v$8(this,!0):this.player.getPresentingPlayerType()!==3&&this.V.xY(this.U,"json3",this.uF),this.D||this.jt||i8(this)||this.player.WN("captionschanged",g.XY(this.U)));else{var q;this.Y==="OFFLINE"?q=new fd(this.player,this.videoData,this.getAudioTrack()):this.Y==="SABR_LIVE"?q=new ID(this.videoData.V,this.player):this.Y==="LIVE"?q=new Pq(this.videoData.V,this.player):this.Y==="INNERTUBE"?
q=new g.xq(this.player,this.videoData,this.getAudioTrack()):q=new g.B1(this.player,this.videoData.M9,this.videoData.videoId,g.gRf(this.videoData),this.videoData.UM,this.videoData.eventId);this.V=q;g.p(this,this.V);this.V.Oi(this.uF)}};
g.C.unload=function(){this.D&&this.U?v$8(this,!1):(this.Tl&&g.zE(this.Tl),this.player.XC("captions"),this.EK=[],this.V&&this.V.YA(),this.h2.clear(),this.F9&&this.player.N9(this.F9),this.B6());g.md.prototype.unload.call(this);this.player.w9();this.player.WN("captionschanged",{})};
g.C.create=function(){this.zR()&&this.load();var q;a:{var a,w,G;if(this.V7.T("web_player_nitrate_promo_tooltip")&&((a=this.videoData.getPlayerResponse())==null?0:(w=a.captions)==null?0:(G=w.playerCaptionsTracklistRenderer)==null?0:G.enableTouchCaptionsNitrate)){var k,b;if(a=(q=this.videoData.getPlayerResponse())==null?void 0:(k=q.captions)==null?void 0:(b=k.playerCaptionsTracklistRenderer)==null?void 0:b.captionTracks)for(q=g.V(a),k=q.next();!k.done;k=q.next())if(k=k.value,k.kind==="asr"&&k.languageCode===
"en"){q=!0;break a}}q=!1}q&&this.j.publish("showpromotooltip",this.X.element)};
g.C.lM=function(){var q=sby(this.player.getAudioTrack(),g.Zg(this.V7));var a=q==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?zc(this,this.S):q==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&t_(this)?vq(this):I9c(this)||this.S||uRy(this)?zc(this,this.S):t_(this)?vq(this):null;if(this.D||this.jt){var w=g.Gg(this.V.U,!0);q=[];for(var G=0;G<w.length;G++){var k=w[G],b=g.dp("TRACK");b.setAttribute("kind","subtitles");b.setAttribute("label",g.UV(k));b.setAttribute("srclang",g.j6(k));b.setAttribute("id",k.toString());
this.jt||b.setAttribute("src",this.V.ea(k,"vtt"));k===a&&b.setAttribute("default","1");q.push(b)}a=this.j.Z0();a.HA(q);q=a.cq();this.VN&&this.f7.C(q.textTracks,"change",this.t4G)}else!this.U&&a&&RD(this,a),this.player.WN("onCaptionsTrackListChanged"),this.player.pu("onApiChange")};
g.C.t4G=function(){for(var q=this.j.Z0().cq().textTracks,a=null,w=0;w<q.length;w++)if(q[w].mode==="showing")a:{a=g.Gg(this.V.U,!0);for(var G=0;G<a.length;G++)if(a[G].toString()===q[w].id){a=a[G];break a}a=null}(this.loaded?this.U:null)!==a&&RD(this,a,!0)};
g.C.a8T=function(){!this.U&&this.D||this.unload()};
g.C.Hd=function(q,a,w,G){if(q){var k;z$U(this,(k=this.U)!=null?k:void 0);this.V.VR()&&(this.EK=[],this.j.XC("captions"),N1(this.L7),this.h2.reset());a:{k=this.h2;G=G||0;w=H3B(k,q,w||0);q=[];try{for(var b=g.V(w),O=b.next();!O.done;O=b.next()){var e=O.value,N=e.trackData,Y=e.vV,P=k.V7.T("safari_live_drm_captions_fix");if(typeof N!=="string"){w=q;var K=w.concat;if(P&&n$I(N))var d=coR(k,N,Y);else{var T=k,F=a,J=N,Q=Y,B=G;if(!FGV(J))throw Error("Invalid binary caption track data");T.V||(T.V=new XC(B,F));
d=T.V.W(J,Q)}var L=K.call(w,d)}else{if(N.substring(0,6)==="WEBVTT")var M=q.concat(coR(k,N,Y));else{w=q;var H=w.concat;b:{F=T=void 0;J=k;Q=a;if(N[0]==="{")try{J.V||(J.V=new h_(ple(Q)));var X=F=J.V.W(N,Y);break b}catch(a_){g.mQ(a_);X=[];break b}var D=g.i7(N);if(!D||!D.firstChild){var z=Error("Invalid caption track data");z.params=N;throw z;}if(D.firstChild.tagName==="timedtext"){if(Number(D.firstChild.getAttribute("format"))===3){J.V||(J.V=new xS(ple(Q),J.V7));X=T=J.V.W(D,Y);break b}var Oj=Error("Unsupported subtitles format in web player (Format2)");
Oj.params=N;throw Oj;}if(D.firstChild.tagName==="transcript"){var $l=Error("Unsupported subtitles format in web player (Format1)");$l.params=N;throw $l;}var ey=Error("Invalid caption track data");ey.params=N;throw ey;}M=H.call(w,X)}L=M}q=L}var Nm=q;break a}catch(a_){k.logger.V(187101178,"Captions parsing failed: "+a_.message+". ");k.clear();Nm=[];break a}Nm=void 0}a=Nm;a.length>0&&(Nm=this.U,this.h4(Nm,!!Nm,i8(this)?"g":this.S?"m":"s"));Nm=!this.V7.T("html5_keep_caption_data_after_seek")&&(this.Y===
"LIVE"||this.Y==="SABR_LIVE");this.player.N9(a,void 0,Nm);!this.S||this.jt||i8(this)||g.Nh(this.V7)||g.b0(this.V7)||g.BA(this.V7)||this.V7.f7==="shortspage"||this.player.isInline()||(g.zE(this.Tl),a=P6U({Wc:0,iO:5,oE:5,GH:2,textAlign:0,MM:0,lang:"en-GB"}),this.le=[a],Nm=["Click "," for settings"],this.BT||(b=new g.gC(g.EE()),g.p(this,b),this.BT=b.element),b=a.end-a.start,(O=g.UV(this.U))&&this.le.push(new J_(a.start,b,0,a.id,O)),this.le.push(new J_(a.start,b,0,a.id,Nm[0]),new J_(a.start,b,0,a.id,
this.BT,!0),new J_(a.start,b,0,a.id,Nm[1],!0)),this.player.N9(this.le),g.tD(this.Tl));!this.S||this.jt||i8(this)||(g.Zg(this.V7)?Wq(this,!0):DF(this,!0),this.J&&(this.J.Y=this.U),this.player.w9());this.S=!1}};
g.C.onCueRangeEnter=function(q){this.EK.push(q);N1(this.L7)};
g.C.onCueRangeExit=function(q){g.mU(this.EK,q);this.V instanceof Pq&&this.V.X&&this.player.kE([q]);N1(this.L7)};
g.C.getCaptionWindowContainerId=function(){return this.X.element.id};
g.C.toT=function(){yow(this,this.le);this.le=null};
g.C.qx=function(){var q=this;if(!this.OA||!this.D){this.L7.stop();g.fcK(this.St);this.EK.sort(g.j7);var a=this.EK;if(this.F9){var w=g.L$(a,function(b){return this.F9.indexOf(b)===-1},this);
w.length&&(a=w)}a=g.V(a);for(w=a.next();!w.done;w=a.next())WGl(this,w.value);a=g.V(Object.entries(this.y7));var G=a.next();for(w={};!G.done;w={UI:void 0,eH:void 0},G=a.next()){var k=g.V(G.value);G=k.next().value;k=k.next().value;w.UI=G;w.eH=k;this.St[w.UI]?(w.eH.element.parentNode||(w.eH instanceof oD||w.eH instanceof Hq||g.a6(this.y7,function(b){return function(O,e){e!==b.UI&&O.U.params.Wc===b.eH.U.params.Wc&&O.U.params.iO===b.eH.U.params.iO&&O.U.params.oE===b.eH.U.params.oE&&(O.dispose(),delete q.y7[e]);
return e===b.UI}}(w),this),this.X.element.appendChild(w.eH.element)),w.eH.T7(this.St[w.UI])):(w.eH.dispose(),delete this.y7[w.UI])}}};
g.C.nWT=function(){Xl6(this,{},!0);this.player.WN("captionssettingschanged")};
g.C.v9=function(){var q=y4.FN;q={background:q.background,backgroundOpacity:q.backgroundOpacity,charEdgeStyle:q.charEdgeStyle,color:q.color,fontFamily:q.fontFamily,fontSizeIncrement:q.fontSizeIncrement,fontStyle:q.bold&&q.italic?3:q.bold?1:q.italic?2:0,textOpacity:q.textOpacity,windowColor:y4.windowColor,windowOpacity:y4.windowOpacity};var a=AxK()||{};a.background!=null&&(q.background=a.background);a.backgroundOverride!=null&&(q.backgroundOverride=a.backgroundOverride);a.backgroundOpacity!=null&&(q.backgroundOpacity=
a.backgroundOpacity);a.backgroundOpacityOverride!=null&&(q.backgroundOpacityOverride=a.backgroundOpacityOverride);a.charEdgeStyle!=null&&(q.charEdgeStyle=a.charEdgeStyle);a.charEdgeStyleOverride!=null&&(q.charEdgeStyleOverride=a.charEdgeStyleOverride);a.color!=null&&(q.color=a.color);a.colorOverride!=null&&(q.colorOverride=a.colorOverride);a.fontFamily!=null&&(q.fontFamily=a.fontFamily);a.fontFamilyOverride!=null&&(q.fontFamilyOverride=a.fontFamilyOverride);a.fontSizeIncrement!=null&&(q.fontSizeIncrement=
a.fontSizeIncrement);a.fontSizeIncrementOverride!=null&&(q.fontSizeIncrementOverride=a.fontSizeIncrementOverride);a.fontStyle!=null&&(q.fontStyle=a.fontStyle);a.fontStyleOverride!=null&&(q.fontStyleOverride=a.fontStyleOverride);a.textOpacity!=null&&(q.textOpacity=a.textOpacity);a.textOpacityOverride!=null&&(q.textOpacityOverride=a.textOpacityOverride);a.windowColor!=null&&(q.windowColor=a.windowColor);a.windowColorOverride!=null&&(q.windowColorOverride=a.windowColorOverride);a.windowOpacity!=null&&
(q.windowOpacity=a.windowOpacity);a.windowOpacityOverride!=null&&(q.windowOpacityOverride=a.windowOpacityOverride);return q};
g.C.jC=function(q,a){var w={};Object.assign(w,AxK());Object.assign(w,q);Xl6(this,w,a);this.player.WN("captionssettingschanged")};
g.C.B6=function(){!this.D&&this.loaded&&(g.yx(this.y7,function(q,a){q.dispose();delete this.y7[a]},this),this.qx())};
g.C.KW=function(q,a){switch(q){case "fontSize":if(isNaN(a))break;q=g.X1(a,-2,4);this.jC({fontSizeIncrement:q});return q;case "reload":a&&!this.D&&RD(this,this.U,!0);break;case "stickyLoading":a!==void 0&&this.V7.S&&(g.Zg(this.V7)?Wq(this,!!a):DF(this,!!a));break;case "track":return R$B(this,a);case "tracklist":return this.V?g.sd(g.Gg(this.V.U,!(!a||!a.includeAsr)),function(w){return g.XY(w)}):[];
case "translationLanguages":return this.V?this.V.D.map(function(w){return Object.assign({},w)}):[];
case "sampleSubtitles":this.D||a===void 0||qAw(this,!!a);break;case "sampleSubtitlesCustomized":this.D||qAw(this,!!a,a);break;case "recommendedTranslationLanguages":return g.Cx();case "defaultTranslationSourceTrackIndices":return this.V?this.V.S:[]}};
g.C.getOptions=function(){var q="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.V7.S&&q.push("stickyLoading");return q};
g.C.Eb=function(){var q=this.U;if(this.j.K6("captions")){if(this.V7.T("html5_modify_caption_vss_logging")){var a;return(q=(a=this.videoData.zW)!=null?a:null)?{cc:g.EZV(q)}:{}}if(q)return a=q.vssId,q.translationLanguage&&a&&(a="t"+a+"."+g.j6(q)),{cc:a}}return{}};
g.C.PtQ=function(){this.isSubtitlesOn()?(g.Zg(this.V7)?Wq(this,!1):DF(this,!1),z$U(this),RD(this,null,!0)):this.xr()};
g.C.xr=function(){var q=i8(this)||!this.U?zc(this,!0):this.U;q&&this.Pm(q.vssId,"m");this.isSubtitlesOn()||RD(this,i8(this)||!this.U?zc(this,!0):this.U,!0)};
g.C.isSubtitlesOn=function(){return!!this.loaded&&!!this.U&&!i8(this)};
g.C.zGT=function(){var q=i8(this);t_(this,q)?RD(this,this.getAudioTrack().V,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.ub()&&(this.S=!1,this.U=null,this.V&&(this.V.dispose(),this.V=null)),this.zR()&&(q?RD(this,zc(this,!1),!1):this.load()))};
g.C.gb=function(q){q&&(this.UK={top:q.top,right:q.right,bottom:q.bottom,left:q.left,width:1-q.left-q.right,height:1-q.top-q.bottom},this.X.element.style.top=this.UK.top*100+"%",this.X.element.style.left=this.UK.left*100+"%",this.X.element.style.width=this.UK.width*100+"%",this.X.element.style.height=this.UK.height*100+"%",this.X.element.style.position="absolute",q=DrR(this))&&(this.X.element.style.width=q.width+"px",this.X.element.style.height=q.height+"px")};
g.C.onVideoDataChange=function(q,a){q==="newdata"&&(this.videoData=a,this.loaded&&this.unload(),this.S=!1,this.U=null,this.V&&(this.V.dispose(),this.V=null,this.player.WN("captionschanged",{})),this.zR()&&this.load())};
g.C.getAudioTrack=function(){return this.player.getAudioTrack()};
g.C.nlh=function(){var q=this.j.Z0();q&&!q.t2()&&q.qk();this.j.isFullscreen()?(this.D=this.A2=!0,this.loaded&&this.lM()):(this.A2=this.V7.controlsType==="3",this.D=Ur6(this));RD(this,this.U)};
g.C.V3=function(){var q,a,w,G=(q=this.videoData.getPlayerResponse())==null?void 0:(a=q.captions)==null?void 0:(w=a.playerCaptionsTracklistRenderer)==null?void 0:w.openTranscriptCommand;G&&this.player.zl("innertubeCommand",G)};
g.C.h4=function(q,a,w){var G=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,k="";q&&(k=q.vssId,k=k.replace(G,""));var b="";q&&q.getId()&&(b=q.getId()||"");q&&q.getXtags()&&(q=q.getXtags(),q=q.replace(G,""),b=b.concat(";"+q));this.j.h4(a?k:"",a?b:"",w)};
g.C.Pm=function(q,a){q=(q||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");q.length>0&&this.j.Pm(q,a)};g.Jq("captions",jny);})(_yt_player);
