(function(g){var window=this;'use strict';var nYB=function(q){q.publish("autonavvisibility")},MkI=function(q,a){q.zl("onAutonavCoundownStarted",a)},hUe=function(q){var a,w,G;
return q==null?void 0:(a=q.playerOverlays)==null?void 0:(w=a.playerOverlayRenderer)==null?void 0:(G=w.autoplay)==null?void 0:G.playerOverlayAutoplayRenderer},OG=function(q){var a=q.B(),w=a.Y;
g.u.call(this,{G:"a",N:"ytp-autonav-suggestion-card",Z:{href:"{{url}}",target:w?a.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},K:[{G:"div",vT:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Z:{style:"{{background}}"},K:[{G:"div",Z:{"aria-label":"{{timestamp}}"},vT:["ytp-autonav-timestamp"],ue:"{{duration}}"},{G:"div",vT:["ytp-autonav-live-stamp"],ue:"Live"},{G:"div",
vT:["ytp-autonav-upcoming-stamp"],ue:"Upcoming"},{G:"div",N:"ytp-autonav-list-overlay",K:[{G:"div",N:"ytp-autonav-mix-text",ue:"Mix"},{G:"div",N:"ytp-autonav-mix-icon"}]}]},{G:"div",vT:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ue:"{{title}}"},{G:"div",vT:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ue:"{{author}}"},{G:"div",vT:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ue:"{{views_and_publish_time}}"}]});this.j=q;this.suggestion=
null;this.V=w;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},lS=function(q,a){a=a===void 0?!1:a;
g.u.call(this,{G:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var w=this;this.X=a;this.cancelCommand=this.L=void 0;this.W=0;this.container=new g.u({G:"div",N:"ytp-autonav-endscreen-countdown-container"});g.p(this,this.container);this.container.HT(this.element);a=q.B();var G=a.Y;this.j=q;this.suggestion=null;this.onVideoDataChange("newdata",this.j.getVideoData());this.C(q,"videodatachange",this.onVideoDataChange);this.V=new g.u({G:"div",N:"ytp-autonav-endscreen-upnext-container",Z:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},K:[{G:"div",N:"ytp-autonav-endscreen-upnext-header"},{G:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",ue:"{{autoplayAlternativeHeader}}"},{G:"a",N:"ytp-autonav-endscreen-link-container",Z:{href:"{{url}}",target:G?a.J:""},K:[{G:"div",N:"ytp-autonav-endscreen-upnext-thumbnail",Z:{style:"{{background}}"},K:[{G:"div",Z:{"aria-label":"{{timestamp}}"},vT:["ytp-autonav-timestamp"],
ue:"{{duration}}"},{G:"div",vT:["ytp-autonav-live-stamp"],ue:"Live"},{G:"div",vT:["ytp-autonav-upcoming-stamp"],ue:"Upcoming"}]},{G:"div",N:"ytp-autonav-endscreen-video-info",K:[{G:"div",N:"ytp-autonav-endscreen-premium-badge"},{G:"div",N:"ytp-autonav-endscreen-upnext-title",ue:"{{title}}"},{G:"div",N:"ytp-autonav-endscreen-upnext-author",ue:"{{author}}"},{G:"div",N:"ytp-autonav-view-and-date",ue:"{{views_and_publish_time}}"},{G:"div",N:"ytp-autonav-author-and-view",ue:"{{author_and_views}}"}]}]}]});
g.p(this,this.V);this.V.HT(this.container.element);G||this.C(this.V.oW("ytp-autonav-endscreen-link-container"),"click",this.kz);this.j.createClientVe(this.container.element,this,115127);this.j.createClientVe(this.V.oW("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.u({G:"div",N:"ytp-autonav-overlay"});g.p(this,this.overlay);this.overlay.HT(this.container.element);this.U=new g.u({G:"div",N:"ytp-autonav-endscreen-button-container"});g.p(this,this.U);this.U.HT(this.container.element);
this.cancelButton=new g.u({G:"button",vT:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",a.T("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{"aria-label":"Cancel auto-play"},ue:"Cancel"});g.p(this,this.cancelButton);this.cancelButton.HT(this.U.element);this.cancelButton.listen("click",this.n8,this);this.j.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.u({G:"a",vT:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
a.T("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{href:"{{url}}",role:"button","aria-label":"Play next video"},ue:"Play now"});g.p(this,this.playButton);this.playButton.HT(this.U.element);this.playButton.listen("click",this.kz,this);this.j.createServerVe(this.playButton.element,this.playButton,!0);(a=this.j.getVideoData())&&SA7(this,a);this.Y=new g.o1(function(){fOc(w)},500);
g.p(this,this.Y);this.gL();this.C(q,"autonavvisibility",this.gL);this.j.T("web_autonav_color_transition")&&(this.C(q,"autonavchange",this.Xg),this.C(q,"onAutonavCoundownStarted",this.Z7t))},eJ=function(q){var a=q.j.f3(!0,q.j.isFullscreen());
g.kX(q.container.element,"ytp-autonav-endscreen-small-mode",q.Ev(a));g.kX(q.container.element,"ytp-autonav-endscreen-is-premium",!!q.suggestion&&!!q.suggestion.y$7);g.kX(q.j.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!q.j.YW());g.kX(q.j.getRootNode(),"countdown-running",q.HW());g.kX(q.container.element,"ytp-player-content",q.j.YW());g.IR(q.overlay.element,{width:a.width+"px"});if(!q.HW()){q.j.YW()?H$8(q,Math.round(ckx(q)/1E3)):H$8(q);a=!!q.suggestion&&!!q.suggestion.mf;var w=q.j.YW()||
!a;g.kX(q.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!w&&a);g.kX(q.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",w&&!a);q.U.Ji(q.j.YW());g.kX(q.element,"ytp-enable-w2w-color-transitions",pQx(q))}},fOc=function(q){var a=ckx(q),w=Math,G=w.min;
var k=q.W?Date.now()-q.W:0;w=G.call(w,k,a);H$8(q,Math.ceil((a-w)/1E3));a-w<=500&&q.HW()?q.select(!0):q.HW()&&q.Y.start()},ckx=function(q){if(q.j.isFullscreen()){var a;
q=(a=q.j.getVideoData())==null?void 0:a.Yb;return q===-1||q===void 0?8E3:q}return q.j.Rx()>=0?q.j.Rx():g.Wo(q.j.B().experiments,"autoplay_time")||1E4},SA7=function(q,a){a=a.getWatchNextResponse();
var w,G;a=(w=hUe(a))==null?void 0:(G=w.nextButton)==null?void 0:G.buttonRenderer;q.L=a==null?void 0:a.navigationEndpoint;w=a==null?void 0:a.trackingParams;q.playButton&&w&&q.j.setTrackingParams(q.playButton.element,w)},pQx=function(q){var a;
return!((a=q.j.getVideoData())==null||!a.watchToWatchTransitionRenderer)},H$8=function(q,a){a=a===void 0?-1:a;
q=q.V.oW("ytp-autonav-endscreen-upnext-header");g.sN(q);if(a>=0){a=String(a);var w="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],G="Up next in $SECONDS".indexOf(w);if(G>=0){q.appendChild(g.TY("Up next in $SECONDS".slice(0,G)));var k=g.dp("span");g.yO(k,"ytp-autonav-endscreen-upnext-header-countdown-number");g.EN(k,a);q.appendChild(k);q.appendChild(g.TY("Up next in $SECONDS".slice(G+w.length)));return}}g.EN(q,"Up next")},N3=function(q,a){g.u.call(this,{G:"div",
vT:["html5-endscreen","ytp-player-content",a||"base-endscreen"]});this.created=!1;this.player=q},Ya=function(q){g.u.call(this,{G:"div",
vT:["ytp-upnext","ytp-player-content"],Z:{"aria-label":"{{aria_label}}"},K:[{G:"div",N:"ytp-cued-thumbnail-overlay-image",Z:{style:"{{background}}"}},{G:"span",N:"ytp-upnext-top",K:[{G:"span",N:"ytp-upnext-header",ue:"Up Next"},{G:"span",N:"ytp-upnext-title",ue:"{{title}}"},{G:"span",N:"ytp-upnext-author",ue:"{{author}}"}]},{G:"a",N:"ytp-upnext-autoplay-icon",Z:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{G:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
K:[{G:"circle",N:"ytp-svg-autoplay-circle",Z:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",N:"ytp-svg-autoplay-ring",Z:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",N:"ytp-svg-fill",Z:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",N:"ytp-upnext-bottom",K:[{G:"span",N:"ytp-upnext-cancel"},{G:"span",N:"ytp-upnext-paused",
ue:"Auto-play is paused"}]}]});this.api=q;this.cancelButton=null;this.L=this.oW("ytp-svg-autoplay-ring");this.W=this.notification=this.V=this.suggestion=null;this.Y=new g.o1(this.QS,5E3,this);this.U=0;var a=this.oW("ytp-upnext-cancel");this.cancelButton=new g.u({G:"button",vT:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:"0","aria-label":"Cancel auto-play"},ue:"Cancel"});g.p(this,this.cancelButton);this.cancelButton.listen("click",this.M8,this);this.cancelButton.HT(a);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.p(this,this.Y);this.api.createClientVe(this.element,this,18788);a=this.oW("ytp-upnext-autoplay-icon");this.C(a,"click",this.N8);this.api.createClientVe(a,this,115130);this.bd();this.C(q,"autonavvisibility",this.bd);this.C(q,"mdxnowautoplaying",this.MiB);this.C(q,"mdxautoplaycanceled",this.N$K);g.kX(this.element,"ytp-upnext-mobile",this.api.B().U)},UQe=function(q,a){if(a)return a;
if(q.api.isFullscreen()){var w;q=(w=q.api.getVideoData())==null?void 0:w.Yb;return q===-1||q===void 0?8E3:q}return q.api.Rx()>=0?q.api.Rx():g.Wo(q.api.B().experiments,"autoplay_time")||1E4},XQV=function(q,a){a=UQe(q,a);
var w=Math,G=w.min;var k=(0,g.Zj)()-q.U;w=G.call(w,k,a);a=a===0?1:Math.min(w/a,1);q.L.setAttribute("stroke-dashoffset",""+-211*(a+1));a>=1&&q.HW()&&q.api.getPresentingPlayerType()!==3?q.select(!0):q.HW()&&q.V.start()},Pu=function(q){N3.call(this,q,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.u({G:"div",N:"ytp-suggestion-panel",K:[{G:"div",vT:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ue:"More videos"}]});this.S=new g.u({G:"div",N:"ytp-suggestions-container"});this.videos=[];this.W=null;this.L=this.X=!1;this.U=new lS(this.player);g.p(this,this.U);this.U.HT(this.element);q.getVideoData().h8?this.V=this.U:(this.V=new Ya(q),g.DZ(this.player,this.V.element,4),g.p(this,this.V));this.overlay=new g.u({G:"div",
N:"ytp-autonav-overlay-cancelled-state"});g.p(this,this.overlay);this.overlay.HT(this.element);this.Y=new g.Ee(this);g.p(this,this.Y);g.p(this,this.table);this.table.HT(this.element);this.table.show();g.p(this,this.S);this.S.HT(this.table.element);this.hide()},Ku=function(q){var a=q.YW();
a!==q.L&&(q.L=a,nYB(q.player),q.L?(q.U!==q.V&&q.U.hide(),q.table.hide()):(q.U!==q.V&&q.U.show(),q.table.show()))},jdV=function(q){N3.call(this,q,"videowall-endscreen");
var a=this;this.j=q;this.stills=[];this.W=this.videoData=null;this.Y=this.X=!1;this.S=null;g.gU(this.element,"modern-videowall-endscreen");this.U=new g.Ee(this);g.p(this,this.U);this.L=new g.o1(function(){g.gU(a.element,"ytp-show-tiles")},0);
g.p(this,this.L);this.table=new g.gC({G:"div",N:"ytp-modern-endscreen-content"});g.p(this,this.table);this.table.HT(this.element);q.getVideoData().h8?this.V=new lS(q,!0):this.V=new Ya(q);g.p(this,this.V);g.DZ(this.player,this.V.element,4);q.createClientVe(this.element,this,158789);this.hide()},ds=function(q){return g.R$(q.player)&&q.Ao()&&!q.W},Tq=function(q){var a=q.YW();
a!==q.X&&(q.X=a,nYB(q.player))},oYI=function(q){N3.call(this,q,"subscribecard-endscreen");
this.V=new g.u({G:"div",N:"ytp-subscribe-card",K:[{G:"img",N:"ytp-author-image",Z:{src:"{{profilePicture}}"}},{G:"div",N:"ytp-subscribe-card-right",K:[{G:"div",N:"ytp-author-name",ue:"{{author}}"},{G:"div",N:"html5-subscribe-button-container"}]}]});g.p(this,this.V);this.V.HT(this.element);var a=q.getVideoData();this.subscribeButton=new g.wm("Subscribe",null,"Unsubscribe",null,!0,!1,a.Am,a.subscribed,"trailer-endscreen",null,q,!1);g.p(this,this.subscribeButton);this.subscribeButton.HT(this.V.oW("html5-subscribe-button-container"));
this.C(q,"videodatachange",this.NB);this.NB();this.hide()},$a=function(q){var a=q.B(),w=g.se||g.Du?{style:"will-change: opacity"}:void 0,G=a.Y,k=["ytp-videowall-still"];
a.U&&k.push("ytp-videowall-show-text");g.u.call(this,{G:"a",vT:k,Z:{href:"{{url}}",target:G?a.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{G:"div",N:"ytp-videowall-still-image",Z:{style:"{{background}}"}},{G:"span",N:"ytp-videowall-still-info",Z:{"aria-hidden":"true"},K:[{G:"span",N:"ytp-videowall-still-info-bg",K:[{G:"span",N:"ytp-videowall-still-info-content",Z:w,K:[{G:"span",N:"ytp-videowall-still-info-title",ue:"{{title}}"},
{G:"span",N:"ytp-videowall-still-info-author",ue:"{{author_and_views}}"},{G:"span",N:"ytp-videowall-still-info-live",ue:"Live"},{G:"span",N:"ytp-videowall-still-info-duration",ue:"{{duration}}"}]}]}]},{G:"span",vT:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},K:[{G:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",N:"ytp-videowall-still-listlabel-length",K:[" (",{G:"span",ue:"{{playlist_length}}"},")"]}]},{G:"span",vT:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},K:[{G:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",N:"ytp-videowall-still-listlabel-length",ue:" (50+)"}]}]});this.suggestion=null;this.U=G;this.api=q;this.V=new g.Ee(this);g.p(this,this.V);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.V.C(q,"videodatachange",this.onVideoDataChange);q.createServerVe(this.element,this);this.onVideoDataChange()},sG=function(q){N3.call(this,q,"videowall-endscreen");
var a=this;this.j=q;this.W=0;this.stills=[];this.Y=this.videoData=null;this.L=this.S=!1;this.J=null;this.U=new g.Ee(this);g.p(this,this.U);this.X=new g.o1(function(){g.gU(a.element,"ytp-show-tiles")},0);
g.p(this,this.X);var w=new g.u({G:"button",vT:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":"Previous"},K:[g.Nl()]});g.p(this,w);w.HT(this.element);w.listen("click",this.C8,this);this.table=new g.gC({G:"div",N:"ytp-endscreen-content"});g.p(this,this.table);this.table.HT(this.element);w=new g.u({G:"button",vT:["ytp-button","ytp-endscreen-next"],Z:{"aria-label":"Next"},K:[g.Yp()]});g.p(this,w);w.HT(this.element);w.listen("click",this.xu,this);q.getVideoData().h8?this.V=new lS(q,!0):this.V=
new Ya(q);g.p(this,this.V);g.DZ(this.player,this.V.element,4);q.createClientVe(this.element,this,158789);this.hide()},Fn=function(q){return g.R$(q.player)&&q.Ao()&&!q.Y},Cu=function(q){var a=q.YW();
a!==q.S&&(q.S=a,nYB(q.player))},IO6=function(q,a){g.u.call(this,{G:"button",
vT:["ytp-watch-on-youtube-button","ytp-button"],ue:"{{content}}"});this.j=q;this.buttonType=this.buttonType=a;this.rS();this.buttonType===2&&g.gU(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.rS);this.Ji(!0)},Zr=function(q){N3.call(this,q,"watch-again-on-youtube-endscreen");
this.watchButton=new IO6(q,1);g.p(this,this.watchButton);this.watchButton.HT(this.element);g.LUy(q)&&(this.V=new g.Dy(q),g.p(this,this.V),this.U=new g.u({G:"div",vT:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Z:{tabIndex:"-1"},K:[this.V]}),g.p(this,this.U),this.V.HT(this.U.element),this.U.HT(this.element));q.createClientVe(this.element,this,156914);this.hide()},zU8=function(q){g.md.call(this,q);
var a=this;this.endScreen=null;this.V=this.U=this.W=!1;this.listeners=new g.Ee(this);g.p(this,this.listeners);var w=q.B();q.isEmbedsShortsMode()?this.endScreen=new Zr(q):uwI(q)?(this.W=!0,tk7(this),this.V?this.endScreen=new Pu(q):w.T("delhi_modern_endscreen")?this.endScreen=new jdV(q):this.endScreen=new sG(q)):w.Ku?this.endScreen=new oYI(q):this.endScreen=new N3(q);g.p(this,this.endScreen);g.DZ(q,this.endScreen.element,4);vYx(this);this.listeners.C(q,"videodatachange",this.onVideoDataChange,this);
this.listeners.C(q,g.oM("endscreen"),function(G){a.onCueRangeEnter(G)});
this.listeners.C(q,g.IM("endscreen"),function(G){a.onCueRangeExit(G)})},tk7=function(q){var a=q.player.getVideoData();
if(!a||q.V===a.BW&&q.U===a.h8)return!1;q.V=a.BW;q.U=a.h8;return!0},uwI=function(q){q=q.B();
return q.h8&&!q.Ku&&!q.disableOrganicUi},vYx=function(q){q.player.XC("endscreen");
var a=q.player.getVideoData();a=new g.Xo(Math.max((a.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var w=new g.Xo(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});q.player.N9([a,w])};
g.o$.prototype.Rx=g.kl(6,function(){return this.app.Rx()});
g.Tb.prototype.Rx=g.kl(5,function(){return this.getVideoData().T9});
g.pD.prototype.tW=g.kl(4,function(q){this.Gg().tW(q)});
g.W1.prototype.tW=g.kl(3,function(q){this.x8!==q&&(this.x8=q,this.BM())});
g.Z(OG,g.u);OG.prototype.select=function(){this.j.Fj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.L$||void 0)&&this.j.logClick(this.element)};
OG.prototype.onClick=function(q){g.J0(q,this.j,this.V,this.suggestion.sessionData||void 0)&&this.select()};
OG.prototype.onKeyPress=function(q){switch(q.keyCode){case 13:case 32:q.defaultPrevented||(this.select(),q.preventDefault())}};g.Z(lS,g.u);g.C=lS.prototype;g.C.vr=function(q){this.suggestion!==q&&(this.suggestion=q,g.Ng(this.V,q),this.playButton.updateValue("url",this.suggestion.La()),eJ(this))};
g.C.HW=function(){return this.W>0};
g.C.Pd=function(){this.HW()||(this.W=Date.now(),fOc(this),MkI(this.j,ckx(this)),g.kX(this.j.getRootNode(),"countdown-running",this.HW()))};
g.C.iR=function(){this.q5();fOc(this);var q=this.V.oW("ytp-autonav-endscreen-upnext-header");q&&g.EN(q,"Up next")};
g.C.q5=function(){this.HW()&&(this.Y.stop(),this.W=0)};
g.C.select=function(q){this.j.nextVideo(!1,q===void 0?!1:q);this.q5()};
g.C.kz=function(q){g.J0(q,this.j)&&(q.currentTarget===this.playButton.element?this.j.logClick(this.playButton.element):q.currentTarget===this.V.oW("ytp-autonav-endscreen-link-container")&&(q=this.V.oW("ytp-autonav-endscreen-link-container"),this.j.logVisibility(q,!0),this.j.logClick(q)),this.L?(this.j.zl("innertubeCommand",this.L),this.q5()):this.select())};
g.C.n8=function(){this.j.logClick(this.cancelButton.element);g.ui(this.j,!0);this.cancelCommand&&this.j.zl("innertubeCommand",this.cancelCommand)};
g.C.onVideoDataChange=function(q,a){SA7(this,a);q=a.getWatchNextResponse();var w,G;q=(w=hUe(q))==null?void 0:(G=w.cancelButton)==null?void 0:G.buttonRenderer;this.cancelCommand=q==null?void 0:q.command};
g.C.Z7t=function(q){if(pQx(this)){var a=this.j.getVideoData().watchToWatchTransitionRenderer,w=a==null?void 0:a.fromColorPaletteDark;a=a==null?void 0:a.toColorPaletteDark;if(w&&a){var G=this.element;G.style.setProperty("--w2w-start-background-color",g.rQ(w.surgeColor));G.style.setProperty("--w2w-start-primary-text-color",g.rQ(w.primaryTitleColor));G.style.setProperty("--w2w-start-secondary-text-color",g.rQ(w.secondaryTitleColor));G.style.setProperty("--w2w-end-background-color",g.rQ(a.surgeColor));
G.style.setProperty("--w2w-end-primary-text-color",g.rQ(a.primaryTitleColor));G.style.setProperty("--w2w-end-secondary-text-color",g.rQ(a.secondaryTitleColor));G.style.setProperty("--w2w-animation-duration",q+"ms")}g.kX(this.element,"ytp-w2w-animate",!0)}};
g.C.Xg=function(q){this.j.T("web_autonav_color_transition")&&q!==2&&g.kX(this.element,"ytp-w2w-animate",!1)};
g.C.gL=function(){var q=this.j.YW();this.X&&this.Fw!==q&&this.Ji(q);eJ(this);this.j.logVisibility(this.container.element,q);this.j.logVisibility(this.cancelButton.element,q);this.j.logVisibility(this.V.oW("ytp-autonav-endscreen-link-container"),q);this.j.logVisibility(this.playButton.element,q)};
g.C.Ev=function(q){return q.width<400||q.height<459};g.Z(N3,g.u);g.C=N3.prototype;g.C.create=function(){this.created=!0};
g.C.destroy=function(){this.created=!1};
g.C.Ao=function(){return!1};
g.C.YW=function(){return!1};
g.C.WG=function(){return!1};g.Z(Ya,g.u);g.C=Ya.prototype;g.C.QS=function(){this.notification&&(this.Y.stop(),this.v5(this.W),this.W=null,this.notification.close(),this.notification=null)};
g.C.vr=function(q){this.suggestion=q;g.Ng(this,q,"hqdefault.jpg")};
g.C.bd=function(){this.Ji(this.api.YW());this.api.logVisibility(this.element,this.api.YW());this.api.logVisibility(this.oW("ytp-upnext-autoplay-icon"),this.api.YW());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.YW())};
g.C.PF9=function(){window.focus();this.QS()};
g.C.Pd=function(q){var a=this;this.HW()||(g.D2("a11y-announce","Up Next "+this.suggestion.title),this.U=(0,g.Zj)(),this.V=new g.o1(function(){XQV(a,q)},25),XQV(this,q),MkI(this.api,UQe(this,q)));
g.wU(this.element,"ytp-upnext-autoplay-paused")};
g.C.hide=function(){g.u.prototype.hide.call(this)};
g.C.HW=function(){return!!this.V};
g.C.iR=function(){this.q5();this.U=(0,g.Zj)();XQV(this);g.gU(this.element,"ytp-upnext-autoplay-paused")};
g.C.q5=function(){this.HW()&&(this.V.dispose(),this.V=null)};
g.C.select=function(q){q=q===void 0?!1:q;if(this.api.B().T("autonav_notifications")&&q&&window.Notification&&typeof document.hasFocus==="function"){var a=Notification.permission;a==="default"?Notification.requestPermission():a!=="granted"||document.hasFocus()||(this.QS(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Wm()}),this.W=this.C(this.notification,"click",this.PF9),this.Y.start())}this.q5();this.api.nextVideo(!1,q)};
g.C.N8=function(q){!g.ZM(this.cancelButton.element,q.target)&&g.J0(q,this.api)&&(this.api.YW()&&this.api.logClick(this.oW("ytp-upnext-autoplay-icon")),this.select())};
g.C.M8=function(){this.api.YW()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.ui(this.api,!0)};
g.C.MiB=function(q){this.api.getPresentingPlayerType();this.show();this.Pd(q)};
g.C.N$K=function(){this.api.getPresentingPlayerType();this.q5();this.hide()};
g.C.qB=function(){this.q5();this.QS();g.u.prototype.qB.call(this)};g.Z(Pu,N3);g.C=Pu.prototype;g.C.create=function(){N3.prototype.create.call(this);this.Y.C(this.player,"appresize",this.i8);this.Y.C(this.player,"onVideoAreaChange",this.i8);this.Y.C(this.player,"videodatachange",this.onVideoDataChange);this.Y.C(this.player,"autonavchange",this.hv);this.Y.C(this.player,"onAutonavCancelled",this.wX);this.onVideoDataChange()};
g.C.show=function(){N3.prototype.show.call(this);(this.X||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.ui(this.player,!1);g.R$(this.player)&&this.Ao()&&!this.W?(Ku(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.V.select(!0):this.V.Pd():this.videoData.autonavState===3&&this.V.iR()):(g.ui(this.player,!0),Ku(this));this.i8()};
g.C.hide=function(){N3.prototype.hide.call(this);this.V.iR();Ku(this)};
g.C.i8=function(){var q=this.player.f3(!0,this.player.isFullscreen());Ku(this);eJ(this.U);g.kX(this.element,"ytp-autonav-cancelled-small-mode",this.Ev(q));g.kX(this.element,"ytp-autonav-cancelled-tiny-mode",this.SK(q));g.kX(this.element,"ytp-autonav-cancelled-mini-mode",q.width<=400||q.height<=360);this.overlay&&g.IR(this.overlay.element,{width:q.width+"px"});if(!this.L)for(q=0;q<this.videos.length;q++)g.kX(this.videos[q].element,"ytp-suggestion-card-with-margin",q%2===1)};
g.C.onVideoDataChange=function(){var q=this.player.getVideoData();if(this.videoData!==q&&q){this.videoData=q;if((q=this.videoData.suggestions)&&q.length||this.player.T("web_player_autonav_empty_suggestions_fix")){var a=g.Vq(this.videoData);a&&(this.V.vr(a),this.V!==this.U&&this.U.vr(a))}if(q&&q.length)for(a=0;a<i$U.length;++a){var w=i$U[a];if(q&&q[w]){this.videos[a]=new OG(this.player);var G=this.videos[a];w=q[w];G.suggestion!==w&&(G.suggestion=w,g.Ng(G,w));g.p(this,this.videos[a]);this.videos[a].HT(this.S.element)}}this.i8()}};
g.C.hv=function(q){q===1?(this.X=!1,this.W=this.videoData.clientPlaybackNonce,this.V.q5(),this.Fw&&this.i8()):(this.X=!0,this.YW()&&(q===2?this.V.Pd():q===3&&this.V.iR()))};
g.C.wX=function(q){q?this.hv(1):(this.W=null,this.X=!1)};
g.C.Ao=function(){return this.videoData.autonavState!==1};
g.C.Ev=function(q){return(q.width<910||q.height<459)&&!this.SK(q)&&!(q.width<=400||q.height<=360)};
g.C.SK=function(q){return q.width<800&&!(q.width<=400||q.height<=360)};
g.C.YW=function(){return this.Fw&&g.R$(this.player)&&this.Ao()&&!this.W};
var i$U=[1,3,2,4];g.Z(jdV,N3);g.C=jdV.prototype;g.C.create=function(){N3.prototype.create.call(this);var q=this.player.getVideoData();q&&(this.videoData=q);this.W1();this.U.C(this.player,"appresize",this.W1);this.U.C(this.player,"onVideoAreaChange",this.W1);this.U.C(this.player,"videodatachange",this.onVideoDataChange);this.U.C(this.player,"autonavchange",this.Fs);this.U.C(this.player,"onAutonavCancelled",this.gX);q=this.videoData.autonavState;q!==this.S&&this.Fs(q);this.U.C(this.element,"transitionend",this.hY)};
g.C.destroy=function(){g.JE(this.U);g.Gr(this.stills);this.stills=[];N3.prototype.destroy.call(this);g.wU(this.element,"ytp-show-tiles");this.L.stop();this.S=this.videoData.autonavState};
g.C.Ao=function(){return this.videoData.autonavState!==1};
g.C.show=function(){var q=this.Fw;N3.prototype.show.call(this);g.wU(this.element,"ytp-show-tiles");this.player.B().U?g.vv(this.L):this.L.start();(this.Y||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.ui(this.player,!1);ds(this)?(Tq(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.V.select(!0):this.V.Pd():this.videoData.autonavState===3&&this.V.iR()):(g.ui(this.player,!0),Tq(this));q!==this.Fw&&this.player.logVisibility(this.element,!0)};
g.C.hide=function(){var q=this.Fw;N3.prototype.hide.call(this);this.V.iR();Tq(this);q!==this.Fw&&this.player.logVisibility(this.element,!1)};
g.C.hY=function(q){q.target===this.element&&this.W1()};
g.C.W1=function(){var q,a,w,G;var k=((q=this.videoData)==null?0:(a=q.suggestions)==null?0:a.length)?(w=this.videoData)==null?void 0:w.suggestions:[(G=this.videoData)==null?void 0:g.Vq(G)];if(k.length){a=this.j.f3(!0,this.j.isFullscreen());q=Math.floor((a.width-64+16)/(g.X1(a.width*.27,250,450)+16));a=Math.min(3,Math.floor((a.height-64)/((a.width-64-(q-1)*16)/q*.5625+70)));g.GM(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.gU(this.element,"ytp-modern-endscreen-limit-rows-"+a);g.kX(this.element,"ytp-modern-endscreen-single-item",q===1);g.kX(this.element,"ytp-modern-endscreen-row-0",a===0);q=this.table.element;q.ariaLive="polite";this.V.vr(g.Vq(this.videoData));this.V instanceof lS&&eJ(this.V);g.kX(this.element,"ytp-endscreen-takeover",ds(this));Tq(this);a=0;q.ariaBusy="true";w=k.length;for(G=0;G<w;G++){var b=G%w,O=this.stills[G];O||(O=new g.Yq(this.player),this.stills[G]=O,q.appendChild(O.element));g.BOc(O,k[b]);a++}this.stills.length=
a}};
g.C.onVideoDataChange=function(){var q=this.player.getVideoData(1);this.videoData!==q&&(q!=null&&g.Vq(q)?(this.videoData=q,this.W1()):this.player.d8("missg",{vid:(q==null?void 0:q.videoId)||"",cpn:(q==null?void 0:q.clientPlaybackNonce)||""}))};
g.C.WG=function(){return this.V.HW()};
g.C.Fs=function(q){q===1?(this.Y=!1,this.W=this.videoData.clientPlaybackNonce,this.V.q5(),this.Fw&&this.W1()):(this.Y=!0,this.Fw&&ds(this)&&(q===2?this.V.Pd():q===3&&this.V.iR()))};
g.C.gX=function(q){if(q){for(q=0;q<this.stills.length;q++)this.j.logVisibility(this.stills[q].element,!0);this.Fs(1)}else this.W=null,this.Y=!1;this.W1()};
g.C.YW=function(){return this.Fw&&ds(this)};g.Z(oYI,N3);oYI.prototype.NB=function(){var q=this.player.getVideoData();this.V.update({profilePicture:q.profilePicture,author:q.author});this.subscribeButton.channelId=q.Am;var a=this.subscribeButton;q.subscribed?a.V():a.U()};g.Z($a,g.u);$a.prototype.select=function(){this.api.Fj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.L$||void 0)&&this.api.logClick(this.element)};
$a.prototype.onClick=function(q){if(g.yw(this.api.B())&&this.api.T("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var a=this.suggestion.La(),w={};g.z4(this.api,w);a=g.sk(a,w);g.mE(a,this.api,q)}else g.J0(q,this.api,this.U,this.suggestion.sessionData||void 0)&&this.select()};
$a.prototype.onKeyPress=function(q){switch(q.keyCode){case 13:case 32:q.defaultPrevented||(this.select(),q.preventDefault())}};
$a.prototype.onVideoDataChange=function(){var q=this.api.getVideoData(),a=this.api.B();this.U=q.J8?!1:a.Y};g.Z(sG,N3);g.C=sG.prototype;g.C.create=function(){N3.prototype.create.call(this);var q=this.player.getVideoData();q&&(this.videoData=q);this.F5();this.U.C(this.player,"appresize",this.F5);this.U.C(this.player,"onVideoAreaChange",this.F5);this.U.C(this.player,"videodatachange",this.onVideoDataChange);this.U.C(this.player,"autonavchange",this.U4);this.U.C(this.player,"onAutonavCancelled",this.Pi);q=this.videoData.autonavState;q!==this.J&&this.U4(q);this.U.C(this.element,"transitionend",this.Sw)};
g.C.destroy=function(){g.JE(this.U);g.Gr(this.stills);this.stills=[];N3.prototype.destroy.call(this);g.wU(this.element,"ytp-show-tiles");this.X.stop();this.J=this.videoData.autonavState};
g.C.Ao=function(){return this.videoData.autonavState!==1};
g.C.show=function(){var q=this.Fw;N3.prototype.show.call(this);g.wU(this.element,"ytp-show-tiles");this.player.B().U?g.vv(this.X):this.X.start();(this.L||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.ui(this.player,!1);Fn(this)?(Cu(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.V.select(!0):this.V.Pd():this.videoData.autonavState===3&&this.V.iR()):(g.ui(this.player,!0),Cu(this));q!==this.Fw&&this.player.logVisibility(this.element,!0)};
g.C.hide=function(){var q=this.Fw;N3.prototype.hide.call(this);this.V.iR();Cu(this);q!==this.Fw&&this.player.logVisibility(this.element,!1)};
g.C.Sw=function(q){q.target===this.element&&this.F5()};
g.C.F5=function(){var q,a,w,G;var k=((q=this.videoData)==null?0:(a=q.suggestions)==null?0:a.length)?(w=this.videoData)==null?void 0:w.suggestions:[(G=this.videoData)==null?void 0:g.Vq(G)];if(k.length){g.gU(this.element,"ytp-endscreen-paginate");var b=this.j.f3(!0,this.j.isFullscreen());if(q=g.MT(this.j))q=q.o8()?48:32,b.width-=q*2;var O=b.width/b.height;G=96/54;a=q=2;var e=Math.max(b.width/96,2),N=Math.max(b.height/54,2);w=k.length;var Y=w*4;for(Y-=4;Y>0&&(q<e||a<N);){var P=q/2,K=a/2,d=q<=e-2&&Y>=
K*4,T=a<=N-2&&Y>=P*4;if((P+1)/K*G/O>O/(P/(K+1)*G)&&T)Y-=P*4,a+=2;else if(d)Y-=K*4,q+=2;else if(T)Y-=P*4,a+=2;else break}G=!1;Y>=12&&w*4-Y<=6&&(a>=4||q>=4)&&(G=!0);Y=q*96;e=a*54;O=Y/e<O?b.height/e:b.width/Y;O=Math.min(O,2);Y=Math.floor(Math.min(b.width,Y*O));e=Math.floor(Math.min(b.height,e*O));b=this.table.element;b.ariaLive="polite";g.qz(b,Y,e);g.IR(b,{marginLeft:Y/-2+"px",marginTop:e/-2+"px"});this.V.vr(g.Vq(this.videoData));this.V instanceof lS&&eJ(this.V);g.kX(this.element,"ytp-endscreen-takeover",
Fn(this));Cu(this);Y+=4;e+=4;O=0;b.ariaBusy="true";for(N=0;N<q;N++)for(P=0;P<a;P++)if(K=O,T=0,G&&N>=q-2&&P>=a-2?T=1:P%2===0&&N%2===0&&(P<2&&N<2?P===0&&N===0&&(T=2):T=2),K=g.jm(K+this.W,w),T!==0){d=this.stills[O];d||(d=new $a(this.player),this.stills[O]=d,b.appendChild(d.element));var F=Math.floor(e*P/a),J=Math.floor(Y*N/q),Q=Math.floor(e*(P+T)/a)-F-4,B=Math.floor(Y*(N+T)/q)-J-4;g.Wa(d.element,J,F);g.qz(d.element,B,Q);g.IR(d.element,"transitionDelay",(P+N)/20+"s");g.kX(d.element,"ytp-videowall-still-mini",
T===1);g.kX(d.element,"ytp-videowall-still-large",T>2);T=Math.max(B,Q);g.kX(d.element,"ytp-videowall-still-round-large",T>=256);g.kX(d.element,"ytp-videowall-still-round-medium",T>96&&T<256);g.kX(d.element,"ytp-videowall-still-round-small",T<=96);K=k[K];d.suggestion!==K&&(d.suggestion=K,T=d.api.B(),F=g.qG(d.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.Ng(d,K,F),g.yw(T)&&!d.api.T("web_player_log_click_before_generating_ve_conversion_params")&&(T=K.La(),F={},g.xU(d.api,"addEmbedsConversionTrackingParams",
[F]),T=g.sk(T,F),d.updateValue("url",T)),(K=(K=K.sessionData)&&K.itct)&&d.api.setTrackingParams(d.element,K));O++}b.ariaBusy="false";g.kX(this.element,"ytp-endscreen-paginate",O<w);for(k=this.stills.length-1;k>=O;k--)q=this.stills[k],g.Cn(q.element),g.wB(q);this.stills.length=O}};
g.C.onVideoDataChange=function(){var q=this.player.getVideoData(1);this.videoData!==q&&(q!=null&&g.Vq(q)?(this.W=0,this.videoData=q,this.F5()):this.player.d8("missg",{vid:(q==null?void 0:q.videoId)||"",cpn:(q==null?void 0:q.clientPlaybackNonce)||""}))};
g.C.xu=function(){this.W+=this.stills.length;this.F5()};
g.C.C8=function(){this.W-=this.stills.length;this.F5()};
g.C.WG=function(){return this.V.HW()};
g.C.U4=function(q){q===1?(this.L=!1,this.Y=this.videoData.clientPlaybackNonce,this.V.q5(),this.Fw&&this.F5()):(this.L=!0,this.Fw&&Fn(this)&&(q===2?this.V.Pd():q===3&&this.V.iR()))};
g.C.Pi=function(q){if(q){for(q=0;q<this.stills.length;q++)this.j.logVisibility(this.stills[q].element,!0);this.U4(1)}else this.Y=null,this.L=!1;this.F5()};
g.C.YW=function(){return this.Fw&&Fn(this)};g.Z(IO6,g.u);g.C=IO6.prototype;g.C.rS=function(){switch(this.buttonType){case 1:var q="Watch again on YouTube";var a=156915;break;case 2:q="Continue watching on YouTube";a=156942;break;default:q="Continue watching on YouTube",a=156942}this.update({content:q});this.j.hasVe(this.element)&&this.j.destroyVe(this.element);this.j.createClientVe(this.element,this,a)};
g.C.onClick=function(q){this.j.T("web_player_log_click_before_generating_ve_conversion_params")&&this.j.logClick(this.element);g.mE(this.getVideoUrl(),this.j,q);this.j.T("web_player_log_click_before_generating_ve_conversion_params")||this.j.logClick(this.element)};
g.C.getVideoUrl=function(){var q=!0;switch(this.buttonType){case 1:q=!0;break;case 2:q=!1}q=this.j.getVideoUrl(q,!1,!1,!0);var a=this.j.B();if(g.yw(a)){var w={};g.yw(a)&&g.xU(this.j,"addEmbedsConversionTrackingParams",[w]);q=g.sk(q,w)}return q};
g.C.logVisibility=function(){this.j.logVisibility(this.element,this.Fw&&this.D)};
g.C.show=function(){g.u.prototype.show.call(this);this.logVisibility()};
g.C.hide=function(){g.u.prototype.hide.call(this);this.logVisibility()};
g.C.Si=function(q){g.u.prototype.Si.call(this,q);this.logVisibility()};g.Z(Zr,N3);Zr.prototype.hasSuggestions=function(){var q;return(q=this.V)==null?void 0:q.hasSuggestions()};
Zr.prototype.show=function(){if(this.player.getPlayerState()!==3){N3.prototype.show.call(this);var q=this.U;if(q){var a=this.V.hasSuggestions();g.kX(this.element,"ytp-shorts-branded-ui",a);a?q.show():q.hide()}var w;(w=g.MT(this.player))==null||w.tW(!0);this.player.logVisibility(this.element,!0);this.watchButton.Si(!0)}};
Zr.prototype.hide=function(){N3.prototype.hide.call(this);var q;(q=g.MT(this.player))==null||q.tW(!1);this.player.logVisibility(this.element,!1);this.watchButton.Si(!1)};g.Z(zU8,g.md);g.C=zU8.prototype;g.C.zR=function(){var q=this.player.getVideoData(),a=q.mutedAutoplay&&(q.limitedPlaybackDurationInSeconds>0||q.endSeconds>0||q.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!a)return!0;var w;var G=!!((q==null?0:g.Vq(q))||(q==null?0:(w=q.suggestions)==null?0:w.length));G=!uwI(this.player)||G;q=q.PQ;w=this.player.oB();return G&&!q&&!w&&!a};
g.C.YW=function(){return this.endScreen.YW()};
g.C.nB=function(){return this.YW()?this.endScreen.WG():!1};
g.C.qB=function(){this.player.XC("endscreen");g.md.prototype.qB.call(this)};
g.C.load=function(){var q=this.player.getVideoData();var a=q.transitionEndpointAtEndOfStream;if(a&&a.videoId){var w=this.player.Hq().KT.get("heartbeat"),G=g.Vq(q);!G||a.videoId!==G.videoId||q.Id?(this.player.Fj(a.videoId,void 0,void 0,!0,!0,a),w&&w.aV("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),q=!0):q=!1}else q=!1;q||(g.md.prototype.load.call(this),this.endScreen.show())};
g.C.unload=function(){g.md.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.C.onCueRangeEnter=function(q){this.zR()&&(this.endScreen.created||this.endScreen.create(),q.getId()==="load"&&this.load())};
g.C.onCueRangeExit=function(q){q.getId()==="load"&&this.loaded&&this.unload()};
g.C.onVideoDataChange=function(){vYx(this);this.W&&tk7(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.V?this.endScreen=new Pu(this.player):this.endScreen=new sG(this.player),g.p(this,this.endScreen),g.DZ(this.player,this.endScreen.element,4))};g.Jq("endscreen",zU8);})(_yt_player);
