(function(g){var window=this;'use strict';var Wyx=function(q,a){if(!Number.isFinite(q))return String(q);q=String(q);var w=q.indexOf(".");w===-1&&(w=q.length);var G=q[0]==="-"?"-":"";G&&(q=q.substring(1));return G+(0,g.tKI)("0",Math.max(0,a-w))+q},DQI=function(){return{G:"svg",
Z:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{G:"path",Z:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},RUl=function(){return{G:"svg",
Z:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{G:"path",Z:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},qQx=function(q){typeof q==="number"?(this.date=yky(q,0,1),EG(this,1)):g.bV(q)?(this.date=yky(q.getFullYear(),q.getMonth(),q.getDate()),EG(this,q.getDate())):(this.date=new Date(g.Kw()),q=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),EG(this,q))},yky=function(q,a,w){a=new Date(q,a,w);
q>=0&&q<100&&a.setFullYear(a.getFullYear()-1900);return a},EG=function(q,a){q.getDate()!=a&&q.date.setUTCHours(q.date.getUTCHours()+(q.getDate()<a?1:-1))},VU=function(q,a){g.Gd.call(this,q,{G:"div",
N:"ytp-reminder-menu",Z:{role:"menu",tabindex:"-1"},K:[{G:"div",N:"ytp-reminder-menu-contents",K:[{G:"div",N:"ytp-reminder-menu-items"}]}]},100,!0);this.V=a;this.W=[];this.menuPopupRenderer=void 0;this.items=this.oW("ytp-reminder-menu-items");this.hide()},gTB=function(q){return(q.menuPopupRenderer&&q.menuPopupRenderer.items||[]).reduce(function(a,w){w&&w.menuServiceItemRenderer&&a.push(w.menuServiceItemRenderer);
return a},[])},JJ=function(q){g.u.call(this,{G:"div",
K:[{G:"button",vT:["ytp-offline-slate-button","ytp-button"],K:[{G:"div",N:"ytp-offline-slate-button-icon",ue:"{{icon}}"},{G:"div",N:"ytp-offline-slate-button-text",ue:"{{text}}"}]}]});this.j=q;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.U=void 0;this.Y=this.V=null;(this.L=this.oW("ytp-offline-slate-button"))&&this.C(this.L,"click",this.X);this.hide()},wNc=function(q,a,w){!q.toggleButtonRenderer&&a&&a.toggleButtonRenderer?q.toggleButtonRenderer=a.toggleButtonRenderer:
a&&a.toggleButtonRenderer||(q.toggleButtonRenderer=null);
!q.upcomingEventReminderButtonRenderer&&w&&g.I(w,aA6)?q.upcomingEventReminderButtonRenderer=g.I(w,aA6):w&&g.I(w,aA6)||(q.upcomingEventReminderButtonRenderer=null);m6(q)},m6=function(q){if(q.toggleButtonRenderer){var a=q.toggleButtonRenderer;
if(a.isToggled){var w=a.toggledText?g.OE(a.toggledText):"";q.update({text:w,icon:G$x(a.toggledIcon)})}else w=a.defaultText?g.OE(a.defaultText):"",q.update({text:w,icon:G$x(a.defaultIcon)});q.show()}else q.upcomingEventReminderButtonRenderer?(a=k$J(q))?(w=a.text?g.OE(a.text):"",q.update({text:w,icon:G$x(a.icon)}),q.show()):q.hide():q.hide()},O77=function(q,a,w){q.Y||(q.Y=new g.o5(q.j.B().xE));
var G={context:g.b$(q.Y.config_||g.GZ())};g.$f()&&(G.context.clientScreenNonce=g.$f());G.params=w;g.I5(q.Y,a,G,{timeout:5E3,onSuccess:function(){q.upcomingEventReminderButtonRenderer&&q.U&&(q.upcomingEventReminderButtonRenderer.currentState=q.U,q.U=void 0)},
onError:function(){b7e(q)},
onTimeout:function(){b7e(q)}})},b7e=function(q){q.toggleButtonRenderer?(q.toggleButtonRenderer.isToggled=!q.toggleButtonRenderer.isToggled,m6(q)):q.upcomingEventReminderButtonRenderer&&(q.U=void 0,m6(q))},G$x=function(q){if(!q)return null;
switch(q.iconType){case "NOTIFICATIONS":return DQI();case "NOTIFICATIONS_NONE":return RUl();case "NOTIFICATIONS_ACTIVE":return g.$p();default:return null}},k$J=function(q){if(!q.upcomingEventReminderButtonRenderer)return null;
var a=q.U||q.upcomingEventReminderButtonRenderer.currentState;q=g.V(q.upcomingEventReminderButtonRenderer.states||[]);for(var w=q.next();!w.done;w=q.next())if((w=g.I(w.value,lAw))&&w.state===a&&w.button&&g.I(w.button,g.e9))return g.I(w.button,g.e9);return null},eGV=function(q){g.u.call(this,{G:"div",
N:"ytp-offline-slate",K:[{G:"div",N:"ytp-offline-slate-background"},{G:"div",N:"ytp-offline-slate-bar",K:[{G:"span",N:"ytp-offline-slate-icon",K:[{G:"svg",Z:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},K:[{G:"path",Z:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",Z:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",N:"ytp-offline-slate-messages",K:[{G:"div",N:"ytp-offline-slate-main-text",Z:{"aria-label":"{{label}}"},ue:"{{mainText}}"},{G:"div",N:"ytp-offline-slate-subtitle-text",ue:"{{subtitleText}}"}]},{G:"span",N:"ytp-offline-slate-buttons"}]},{G:"button",vT:["ytp-offline-slate-close-button","ytp-button"],K:[g.Yp()]},{G:"button",vT:["ytp-offline-slate-open-button","ytp-button"],K:[g.Nl()]}]});var a=this;this.api=q;this.V=this.U=null;this.background=this.oW("ytp-offline-slate-background");
this.W=this.oW("ytp-offline-slate-bar");this.L=new g.o1(function(){g.gU(a.W,"ytp-offline-slate-bar-fade")},15E3);
this.X=!1;this.Y=new g.o1(function(){g.gU(a.element,"ytp-offline-slate-collapsed")},15E3);
g.p(this,this.Y);g.p(this,this.L);this.countdownTimer=new g.o1(this.yb,1E3,this);this.C(q,"presentingplayerstatechange",this.f4);this.C(q,"livestatedata",this.NB);this.C(this.oW("ytp-offline-slate-close-button"),"click",function(){g.gU(a.element,"ytp-offline-slate-collapsed")});
this.C(this.oW("ytp-offline-slate-open-button"),"click",function(){g.wU(a.element,"ytp-offline-slate-collapsed")});
this.hide();q=this.getVideoData();q.getPlayerResponse()&&(q=q.getPlayerResponse().playabilityStatus)&&this.NB(q);q=this.api.getPresentingPlayerType()===8&&!this.getVideoData().FB;var w=this.api.getPresentingPlayerType()===8;g.kX(this.element,"ytp-offline-slate-premiere-trailer",q);g.kX(this.element,"ytp-offline-slate-hide-background",w)},NX8=function(q,a,w){if(a){var G=a.subtitleText!=null?g.OE(a.subtitleText):"";
w=w?w:a.mainText!=null?g.OE(a.mainText):"";var k,b,O,e;a=(e=(k=a.mainText)==null?void 0:(b=k.accessibility)==null?void 0:(O=b.accessibilityData)==null?void 0:O.label)!=null?e:w;q.update({mainText:w,subtitleText:G,label:a});g.kX(q.element,"ytp-offline-slate-single-text-line",!G);g.kX(q.W,"ytp-offline-slate-bar-hidden",!w&&!G)}},QU=function(q,a){var w=(0,g.Zj)();
this.trigger=q;this.V=a;this.W=w},$Ew=function(q){g.md.call(this,q);
var a=this;this.X=!1;this.S=0;this.D=!1;this.U=new g.o1(function(){YQx(a)},0);
this.V=this.heartbeatParams=null;this.Y=!1;this.L=new g.h1(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.F9=new g.o5(void 0);this.attestationResponse=Promise.resolve(void 0);this.J=Promise.resolve(void 0);this.utcOffsetMinutes=-(new qQx).getTimezoneOffset();this.W=new g.Ee(this);g.p(this,this.U);g.p(this,this.W);PuB(this);Kc8(this);this.W.C(q,"heartbeatparams",this.Wk);this.W.C(q,"presentingplayerstatechange",this.AY);this.W.C(q,"videoplayerreset",this.zK);this.W.C(q,g.oM("heartbeat"),
this.onCueRangeEnter);this.Y&&this.V&&dEc(this,void 0,this.V);var w=new g.Xo(AJ(this,!0),0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),G=new g.Xo(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});q.N9([w,G]);TXI(this)},TXI=function(q){var a=q.getVideoData();
!a.T("use_rta_for_player")&&a.mP&&(a=a.botguardData)&&g.Kx(a,q.player.B())},sqK=function(q){var a,w;
return g.h(function(G){if(G.U==1)return g.n(G,g.MCf(),2);if(!G.V)return q.sequenceNumber>=3?G.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):G.return(void 0);a=q.getVideoData();w={};return G.return(g.n3l((w.cpn=a.clientPlaybackNonce,w.encryptedVideoId=a.videoId||"",w),1500))})},PuB=function(q){var a=q.getVideoData();
if(a.mP)if(a.T("use_rta_for_player"))q.attestationResponse=sqK(q);else if(a=new g.IbK(a),g.Nq.isInitialized()||q.sequenceNumber>=3){var w=Promise,G=w.resolve,k=null;if(a.videoData.qj){var b=g.uoJ(a);if(b){k={};var O={};b=b.split("&");b=g.V(b);for(var e=b.next();!e.done;e=b.next())e=e.value.split("="),e.length===2&&(O[e[0]]=e[1]);O.r1a&&(k.webResponse=O.r1a);O.r1c&&(k.error=FcJ[Number(O.r1c)]);k.challenge=a.videoData.qj}}q.attestationResponse=G.call(w,k||void 0)}},Cu6=function(q){var a=q.getVideoData();
if(!g.op(q.getVideoData())||a.qJ)return!1;if(a.D){q=a.D.flavor==="playready"&&a.T("html5_innertube_heartbeats_for_playready");var w=a.D.flavor==="widevine"&&a.T("html5_innertube_heartbeats_for_widevine");a=g.Ni(a.D)&&a.T("html5_innertube_heartbeats_for_fairplay");return!(q||w||a)}return!0},Z7K=function(q){if(Cu6(q))return!!q.heartbeatParams;
var a=q.getVideoData();return!g.op(q.getVideoData())||a.J4||a.FX?!!a.heartbeatToken:!1},xa=function(q,a){if(!q.U.isActive()&&q.X){var w=q.getVideoData();
if(Z7K(q)||w.isLivePlayback){if(a===void 0)if(q.D)if(q.Y)a=7500;else{var G;a=((G=q.heartbeatParams)==null?0:G.interval)?q.heartbeatParams.interval*1E3:q.getVideoData().Xc||6E4}else a=1E3;q.U.start(a)}}},mE6=function(q,a,w){a.qS&&(w=g.sk(w,{internalipoverride:a.qS}));
var G={cpn:a.clientPlaybackNonce};a.contextParams&&(G.context_params=a.contextParams);a.L0&&(G.kpt=a.L0);w=g.sk(w,G);g.Cy(w,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(k){if(!q.U.isActive()&&Lu(q)){q.L.reset();q.sequenceNumber++;k=k.responseText;var b=ETx(k);if(b){q.player.zl("onHeartbeat",b);var O=b.status==="ok"?b.stop_heartbeat?2:0:b.status==="stop"?1:b.status==="live_stream_offline"?0:-1}else O=(O=k.match(V_c))?O[1]==="0"?0:1:-1;JpK(q,void 0,b,k,O)}},
onError:function(k){Lu(q)&&Bu(q,!0,"net-"+k.status)},
onTimeout:function(){Lu(q)&&Bu(q,!0,"timeout")},
withCredentials:!0})},YQx=function(q){var a,w;
g.h(function(G){a=q.player.B();w=q.getVideoData();if(!Lu(q))return G.return();if(Cu6(q))return QqI(q,a,w),G.Gl(0);PuB(q);return g.n(G,Apx(q,a,w),0)})},QqI=function(q,a,w){var G;
if((G=q.heartbeatParams)!=null&&G.url){var k=g.sk(q.heartbeatParams.url,{request_id:g.Vuf()});w.f7&&(k=g.sk(k,{vvt:w.f7}),w.mdxEnvironment&&(k=g.sk(k,{mdx_environment:w.mdxEnvironment})));g.B8(a,w.oauthToken).then(function(b){b&&(k=g.sk(k,{access_token:b}));mE6(q,w,k)})}},Lu=function(q){var a=q.getVideoData();
return q.player.getPresentingPlayerType()===3||g.v(q.player.getPlayerStateObject(q.getPlayerType()),4)?!1:Z7K(q)||a.isLivePlayback?!0:(rs(q),!1)},Apx=function(q,a,w){var G,k,b,O,e,N,Y,P,K,d,T,F,J,Q,B,L,M,H,X,D;
return g.h(function(z){if(z.U==1)return G="player/heartbeat",b={videoId:w.videoId,sequenceNumber:q.sequenceNumber,heartbeatServerData:(k=q.UK)!=null?k:w.heartbeatServerData},q.J=q.attestationResponse,w.mP?g.n(z,q.J,3):z.Gl(2);z.U!=2&&(b.attestationResponse=z.V);O=g.Vk(w);N=(e=O.client)!=null?e:{};N.utcOffsetMinutes=q.utcOffsetMinutes;b.context=O;b.cpn=w.clientPlaybackNonce;if(Y=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)N.timeZone=Y;P={heartbeatChecks:[]};
if(K=w.getPlayerResponse())w.heartbeatToken&&(b.heartbeatToken=w.heartbeatToken),(d=K.playabilityStatus)&&(T=d.liveStreamability)&&T.liveStreamabilityRenderer&&P.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");w.heartbeatToken&&P.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.lt(a)&&(P.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),F=xE6(q),J={},F!==null&&(J.clientPlayerPositionUtcMillis=F),B=(Q=q.player.Hq())==null?void 0:g.SW(Q),M=((L=B)==null?void 0:L.freePreviewWatchedDuration)||
0,M>0&&(J.freePreviewWatchedDuration={seconds:""+M}),P.unpluggedParams=J);b.heartbeatRequestParams=P;w.isLivePlayback?(H=xE6(q),H!==null&&(b.playbackState||(b.playbackState={}),b.playbackState.playbackPosition={utcTimeMillis:H})):a.T("enable_heartbeat_vod_playback_position")&&(X=Lcw(q),X!==null&&(b.playbackState||(b.playbackState={}),b.playbackState.playbackPosition={streamTimeMillis:X}));q.player.publish("heartbeatRequest",b);D={timeout:3E4,onSuccess:function(Oj){if(!q.U.isActive()&&Lu(q)){var $l=
q.getVideoData(),ey=$l.mP&&q.J==null,Nm;$l.mP=!((Nm=Oj.heartbeatAttestationConfig)==null||!Nm.requiresAttestation)||ey;ey=Oj.playabilityStatus;Nm=JSON.stringify(ey)||"{}";Oj.authenticationMismatch&&q.player.d8("authshear",{});var a_=-1;var BJ=Oj.playabilityStatus;BJ&&(q.player.zl("onHeartbeat",BJ),BJ.status==="OK"?a_=Oj.stopHeartbeat?2:0:BJ.status==="UNPLAYABLE"?a_=1:BJ.status==="LIVE_STREAM_OFFLINE"&&(a_=0));q.sequenceNumber&&a_===-1||q.L.reset();q.sequenceNumber++;Oj.heartbeatServerData&&(q.UK=
Oj.heartbeatServerData);$l.Os=Oj;(BJ=Oj.playerCueRangeSet)&&g.Cc($l,BJ);Oj.playerCueRanges&&Oj.playerCueRanges.length>0&&($l.cueRanges=Oj.playerCueRanges);var WJ,gy;((WJ=Oj.progressBarConfig)==null?0:WJ.progressBarStartPosition)&&((gy=Oj.progressBarConfig)==null?0:gy.progressBarEndPosition)&&($l.progressBarStartPosition=Oj.progressBarConfig.progressBarStartPosition,$l.progressBarEndPosition=Oj.progressBarConfig.progressBarEndPosition);$l.compositeLiveIngestionOffsetToken=Oj.compositeLiveIngestionOffsetToken;
Oj.compositeLiveStatusToken!==$l.compositeLiveStatusToken&&($l.compositeLiveStatusToken=Oj.compositeLiveStatusToken);$l.publish("dataupdated");JpK(q,Oj,ey,Nm,a_)}},
onError:function(Oj){Lu(q)&&Bu(q,!0,"net-"+Oj.status)},
onTimeout:function(){Lu(q)&&Bu(q,!0,"timeout")}};
g.B8(a,g.li(w)).then(function(Oj){Oj&&(D.Sz="Bearer "+Oj);g.I5(q.F9,G,b,D)});
g.Jm(z)})},JpK=function(q,a,w,G,k){k===-1?(w="decode "+g.xe(G,3),Bu(q,!1,w)):k===2?(rs(q),q.D=!0):(q.S=0,q.U.stop(),k===1?(q.D=!1,w&&w.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&q.player.nF(!0),k="pe."+(w==null?void 0:w.errorCode)+";ps."+(w==null?void 0:w.status),q.player.q_("heartbeat.stop",2,q.Jp(G),k),g.aw("heartbeatActionPlayerHalted",BXw(w)),(a==null?0:a.videoTransitionEndpoint)&&w&&(a=a.videoTransitionEndpoint,(G=g.I(a,g.Er))&&rpw(q,G,w,{itct:a==null?void 0:a.clickTrackingParams}))):(q.D=
!0,G=0,q.Y&&w&&(G=dEc(q,a,w),q.player.publish("livestatedata",w)),G?xa(q,G):xa(q)))},dEc=function(q,a,w){var G=w.liveStreamability&&w.liveStreamability.liveStreamabilityRenderer,k=!(!G||!(G.switchStreamsImmediately||G.transitionTiming&&G.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
a=nT6(q,a,G);var b=q.getVideoData(),O=q.player.getPlayerStateObject(q.getPlayerType()),e=O.isPlaying()&&!g.WD(b)&&!q.player.isAtLiveHead(q.getPlayerType());if(b.B().TZ()){var N,Y=((N=q.player.Z0())==null?void 0:N.Kk())||{};Y.status=w.status||"";Y.dvr=""+ +e;Y["switch"]=""+ +k;Y.ended=""+ +!(!G||!G.displayEndscreen);q.player.d8("heartbeat",Y)}N=q.player.T("always_cache_redirect_endpoint");if(e&&!k&&!N)return a;Y=G&&G.streamTransitionEndpoint&&g.I(G.streamTransitionEndpoint,g.Er);var P=G&&G.transitionTiming;
if(P==="STREAM_TRANSITION_TIMING_AT_STREAM_END")q.getVideoData().transitionEndpointAtEndOfStream=Y;else if(N&&!Y&&q.getVideoData().transitionEndpointAtEndOfStream)q.getVideoData().transitionEndpointAtEndOfStream=void 0;else if(!N&&Y&&rpw(q,Y,w))return a;if(e&&!k&&N||N&&Y&&(P==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||P==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&rpw(q,Y,w))return a;if(w.status.toUpperCase()==="OK"){k=G&&G.broadcastId;e=q.V&&q.V.liveStreamability&&q.V.liveStreamability.liveStreamabilityRenderer&&
q.V.liveStreamability.liveStreamabilityRenderer.broadcastId;N=k!==e&&k!=null;if(!g.vD(b)||N){var K={video_id:b.videoId};b.oX&&(K.is_live_destination="1");K.disable_watch_next=!0;K.raw_watch_next_response=b.getWatchNextResponse();K.autonav_state=b.autonavState;K.oauth_token=b.oauthToken;K.XV=b.XV;b.L&&(K.vss_credentials_token=b.L,K.vss_credentials_token_type=b.aP);b.f7&&(K.vvt=b.f7);G=void 0;g.vD(b)?N&&(G=new QU("broadcastIdChanged",e+","+k),q.aV("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",
w)):(k&&(G=new QU("formatsReceived",""+k)),q.aV("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",w));q.player.loadVideoByPlayerVars(K,void 0,void 0,void 0,G);return a}q.player.fu("heartbeat",q.getPlayerType())}G&&G.displayEndscreen&&(q.offlineSlate?(q=q.offlineSlate,q.X=!0,q.Fw&&q.api.dB()):O.isBuffering()&&(b=((K=q.player.Z0())==null?void 0:K.Kk())||{},q.player.d8("hbse",b,!0),q.player.T("html5_report_eos")?q.player.dB(!0,"h"):q.player.dB(),q.player.zl("onLiveMediaEnded",
w)));return a},nT6=function(q,a,w){return q.player.T("web_player_use_heartbeat_poll_delay_ms")&&(q=Number(a==null?void 0:a.pollDelayMs))?q:(w=Number(w==null?void 0:w.pollDelayMs))?w:0},Bu=function(q,a,w){if(!q.U.isActive()){q.U.stop();
q.S++;var G=a?"heartbeat.net":"heartbeat.servererror";var k=q.getVideoData();if(k.Ly||a&&!g.op(q.getVideoData())&&!Z7K(q)&&k.isLivePlayback)k=!1;else{var b,O;((O=q.heartbeatParams)==null?0:O.retries)?b=q.heartbeatParams.retries:b=k.Dg||5;k=q.S>=b}k?(g.aw("heartbeatActionPlayerHalted",a?{enforcedPolicyToHaltOnNetworkFailure:!0}:BXw()),(a=q.getVideoData())&&a.isLivePlayback?q.player.q_(G,1,"Video playback interrupted. Please try again.",w):q.player.q_(G,1,"Sorry, there was an error while licensing this video.",
w)):(xa(q,q.L.getValue()),g.Sz(q.L))}},BXw=function(q){var a={enforcedPolicyToHaltOnNetworkFailure:!1};
q&&(a.serializedServerContext=q.additionalLoggingData);return a},rs=function(q){q.S=0;
q.U.stop();q.D=!1;q.sequenceNumber=0},Kc8=function(q){var a=q.getVideoData(),w=q.player.B();
if(a.isLivePlayback)if(g.Vw(w.D)){q.Y=!0;q.X=!0;if(!g.Nh(w)||g.lt(w))q.offlineSlate=new eGV(q.player),g.p(q,q.offlineSlate),g.DZ(q.player,q.offlineSlate.element,4);(a=a.getPlayerResponse())&&a.playabilityStatus&&(q.V=a.playabilityStatus);var G;((G=q.V)==null?void 0:G.status)!=="UNPLAYABLE"&&(q.V?(G=nT6(q,void 0,q.V.liveStreamability&&q.V.liveStreamability.liveStreamabilityRenderer))?xa(q,G):xa(q,7500):xa(q,AJ(q,!0)))}else q.player.q_("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK",
"nolive.1");else g.Vx(a.J,"heartbeat")&&q.player.fu("heartbeat",q.getPlayerType())},rpw=function(q,a,w,G){var k=a&&a.videoId;
return k?(q.player.Fj(k,Object.assign({},{autonav:"1"},G||{}),void 0,!0,!0,a,g.li(q.getVideoData())),q.aV("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",w),!0):!1},xE6=function(q){return(q=q.player.getProgressState(q.getPlayerType()).ingestionTime)&&isFinite(q)?""+Math.floor(q*1E3):null},Lcw=function(q){return(q=q.player.getCurrentTime(q.getPlayerType()))&&isFinite(q)?""+Math.floor(q*1E3):null},AJ=function(q,a){a=a===void 0?!1:a;
q=q.getVideoData();return q.T("html5_use_server_init_heartbeat_delay")?isNaN(q.Xc)?15E3:q.Xc:a?1E3:2E3},ETx=function(q){try{var a=JSON.parse(q);
return a!=null?a:void 0}catch(w){}},M_6={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
M_6={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["am","pm"],DATEFORMATS:["EEEE, d MMMM y",
"d MMMM y","d MMM y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:3};
var FcJ=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],hG6={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.C=qQx.prototype;g.C.qW=M_6.FIRSTDAYOFWEEK;g.C.Qq=M_6.FIRSTWEEKCUTOFFDAY;
g.C.clone=function(){var q=new qQx(this.date);q.qW=this.qW;q.Qq=this.Qq;return q};
g.C.getFullYear=function(){return this.date.getFullYear()};
g.C.getYear=function(){return this.getFullYear()};
g.C.getMonth=function(){return this.date.getMonth()};
g.C.getDate=function(){return this.date.getDate()};
g.C.getTime=function(){return this.date.getTime()};
g.C.getDay=function(){return this.date.getDay()};
g.C.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.C.getUTCMonth=function(){return this.date.getUTCMonth()};
g.C.getUTCDate=function(){return this.date.getUTCDate()};
g.C.getUTCDay=function(){return this.date.getDay()};
g.C.getUTCHours=function(){return this.date.getUTCHours()};
g.C.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.C.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.C.set=function(q){this.date=new Date(q.getFullYear(),q.getMonth(),q.getDate())};
g.C.setFullYear=function(q){this.date.setFullYear(q)};
g.C.setYear=function(q){this.setFullYear(q)};
g.C.setMonth=function(q){this.date.setMonth(q)};
g.C.setDate=function(q){this.date.setDate(q)};
g.C.setTime=function(q){this.date.setTime(q)};
g.C.setUTCFullYear=function(q){this.date.setUTCFullYear(q)};
g.C.setUTCMonth=function(q){this.date.setUTCMonth(q)};
g.C.setUTCDate=function(q){this.date.setUTCDate(q)};
g.C.add=function(q){if(q.years||q.months){var a=this.getMonth()+q.months+q.years*12,w=this.getYear()+Math.floor(a/12);a%=12;a<0&&(a+=12);a:{switch(a){case 1:var G=w%4!=0||w%100==0&&w%400!=0?28:29;break a;case 5:case 8:case 10:case 3:G=30;break a}G=31}G=Math.min(G,this.getDate());this.setDate(1);this.setFullYear(w);this.setMonth(a);this.setDate(G)}q.days&&(w=this.getYear(),a=w>=0&&w<=99?-1900:0,q=new Date((new Date(w,this.getMonth(),this.getDate(),12)).getTime()+q.days*864E5),this.setDate(1),this.setFullYear(q.getFullYear()+
a),this.setMonth(q.getMonth()),this.setDate(q.getDate()),EG(this,q.getDate()))};
g.C.equals=function(q){return!(!q||this.getYear()!=q.getYear()||this.getMonth()!=q.getMonth()||this.getDate()!=q.getDate())};
g.C.toString=function(){var q=this.getFullYear(),a=q<0?"-":q>=1E4?"+":"";return[a+Wyx(Math.abs(q),a?6:4),Wyx(this.getMonth()+1,2),Wyx(this.getDate(),2)].join("")+""};
g.C.valueOf=function(){return this.date.valueOf()};var SQI=new g.Ze("addUpcomingEventReminderEndpoint");var fAw=new g.Ze("removeUpcomingEventReminderEndpoint");var H7x=new g.Ze("updateUpcomingEventReminderButtonStateCommand");var aA6=new g.Ze("upcomingEventReminderButtonRenderer"),lAw=new g.Ze("upcomingEventReminderButtonStateRenderer");g.Z(VU,g.Gd);
VU.prototype.updateMenuItems=function(){var q=this,a=gTB(this),w=0;w=0;for(var G={};w<a.length;G={Ds:void 0},w++){var k=this.W[w];k||(k=new g.u({G:"div",N:"ytp-reminder-menu-item",Z:{role:"menuitem",tabindex:"0"},K:[{G:"div",N:"ytp-reminder-menu-item-icon",ue:"{{icon}}"},{G:"div",N:"ytp-reminder-menu-item-label",ue:"{{text}}"}]}),G.Ds=w,k.listen("click",function(O){return function(){var e=O.Ds;q.DZ();e=gTB(q)[e];q.publish("reminderMenuItemClicked",e.serviceEndpoint||e.command)}}(G)),k.HT(this.items),
this.W[w]=k);
var b=a[w];G=null;switch(b.icon&&b.icon.iconType){case "NOTIFICATIONS":G=DQI();break;case "NOTIFICATIONS_NONE":G=RUl();break;case "NOTIFICATIONS_ACTIVE":G=g.$p()}b=b.text?g.OE(b.text):"";k.update({icon:G,text:b})}for(;w<this.W.length;)this.W.pop().dispose();w===0?this.DZ():this.kF(this.V)};
VU.prototype.hide=function(){this.V&&this.V.removeAttribute("aria-haspopup");g.Gd.prototype.hide.call(this)};
VU.prototype.show=function(){this.V&&this.V.setAttribute("aria-haspopup","true");g.Gd.prototype.show.call(this)};
VU.prototype.qB=function(){g.Gr(this.W);g.Gd.prototype.qB.call(this)};g.Z(JJ,g.u);
JJ.prototype.X=function(){if(this.toggleButtonRenderer){var q=this.toggleButtonRenderer;q.isToggled?this.W(q.toggledServiceEndpoint):this.W(q.defaultServiceEndpoint);q.isToggled=!q.isToggled;m6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.V&&this.V.Fw)this.V.DZ();else{var a=k$J(this);a&&this.W(a.serviceEndpoint||a.command);a=((q=g.I(a==null?void 0:a.command,g.eg))==null?void 0:q.commands)||[];a:{q=g.V(a);for(var w=q.next();!w.done;w=q.next()){var G=a=void 0;if(w=(a=g.I(w.value,g.waU))==
null?void 0:(G=a.popup)==null?void 0:G.menuPopupRenderer){q=w;break a}}q=void 0}this.V||(this.V=new VU(this.j,this.L),this.V.HT(this.element),g.p(this,this.V),this.V.subscribe("reminderMenuItemClicked",this.W,this));a=this.V;a.menuPopupRenderer=q;a.updateMenuItems()}};
JJ.prototype.W=function(q){var a=g.I(q,SQI),w=g.I(q,fAw);if(q&&(a||w)){if(a){var G=a;var k="notification/add_upcoming_event_reminder"}else w&&(G=w,k="notification/remove_upcoming_event_reminder");if(k&&G&&G.params)for(O77(this,k,G.params),q=g.V(G.commands||[]),a=q.next();!a.done;a=q.next())if((a=a.value)&&g.I(a,H7x)){this.U=g.I(a,H7x).state;m6(this);break}}};g.Z(eGV,g.u);g.C=eGV.prototype;g.C.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.C.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.C.NB=function(q){var a,w,G=q==null?void 0:(a=q.liveStreamability)==null?void 0:(w=a.liveStreamabilityRenderer)==null?void 0:w.offlineSlate;if(G){this.U=q;a=G.liveStreamOfflineSlateRenderer;a.canShowCountdown?this.yb():NX8(this,a);var k,b,O,e;if(w=q==null?void 0:(k=q.liveStreamability)==null?void 0:(b=k.liveStreamabilityRenderer)==null?void 0:(O=b.offlineSlate)==null?void 0:(e=O.liveStreamOfflineSlateRenderer)==null?void 0:e.thumbnail){k=0;b=null;O=w.thumbnails;for(e=0;e<O.length;e++)O[e].width>
k&&(k=O[e].width||0,b=O[e].url);b&&(this.background.style.backgroundImage="url("+b+")")}else this.background.style.backgroundImage="";a.actionButtons||a.reminderButton?(this.V||(this.V=new JJ(this.api),this.V.HT(this.oW("ytp-offline-slate-buttons")),g.p(this,this.V)),wNc(this.V,a.actionButtons&&a.actionButtons[0],a.reminderButton)):this.V&&wNc(this.V,null,null);this.U=q}else this.U=null;this.f4()};
g.C.f4=function(q){if(this.api.getPresentingPlayerType()===8)var a=!0;else{var w=this.api.getPlayerStateObject(),G=this.getVideoData();a=G.isLivePlayback&&(w.isBuffering()||g.v(w,2)||g.v(w,64));var k=G.autonavState===2&&g.v(w,2);w=w.isPlaying()&&!g.WD(G)&&!this.api.isAtLiveHead(void 0,!0);a=a&&!w&&!k}a&&this.U?this.Fw?(q==null?0:g.Ox(q,2))&&!this.getVideoData().FB&&(g.wU(this.element,"ytp-offline-slate-collapsed"),this.Y.stop(),g.wU(this.W,"ytp-offline-slate-bar-fade"),this.L.start()):(this.show(),
this.Y.start(),this.api.publish("offlineslatestatechange"),this.X&&this.api.dB()):this.Fw&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.C.yb=function(){var q,a,w,G,k=(q=this.U)==null?void 0:(a=q.liveStreamability)==null?void 0:(w=a.liveStreamabilityRenderer)==null?void 0:(G=w.offlineSlate)==null?void 0:G.liveStreamOfflineSlateRenderer;k&&(q=Math.floor(g.Kw()/1E3),a=k.canShowCountdown&&Number(k.scheduledStartTime),!a||a<=q?(NX8(this,k),this.countdownTimer.stop()):(NX8(this,k,g.$m(a-q)),g.tD(this.countdownTimer)))};
g.C.qB=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.u.prototype.qB.call(this)};QU.prototype.U=function(q){return this.trigger&&q.trigger?this.trigger===q.trigger&&this.V===q.V:!1};
QU.prototype.isExpired=function(){return(0,g.Zj)()-this.W>6E4};
QU.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.V};g.Z($Ew,g.md);g.C=$Ew.prototype;g.C.qB=function(){rs(this);this.player.XC("heartbeat");g.md.prototype.qB.call(this)};
g.C.onCueRangeEnter=function(){this.X=!0;xa(this,AJ(this))};
g.C.Wk=function(q){this.heartbeatParams=q;xa(this,AJ(this))};
g.C.AY=function(q){var a;this.player.getPresentingPlayerType()!==8&&((a=this.V)==null?void 0:a.status)!=="UNPLAYABLE"&&(g.v(q.state,2)||g.v(q.state,64)?(rs(this),this.Y&&(this.X=!0,xa(this,AJ(this,!0)))):(g.v(q.state,1)||g.v(q.state,8))&&xa(this,AJ(this)))};
g.C.zK=function(){this.player.getPresentingPlayerType()!==3&&xa(this,AJ(this))};
g.C.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.C.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.C.AZ=function(q){switch(q){case 4:case 3:return!1}return!0};
g.C.aV=function(q,a,w){q={trigger:q,reason:a};w&&(q.serializedServerContext=w.additionalLoggingData);g.aw("heartbeatActionPlayerTransitioned",q)};
g.C.Jp=function(q){var a="LICENSE",w=ETx(q);if(w)return w.reason||g.uB[a]||"";if(q=q.match(V_c))if(q=Number(q[1]))a=(a=hG6[q.toString()])?a:"LICENSE";return g.uB[a]||""};
g.C.r6=function(){return!!this.offlineSlate&&this.offlineSlate.Fw};
var V_c=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.Jq("heartbeat",$Ew);})(_yt_player);
